### ISSUE TITLE
NoReverseMatch at /search

### ISSUE THREAD

**Issue by goldcoders** [ciur/papermerge#102]
Im running on archlinux , 
but i manage to make it run even if no docs support on how to run this on arch...

all is working fine , except  when searching...
```

Request Method: | GET
-- | --
http://127.0.0.1:8000/search?q=power
3.0.8
NoReverseMatch
Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
/home/uriah/.local/lib/python3.8/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 677
/usr/bin/python
3.8.5
['/home/uriah/.www/papermerge',  '/home/uriah/.www/papermerge',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/uriah/.local/lib/python3.8/site-packages',  '/usr/lib/python3.8/site-packages']
Tue, 1 Sep 2020 11:33:02 +0000

```

Nevery Used django before lol , but even so , i think ive installed it properly with venv 

Ive tried switching to lower version of release but same issue persist...

Dont know if i did something wrong on Django end or apache 
i did test my apache config its ok, 

wsgi_module is loaded properly
Any help would be appreciated...

**Comment by ciur** [comment]
Did you install/run it from master branch? I.e. latest version?

**Comment by goldcoders** [comment]
yes im running it on latest version

**Comment by ciur** [comment]
😀 master branch is development one... i mean the one that I work daily. Anyway that issue is a very easy fix, i will fix it in an hour or so!

**Comment by goldcoders** [comment]
im running the python using this command

```
./.venv/bin/python manage.py runserver
```
since i dont want to clutter my system python packages which is manage by yay my package manager in arch....

my papermerge.conf.py

https://gist.github.com/goldcoders/b0853d2a35aeec38e3fdad8722bfe534

my /etc/httpd/conf/extra/httpd-vhost.conf

```apache2
<VirtualHost *:8000>
    <Directory /home/uriah/.www/papermerge/config>
        Require all granted
    </Directory>

    Alias /media/ /home/uriah/.www/papermerge/media/
    Alias /static/ /home/uriah/.www/papermerge/static/

    <Directory /home/uriah/.www/papermerge/media>
       Require all granted
    </Directory>

    <Directory /home/uriah/.www/papermerge/static>
      Require all granted
    </Directory>

    ServerName papermerge.test
    ServerRoot /home/uriah/.www/papermerge
</VirtualHost>

WSGIPythonHome /home/uriah/.www/papermerge/.venv/
WSGIPythonPath /home/uriah/.www/papermerge/
WSGIScriptAlias / /home/uriah/.www/papermerge/config/wsgi.py


```
added to my /etc/hosts `127.0.0.1   papermerge.test`

**Comment by goldcoders** [comment]
i dont have any errors on , `./.venv/bin/python manage.py check` all the commands required i have it installed.

so i dont know where i fucked up on apache side or python/django ....

i did check my apache conf is correct and syntax is correct and module is loaded

seems like proxying it to this domain name wont work either with 

http://papermerge.test:8000/

![pic-full-200901-2138-06](https://user-images.githubusercontent.com/55337687/91858206-75e13180-ec9b-11ea-92f9-918c501542a3.png)

so its either on django end? sorry im not well verse with django , but im very familiar with the required technology except python and django lol... so im stuck at that area hahaha

**Comment by goldcoders** [comment]
did fstr on the whole directory and got something..

![pic-full-200901-2151-10](https://user-images.githubusercontent.com/55337687/91859675-50552780-ec9d-11ea-8fcf-2174d4449247.png)

can you tell me what to change here on url patterns :) 
i think this one will fix it..

.config/urls.py

![pic-full-200901-2153-04](https://user-images.githubusercontent.com/55337687/91859883-8a262e00-ec9d-11ea-98a8-16d5b8b17046.png)

will wait for your reply thanks

**Comment by ciur** [comment]
@goldcoders, [here is the fix](https://github.com/ciur/papermerge/commit/53fbb4c57c6454ed400fcc2b503504a8b4a619e0)

Sorry, couldn't do it earlier, I did not have computer with me :grin: 
It's good that you opened a ticket - if all tests pass and there is a problem like this - it is bad :(. I will add an unit test to avoid such problems in future.

@goldcoders, fantastic work with installation! Btw, completely unrelated, I used arch linux for long time. Moved to ubuntu just recently.

**Comment by goldcoders** [comment]
using version 1.4.0 fixed it lol  , i did tried now to make pull from remote its fixed thanks

quick note also, i think ./static in .gitignore is not correct, should be /static/ 
i did run ./.venv/bin/python manage.py collectstatic
it populated my stastic folder and git is showing new files which should not
