### ISSUE TITLE
Missing: How to update

### ISSUE THREAD

**Issue by Pyromane** [ciur/papermerge#113]
Similar to the extremely detailed bare metal installation instructions, I miss instructions on how to perform an update.

**Comment by ciur** [comment]
@Pyromane, good point! 
I will update that part of documentation.
Thank you for opening the issue!

**Comment by ciur** [comment]
Hi @Pyromane ,
[Here is documentation](https://papermerge.readthedocs.io/en/latest/updates.html) on how to perform an update.

**Comment by Pyromane** [comment]
Thanks for the instructions!

Should after that
`git checkout`
not a
`git pull`
consequences? Because the changelog.md has not changed for me.

(Sry, I'm still a git newbie)

**Comment by ciur** [comment]
Hi @Pyromane,

``git checkout`` will "checkout" application source code for exact point your are asking for. E.g. ``checkout -b v1.4.5`` will checkout source code to be exact for version 1.4.5. The ``git pull`` command on the hand will retrieve the latest source code from current branch. 
Usually the workflow is:
```
1. git pull                # get latest code from github
2. git checkout -b v1.4.5  # from pulled code, switch to version v1.4.5
```
[I added this points to the documentation.
](https://github.com/ciur/papermerge/commit/a71a8d10ba4ca391e780195955cf6468f4d4f959)

@Pyromane in case you are happy with resolution of this ticket - you may close it.
