### ISSUE TITLE
Problem with non ASCII characters in file names.

### ISSUE THREAD

**Issue by N3tFX** [ciur/papermerge#128]
If the file is uploaded with a file name that has **non** ASCII characters,  Papermerge can't process it. It shows a broken Icon. If the same file is renamed before upload with **only** ASCII characters in its filename, then everything works. I've tried it in the docker version.

**Comment by ciur** [comment]
Hi @N3tFX,

can you please be more specific?
What non ASCII characters are used in file name ? Was it a pdf file ? Or maybe jpeg, tiff, png ? Was there another OCR background job running (working crunching another file in meantime)?

**Comment by N3tFX** [comment]
Basically, ASCII characters [https://en.wikipedia.org/wiki/ASCII](url) are the ones used in the English language and numbers. By **non** ASCII characters I am referring to characters that are not part of the English language. And I have tried it with pdf, jpg and png files. It was the file name that was the problem. When I renamed them with English characters from the ASCII table, everything worked. And no OCR was running in the background as these files where the first I've tried to upload.

**Comment by ciur** [comment]
@N3tFX, 
I tested application with German letters e.g. Änderungen.pdf, with Russian cyrillic e.g. файл.pdf and it worked as expected.
What characters did you use ?

**Comment by N3tFX** [comment]
I have tried it in many other languages, even Japanese. Only if the filename is in English it uploads correctly. Remember, I am using the docker version (v1.4.2). Maybe this happens only in the docker container. By the way here is an error message I see in the logs when I upload a file with non English characters in the file name:

    `UnicodeEncodeError: 'ascii' codec can't encode characters in position 105-107: ordinal not in range(128)`.

The exact same files with English filenames upload without problems.

**Comment by ciur** [comment]
What docker image you use ? Is it [this one](https://hub.docker.com/repository/docker/eugenci/papermerge)? Or the one provided by [linuxserverio](https://fleet.linuxserver.io/image?name=linuxserver/papermerge)?

**Comment by N3tFX** [comment]
I am using the **linuxserver/papermerge** docker. I have tried to run the **eugenci/papermerge** but I can't make it run. It complains about not finding tesseract and not finding the db. I have even try installing it using the instructions in the Papermerge manual [https://papermerge.readthedocs.io/en/latest/setup/docker.html](url) but is fails installing with the error: 

`ERROR: Cannot locate specified Dockerfile: app.dockerfile`

Also another thing I like in the **linuxserver/papermerge** docker, is that it has enviroment options for bind volumes. This way if something happens to the Papermerge container, at least the documents would be safe outside the container in the host machine.

**Comment by ciur** [comment]
Ah, and last question. What OS do you use ? Windows/Linux/MacOS ?
I will create an "issue template" to these questions automatically pop up on opening of the new issues.

**Comment by N3tFX** [comment]
I am using Debian with the latest docker version from docker repositories.

**Comment by ciur** [comment]
@N3tFX , thank you! I will investigate the issue.

**Comment by stoykovstoyk** [comment]
I had the exact same problem with , and the problem is with the linuxserver.io docker image. Don't use it this docker image. I have spend a lot of time until I realized that the non ascii filenames error is due to this docker image not due to anything related to Papermerge. 

Use official documentation provided by Papermerge and install by yourself and you will have it up and running. This is what I did and it fixed it. 

This is not a Papermerge bug and @ciur should not waste time on it.

**Comment by ciur** [comment]
I agree with @stoykovstoyk
Bugs related to external docker images must be handled by respective 3rd parties.
@N3tFX, please open bug at[ linuxserver.io repo for papermerge docker image](https://github.com/linuxserver/docker-papermerge).

**Comment by romka-elvis** [comment]
Hello, @stoykovstoyk ! Can you describe, how you managed to setup the official docker image? I only could install the linuxserver.io edition. When I try to install the original image via portainer.io on my Synology DS218+, I get the error message about not supported version. Is there another way to install it? 

![grafik](https://user-images.githubusercontent.com/59457122/95657147-24865680-0b13-11eb-906b-0a8cd47ae022.png)

**Comment by stoykovstoyk** [comment]
I haven't used the docker image. I have installed it with the OS Specific instructions. You just have to follow the instructions and read carefully. I have done it and everything works fine.
