### ISSUE TITLE
Include tag management in automation

### ISSUE THREAD

**Issue by cr0** [ciur/papermerge#131]
Hi, great project.

I'd like to see tag management in the automation. From what I see, automation allows to move a file to a specific folder based on ocr content but does not allow to add a tag or two. 

At this point, maybe you could overhaul the automation process to support multiple conditions at once combined via and/or/xor and an extandable action set (add tags, move to folder, notifiy users, add metadata, run script, ...)

Keep up the good work.

**Comment by ciur** [comment]
> great project.

@cr0, thank you!

> I'd like to see tag management in the automation. 

That's exactly the plan for 1.5 release! When 1.5 will be ready (somewhere in October 2020) in automation form you will be able to assign tags as well.

> At this point, maybe you could overhaul the automation process to support multiple conditions at once combined via and/or/xor and an extandable action set (add tags, move to folder, notifiy users, add metadata, run script, ...)

The plan for 1.6 release is to somehow include in automations a thing similar [to this project](https://github.com/invoice-x/invoice2data) - where patterns matching/metadata to extract will be specified by [yml template, for example like this one](https://github.com/invoice-x/invoice2data/blob/master/TUTORIAL.rst), which users can upload themselves.

**Comment by ciur** [comment]
@cr0, tags are now part of automation. You can see the [demo here](https://www.youtube.com/watch?v=5adbHHmNcEw). In a week or so will be available as part of 1.5 release.

**Comment by cr0** [comment]
@ciur nice! looking forward to release 1.5 and in particular 1.6 ;-)
