### ISSUE TITLE
Feedback, Improvement suggestions

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#139]
I got this feedback from [here](https://github.com/ciur/papermerge/issues/135#issuecomment-699570384):

> I'm coming from [Paperwork](https://openpaper.work/) and while I'm still happy with it I wanted to look into similar project with multi user capability.
> 
> So here's a list with things which aren't ideal IMHO:
> 
> In contrast to Paperwork or Docspell this uses a folder base approach and is really bad at it:
>     
> - It's missing drag and drop or a context menu which adds five extra steps to every process. Automation helps here but you can't automate all of them in advance.
> - While cutting and moving pages also has the same problem it's nice to have it and I don't see another good way to do this. You don't see this feature that often.
> - Modal popup input fields don't get automatic text focus.
> - Having a multi user setup is pointless if only the superuser inbox is usable.
> - Fetching emails has to be a user setting.
> - Maybe watch subdirs for users?
> - Lack of feedback everywhere
>         1. Nothing happens when uploading finished.
>         2. Reloading the page and looking in the document is missing selectable text. Has processing failed or is it still on it? Do I have to retry? How do I let it process the document again? (It's possible to get some of the information in the log section but only if it was somewhat successful)
> - Scrolling documents to the bottom is a pain. The site has 4 (!) vertical and 3 horizontal scroll bars which activate one after another until you're finally at the bottom.
> - No fuzzy search. OCR often falsely recognizes characters or words or both and having a fuzzy search is crucial. A bit less than for Paperwork or Docspell because Papermerge uses folders but still important. (Search you demo for "Gesamtbetrag", which it indexed as "Gesantbetrag")
> - The right side menu (meta) is ugly compared to the other elements.
> - Automation based on pages will probably bite me later by ripping documents apart. Haven't tried that feature yet though.
> - Minor thing: No dark theme.
>

**Comment by maschhoff** [comment]
push!
