### ISSUE TITLE
Will not delete certain ocr'd files

### ISSUE THREAD

**Issue by fumunda** [ciur/papermerge#14]
Howdy again,

Seem to be having a strange issue. I take the container down nightly as I do a backup of all of my containers and when i bring it back up in the morning, a couple of the files that had been deleted the previous day are back.  The first time, i just thought it was me, but it has been 4 days now and those 2 files continue to appear daily.  They get deleted daily and then are back in the morning when i bring it back up. Its weird.  I am not a programmer or anything so let me know what you need to diagnose this.

OS: unRAID 6.8.3 (running docker-compose from the commandline)
PostGRES db container: default from your compose file
worker container version:  eugenci/papermerge-worker:latest
service container version: eugenci/papermerge:1.2.x (and yes it is "x")

Only changes i have made to your compose file are:
changed the line 'depends_on: - db' to 'links: - db:db' (wouldn't talk the other way for some reason)
service version 1.2.x 
added exposing ports for postgres (-p 5432:5432 which i had to do to get them to talk to one another for some reason), other than that it is what you wrote.

Also, no errors or anything in the logs. Just files reappearing.

Thanks for looking.

**Comment by ciur** [comment]
Well written a very clear report!
I will have a look at this issue over the weekend and come back with feedback.

**Comment by ciur** [comment]
I can't reproduce this issue. IMHO document deletion works pretty well.

**Comment by fumunda** [comment]
Alright. Must just be a strange side effect of the way i am running it.
I'll look into it more and see if i cant figure it out. Thanks!
