### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by habenkiros** [ciur/papermerge#140]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**
I will close automatically any bug related to linuxserver.io/papermerge docker image as I don't provide support for 3rd parties.

**Bug Description**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 20.04 LTS]
 - Papermerge Version [e.g. 1.4.3]

**Comment by ciur** [comment]
Hi @habenkiros, this is raw template for reporting issues, you need to change it with actual values.
