### ISSUE TITLE
"Check all" checkbox on logs page does nothing

### ISSUE THREAD

**Issue by okoetter** [ciur/papermerge#142]
**Bug Description**
On the logs page there is a checkbox on the left to "TIME" in the header of the table.
I expect this checkbox means "Check all". But for me it does nothing.

**Expected behavior**
When I check this checkbox and select "Delete selected logs" I expect all log entries to be deleted.

**Desktop (please complete the following information):**
 - OS: Docker image
 - Browser: Firefox 80.0.1
 - Papermerge 1.4.4

**Comment by ciur** [comment]
Hi @okoetter, thank you for reporting the issue!

Funny thing is that I fixed it (click checkbox -> select all issue) in master branch, but I  forgot to cherry-pick to stable/1.4.x branch :grin:

**Comment by ciur** [comment]
Hi @okoetter, I fixed the issue in [release 1.4.5.](https://github.com/ciur/papermerge/releases/tag/v1.4.5).

**Comment by ciur** [comment]
fix is in master branch (and thus will be available in 1.5.0 release in two weeks).
