### ISSUE TITLE
Change language - linuxserver container

### ISSUE THREAD

**Issue by guim31** [ciur/papermerge#144]
I just installed Papermerge via the linuxserver/papermerge container.

I see only English int the admin settings and in OCR as weel.

How should I do to make it work with french language ? I tried to add OCR_LANGUAGES (eng, fra) and OCR_DEFAULT_LANGUAGE (fra) in my docker variables with no effects.

Thanks for your work !

**Comment by ciur** [comment]
Hi @guim31, for official docker images, instructions [on how to change language are here.](https://papermerge.readthedocs.io/en/latest/setup/docker.html#configuration-changes-in-docker-container).

**Comment by guim31** [comment]
Thanks for your answer, but the thing is that I'm not a specialist with docker, and I use the linuxserver/papermerge container which I run like this : 

```
docker create \
  --name=papermerge \
  -e PUID=myid \
  -e PGID=groupid \
  -e TZ=Europe/Paris \
  -p 8000:8000 \
  -v /path/to/appdata/config:/config \
  -v /path/to/appdata/data:/data \
  --restart unless-stopped \
  linuxserver/papermerge
```

So I don't understand where I should add OCR_LANGUAGES and OCR_DEFAULT_LANGUAGE .. as there is only one container.
Are they just variables that I should add like this : 

```
docker create \
  --name=papermerge \
  -e PUID=myid \
  -e PGID=groupid \
  -e TZ=Europe/Paris \
  -p 8000:8000 \
  -v /path/to/appdata/config:/config \
  -v /path/to/appdata/data:/data \
  -v OCR_LANGUAGES:eng,fra \
  -v OCR_DEFAULT_LANGUAGE:fra \
  --restart unless-stopped \
  linuxserver/papermerge
```

Cause I already did that with no effects :-/

**Comment by ciur** [comment]
``-e XYZ=xyz`` is a way of passing environment variables and these lines:
```
  -e PUID=myid \
  -e PGID=groupid \
  -e TZ=Europe/Paris \
```
looks like the way linuxserver's guys configure application. From Papermerge application point of view both configuration variables``OCR_LANGUAGES`` and ``OCR_DEFAULT_LANGUAGE`` need to be placed in file named ``papermerge.conf.py``  which is supposed to be in **project directory**.

You need to open a ticket on [linuxserver's docker image for papermerge](https://github.com/linuxserver/docker-papermerge/issues) and ask them how are you supposed to configure application from within their image.

**Comment by guim31** [comment]
Thanks a lot for those explanations, I'll see what I can get from them !

**Comment by guim31** [comment]
Ok, so I just modified the papermerge.conf.py file in my appdata directory : everything worked fine ! 👍
