### ISSUE TITLE
Directory Navigation

### ISSUE THREAD

**Issue by AlexanderEDavis** [ciur/papermerge#150]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
When you go into a subfolder from root then click on the **name text** of the folder the app sends you up one directory.

**Expected**
Folder is selected or entered

**Actual**
What actually happens
User is sent to the parent directory

**Info:**
 - OS: [e.g. Windows 10, Ubuntu 20.04 LTS]
Windows 10 Business 2004
Chrome, Edge (new), Firefox
-  Database [SQLite, PostgreSQL 12.1]
Hosted with papermerge
 - Papermerge Version [e.g. 1.4.3]
1.4.4

**Comment by ciur** [comment]
Hi @AlexanderEDavis,

thank you for reporting the bug. I will fix it and make it available next week.

**Comment by ciur** [comment]
Hi @AlexanderEDavis,

[It was a simple fix.](https://github.com/ciur/papermerge-js/commit/a4f32841cfe4ef0e658d789583f6caf1f69f3589)
I closed this ticket by mistake (by referencing in git commit comment fixes #<ticket-number> github automatically closes the ticket). It would be correct to keep it open until you will confirm that ticket should be closed.
