### ISSUE TITLE
[Feature] XML documents

### ISSUE THREAD

**Issue by francescocarzaniga** [ciur/papermerge#161]
XML is sometimes used for invoices (e.g. Italy) or other static documents. It would be extremely useful (and a major selling point in places where such documents are mandatory) to be able to add them to Papermerge and view them in the Web UI using a stylesheet. Each document could be associated to a stylesheet either directly or automated per-folder or with a tag. Moreover no OCR is needed.
A user story could be setting up an autoforward for XML invoices to the Papermerge email, which would then process it, tag it, and associate a stylesheet for viewing, making the whole invoice intake incredibly smooth.

**Comment by ciur** [comment]
@francescocarzaniga, Papermerge is limited only for scanned documents. XML invoices are out of scope.

**Comment by francescocarzaniga** [comment]
@ciur It would be nice to have documentation on how to create plugins (you mention them in the README so I guess they are possible). This way people might choose to extend Papermerge's scope without interfering with the main concept.

**Comment by ciur** [comment]
@francescocarzaniga, my plans are to make Papermerge "plugin" oriented (plugin=apps).

> This way people might choose to extend Papermerge's scope without interfering with the main concept.

I absolutely agree!
