### ISSUE TITLE
Digest validation

### ISSUE THREAD

**Issue by francescocarzaniga** [ciur/papermerge#167]
I think that having a digest+user validation to prevent duplicate file upload is a good thing. When I have thousands or more documents I would like to avoid importing duplicates.

I understand this makes testing more difficult, but disabling validation in production because they are an inconvenience does not sound too good. There could at least be a setting for it, possibly per-user.

**Comment by ciur** [comment]
@francescocarzaniga, the master branch now contains papermerge.core.models.AbstractDocument model - you can use it to write your own (django based apps) plugins to add whatever additional validations you wish. 

See [pagelimit app](https://github.com/papermerge/limitpages) as example how to add additional document validations in external apps.
This is still experimental API, but it is already usable. [limitpages app](https://github.com/papermerge/limitpages) is used in [demo](https://www.papermerge.com/demo) to limit number of pages for uploaded docs.

You want to use [get_abspath](https://github.com/ciur/papermerge/blob/master/papermerge/core/models/document.py#L694) function to get access to the document's file.
