### ISSUE TITLE
Obsolete code

### ISSUE THREAD

**Issue by francescocarzaniga** [ciur/papermerge#168]
I have noticed that there is are quite a few lines of code and database fields that are obsolete. 
It would be a good idea to do a refactoring to also give charfields a more reasonable lengths, to have the least waste possible.

A concrete bug that stems from this is the requirement of MySQL with innodb_large_prefix on, since the digest field's length is > 255 and it is a unique value, without having any real need for such length.

**Comment by ciur** [comment]
@francescocarzaniga, I removed all obsolete fields from document model (speaking here about master branch).
Regarding digest validation, please [see my comment here](https://github.com/ciur/papermerge/issues/167#issuecomment-712609047) where I mention about external apps to add extra validations/fields.
