### ISSUE TITLE
Refactor of document importing

### ISSUE THREAD

**Issue by francescocarzaniga** [ciur/papermerge#169]
I am leaving a few issues at the same time, but this is just the things a noticed in the last couple of days and a reminder for me if I want to do some PRs.

Document importing is the major cornerstone of Papermerge, but right now the code is scattered in a few places and it does not support plugins at all. One solution would be to make an importer app and move the DocumentImporter class there. Then I propose there should be a split with a new class DocumentProcessor. As subclasses DocumentValidator would check mimetypes (using python-magic and not file extension) and count pages, while DocumentImporter does the actual importing itself. They could also be merged into DocumentProcessor. Then such a class could be used both in the upload view and other importers to do all the heavy lifting. This would allow to add custom pre- and post- processing on the documents and go a long way to provide more pluggability.

This is just a proposal, the spirit is to make document importing more unified and modular, so a number of solutions is possible.

**Comment by ciur** [comment]
@francescocarzaniga, description is too generic. Maybe you can be more specific.

**Comment by francescocarzaniga** [comment]
I guess this and #167 stem from the same problem, lack of plugin support. This issue is a suggestion to change the document importing system to be more modular and plugin-friendly. 
While I think this may not be urgent, the sooner you standardise a plugin system and document it the quicker people will get on board. If you truly want Papermerge to be plugin centric, then more people working on plugins => more features => bigger userbase.

**Comment by ciur** [comment]
>  lack of plugin support.

I am working on it ... :). In future Papermerge will be apps (app=plugin in django parlance) oriented.

**Comment by ciur** [comment]
@francescocarzaniga 
[Document Pipelines](https://github.com/papermerge/papermerge-core/blob/master/papermerge/core/import_pipeline.py) are now part of Papermerge.
