### ISSUE TITLE
Error when browsing to http://localhost:8000

### ISSUE THREAD

**Issue by bg1000** [ciur/papermerge#17]
Tried this on Ubuntu 20.04
Docker version 19.03.9, build 9d988398e7
docker-compose version 1.25.5, build 8a1c60f6
Setup using these instructions: https://papermerge.readthedocs.io/en/latest/installation/docker.html
Chose to pull from docker hub rather than build locally
The first error from `docker-compose logs app` is the following:

`Internal Server Error: /admin/login/
papermerge_service | Traceback (most recent call last):
papermerge_service |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
papermerge_service |     return self.cursor.execute(sql, params)
papermerge_service | psycopg2.errors.UndefinedTable: relation "django_site" does not exist
papermerge_service | LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
papermerge_service | 
`
http://localhost:8000 shows the following:

`Request Method: | GET
-- | --
http://192.168.1.2:8000/admin/login/?next=/admin/core/basetreenode/
3.0.2
ProgrammingError
relation "django_site" does not exist LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...                                                              ^
/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py in _execute, line 86
/usr/bin/python3
3.7.5
['/opt/papermerge',  '/opt/papermerge',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/usr/lib/python3/dist-packages']
Wed, 20 May 2020 13:41:13 +0000
`
                                                             ^

**Comment by bg1000** [comment]
Built this locally and it runs without error.
The docs show the command for this as `docker-compose up --build -f docker-compose-dev.yml -d`
This does not work, alteast with the version of docker-compose I am running.  This does work.
`docker-compose -f docker-compose-dev.yml up --build -d`

**Comment by ciur** [comment]
Thank you for reporting this issue. I will need to remove all my local images and try it again.

**Comment by bg1000** [comment]
No problem and thanks for sharing your work. I am going to close this now that you are aware.
