### ISSUE TITLE
Right click menu - feedback

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#170]
[Copied from redditer](https://www.reddit.com/r/selfhosted/comments/jb3jcl/papermerge_15_is_out_finally_with_tags/g8tkiz9?utm_source=share&utm_medium=web2x&context=3)

> Love the project, and it is my preferred dms for home use.
> 
> But I have one small request: I have not tried 1.5, but I think double click still is the way to open folders and documents. That makes it impossible (or at least a great hassle) to use touch screens. To be fair I have only tried Android browsers, but with no luck. A menu option to open selected document would be nice. Single click opening even better, but that is more a design choice I guess.

[and this one](https://www.reddit.com/r/selfhosted/comments/jb3jcl/papermerge_15_is_out_finally_with_tags/g8tp3lp?utm_source=share&utm_medium=web2x&context=3)

> 
> Single click to open would go hand in hand with adding a right click menu which would also help on touch screens (long press). Currently you have to single click to select one or more documents/folders and then choose an action from the toolbar above. It's a little tedious in its current form especially having to cut and paste documents rather than just "move to..." and choose a folder.
> 
> If a right click menu with those actions were added it would work the same as most other modern file storage solutions (e.g. onedrive/sharepoint/google drive). I think I saw this on the feature request list already so hopefully it gets attention.

**Comment by jtenniswood** [comment]
+1

**Comment by ciur** [comment]
[Double clicks open folder/document was replaced with single clicks.](https://github.com/ciur/papermerge/commit/ce0f929c877a9c8a04a7ff056f22999fdda3b43d)
Right click menu is already there.
Will be available since release 2.0.0
