### ISSUE TITLE
Sample config for caddy

### ISSUE THREAD

**Issue by ThisIsTenou** [ciur/papermerge#173]
Hey there,

I've created a sample config for use with caddy instead of nginx. I just love caddy.
Feel free to add it to the docs, if you're interested. The setup process is the same as with nginx, just without nginx. It's still using gunicorn.

```
my.domain.tld:80 {
  root * /opt/PapermergeDMS
  @notStatic not path /media* /static*
  reverse_proxy @notStatic 127.0.0.1:9001
  file_server
  encode zstd gzip
  log {
    level error
  }
}
```

**Comment by ciur** [comment]
oh, man, thank you! I didn't know about caddy web server. Really cool project! I will play with it lil bit.

**Comment by ThisIsTenou** [comment]
No problem! Caddy really is amazing. Fast and simple, with a huge amount of features.

This would be the config with custom ssl certificates:

```
my.domain.tld {
  root * /opt/PapermergeDMS
  @notStatic not path /media* /static*
  reverse_proxy @notStatic 127.0.0.1:9001
  file_server
  tls /path/to/certfile.crt /path/to/keyfile.key
  encode zstd gzip
  log {
    level error
  }
}
```

So yeah, as you can see, it's really that simple. If you have further questions, feel free to ask!
