### ISSUE TITLE
Merge PDFs

### ISSUE THREAD

**Issue by mikkelnl** [ciur/papermerge#184]
Could it be possible to merge two seperate PDF files into one?

**Comment by ciur** [comment]
@mikkelnl, this feature exists. You need to open a source document, select all pages, action -> cut, open destination document, action -> paste pages. All pages will be pasted at the end of destination document. As result, destination document will be "merge result" of the two.

**Comment by wklink** [comment]
I think the cut & paste option is far too much work if you're trying to merge multiple documents.  I'd be thrilled if I could just select a group of documents and select Action/Merge and put them all into a single document.
