### ISSUE TITLE
inbox folder is only selectable at automate creation

### ISSUE THREAD

**Issue by dani** [ciur/papermerge#185]
**Description**
When we create a new automate, we can select inbox as the destination folder. But if we edit an existing automate, inbox doesn't appear in the drop down

**Expected**
Automate creation and editing should be consistent, and inbox shoud always be selectable

**Info:**
 - OS: CentOS 7, manual install (no Docker)
 - Browser Chromium
-  Database Postgres 13
 - Papermerge Version 1.5.0

**Comment by ciur** [comment]
@dani, thank you for opening this bug!
