### ISSUE TITLE
Possibility to move doc to the "home" folder

### ISSUE THREAD

**Issue by dani** [ciur/papermerge#186]
When selecting the destination folder in an automate, we can only choose sub folders, there's no apparent way to simply move the doc out of the inbox to the top level "home" folder. This folder should be available as destination.

**Comment by ciur** [comment]
@dani, I am wondering how I did not notice this for such a long time!

**Comment by ciur** [comment]
This ticket is obsolete. First of all - automates are not there anymore. Secondly, version 3.0 feature dual panel which makes it very simple to move docs from one folder to another.
