### ISSUE TITLE
Nested folder & Metadata

### ISSUE THREAD

**Issue by CorneliousJD** [ciur/papermerge#191]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
If you have multiple levels of folders, such as Receipts/Retailers/Item Type/doc1.pdf, etc. and you set a "Price" metadata item on the Receipts top folder, it duplicates in the web UI all the way down, so by the time you get to the 3rd folder deep it's showing up 3 times in list voew.

**Expected**
Just one column for the metadata and that's it.

**Actual**
See screenshot - metadata is duplicated in 3 columns.
![image](https://user-images.githubusercontent.com/724777/97051235-d3cc2000-154c-11eb-9571-b9c6e149d41a.png)

**Info:**
 - OS: unRAID
 - Browser: Chrome
-  Database SQLite
 - Papermerge Version 1.5.0

**Comment by ciur** [comment]
@CorneliousJD, oh, man, really good catch! Thank you for opening this bug. Very well described as well :) thank you!
