### ISSUE TITLE
Multi language OCR by default or by choice per document

### ISSUE THREAD

**Issue by maspiter** [ciur/papermerge#193]
For storing documents in multiple languages, it would be nice to have the option to select other installed languages as extra tesseract default language with a checkbox.

As an alternative, make it possible to re-OCR specific documents in a language other than the default.

**Comment by ciur** [comment]
Feature is available in 3.0 version. Current stable release is 3.0.1. 
![OCR-in-another-language](https://github.com/ciur/papermerge/assets/24827601/a38fd0ef-6311-4703-bfb8-fcf6c7acf623)
