### ISSUE TITLE
confusing phrase in readme.md

### ISSUE THREAD

**Issue by bish0polis** [ciur/papermerge#2]
>  By config/settings/development.py is ignored

This sentence may need a quick look-over:  I can't parse out its meaning.  I suspect it should be 

> By config, settings/development.py is ignored

.. and I'd love to just make that trivial change, but I'm not sure that's the intent.

**Comment by ciur** [comment]
man, thanks a lot for opening an issue, I appreciate it!

I wanted basically to say that file is listed in .gitignore and will be ignored by git. [It's corrected now](https://github.com/ciur/papermerge/commit/940a16ea7c469387fb4377c9e946f53dfdec9231).
Note that Readme.md gives you only high level explanation; detailed instructions [are here ](https://papermerge.readthedocs.io/en/latest/installation/manual_way.html).
