### ISSUE TITLE
Manually Fire Automations

### ISSUE THREAD

**Issue by errolsancaktar** [ciur/papermerge#201]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to run automations on documents that are already in the inbox.  When building automations, having documents to work from will make it much easier to develop them.

**Describe the solution you'd like**
under actions in the inbox page allow selected documents to be run through the automation engine.

**Describe alternatives you've considered**
only thing i can see is to delete and reupload

**Additional context**

**Comment by ciur** [comment]
@errolsancaktar, good point! 
Manual re-run on Automations goes hand in hand with manual re-run of OCR operations.
I will take care of this issue. Thank for taking you time and opening this ticket!

**Comment by errolsancaktar** [comment]
Do you happen to have any idea on timeline? Also need help?

**Comment by webac** [comment]
Hi @ciur ,
I just start testing and using Papermerge at home, this should be a good enhancement,
Because I generally send some documents to inbox before creating the automate.
Thank you

**Comment by ciur** [comment]
I just added "re-run automation" feature.
Will be available in couple of weeks as part of Papermerge 2.0.
