### ISSUE TITLE
Automates created for all users

### ISSUE THREAD

**Issue by jorisvc** [ciur/papermerge#202]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
When having multiple users in Papermerge, a new automate is created for all users.

**Expected**
Have seperated automates for each user.
That users can't see each others automates.

**Actual**
User1 creates a new automate. User2 can see the new automate created by user1.
The automate created by user1 doesn't work for user2 because the destination folder doesn't exist for user2.

**Info:**
 - OS: Debian 10
 - Browser: Google Chrome
-  Database SQLite
 - Papermerge Version 1.5.0]

**Comment by ciur** [comment]
@jorisvc, oh, man, that is a bad one :(
Automates are per user :(
I will fix it, thank you @jorisvc, for heads up!

**Comment by ciur** [comment]
Fix is available in version 2.0.
