### ISSUE TITLE
 I want to know how to put tag

### ISSUE THREAD

**Issue by mrtortong** [ciur/papermerge#207]
Hi,
 I want to know how to put tags.
![Screenshot from 2020-11-14 22-09-32](https://user-images.githubusercontent.com/21356923/99150307-186b5700-26c6-11eb-8f48-7c92f597e085.png)

Thank in advance.

**Comment by ciur** [comment]
@mrtortong  - you don't add tags in "Tags" navigation menu.
To add a tag:
1. go to document
2. select what document you want to tag (by clicking once)
3. actions menu (that one with lighting on it) select "tag"

You can see adding tags "in action" in [this video.](https://www.youtube.com/watch?v=bshUowL57t8)

**Comment by mrtortong** [comment]
@ciur Thanks for helping.
