### ISSUE TITLE
Add ability to rotate document

### ISSUE THREAD

**Issue by rf152** [ciur/papermerge#209]
**Is your feature request related to a problem? Please describe.**
I have some documents that are landscape rather than portrait. It would be nice to be able to rotate these so I don't have to rotate either my head or the screen :)

**Describe the solution you'd like**
Ability to rotate pages within a document, or a document as a whole.

**Describe alternatives you've considered**
Continue as I am at the moment.

**Additional context**
None that I can think of....

**Comment by ciur** [comment]
@rf152, makes perfect sense. I will add this feature. Thank you for opening a feature request!

**Comment by RavetcoFX** [comment]
Any update on the progress of this?

**Comment by browntownington** [comment]
+1 this feature request. 

For two reasons
1) As OP says some documents contain both portrait and landscape pages. e.g my share holding statements or anything that has full page tables usually.
2) Sometimes the documentations scan upside down and the OCR engine doesn't flip them correct. It would be nice to be able to flip them within Papermerge and re-initiate OCR on the correctly rotated pages.

**Comment by ciur** [comment]
This feature will be part of 2.1

**Comment by ciur** [comment]
Feature [was implemented](https://docs.papermerge.io/User%27s%20Manual/page_management.html#rotate).
It is available in latest [2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35).
Please note that after rotation you need to trigger (manually) OCR again.
