### ISSUE TITLE
Alternative to folder structure

### ISSUE THREAD

**Issue by duracell** [ciur/papermerge#21]
Hey, I just found papermerge and it seems very nice, the only thing which stops me from using is the folder system. I really love to use tags in many applications, so I would love to use tags to categorize my documents. Do maybe could implement such a feature in the future? Because with folders you're very limited to sort files.

**Comment by ciur** [comment]
Tags per folder/document (even per page) is a planned feature. However, it will be not sooner than 1.5.
1.3 is (current work in progress) in concerned with metadata.
1.4 UI changes - papermerge will [use Admin LTE UI](https://adminlte.io/themes/AdminLTE/index2.html)

**Comment by ciur** [comment]
Hmm, tags are important indeed!
I will definitely add them in version 1.5

**Comment by darookee** [comment]
It would be nice if tags could be added and updated on documents via the REST API, as well as searching/filtering the `/api/documents` by them.

**Comment by ciur** [comment]
It makes sense. REST API is an important feature.
I will open a new ticket (feature request) regarding for REST + tags management specifically. It will help me manage tickets easier.

**Comment by ciur** [comment]
Tag management is now in master branch and it works pretty smooth.
