### ISSUE TITLE
How i use pgAdmin4 for database management.

### ISSUE THREAD

**Issue by mrtortong** [ciur/papermerge#211]
Hi Ciur
       How i use pgAdmin4 for database management? I try but it error. I run by docker-compose for papermerge.
![Screenshot from 2020-11-15 13-37-41](https://user-images.githubusercontent.com/21356923/99178628-c5d27f00-2747-11eb-9d53-a585adbaed5d.png)

Thank you very much.
Apichat

**Comment by ciur** [comment]
Please use pgAdmin4 specific resource for questions regarding pgAdmin usage.

**Comment by mohammed-Emad** [comment]
- It should be added to the Postgres network
In other words, both of them must be within a single network
You can find out which networks have been set up inside the docker by means of the command
``` sudo docker network ls ```

- But to solve the problem, continue the following stages

First, review the names of the containers
```bach
sudo docker ps -a
```
Search for the name for Postgres 
like ``` postgres_db ```
Then run the following query
``` sudo docker inspect postgres_db ```

and Find the IP address and the network name. You will find them in the following figure
like that:
```
 "NetworkMode": "docker_default",
```
and
``` 
"IPAddress": "172.18.0.5",
```

Next we'll run Pgadmin by merging the network name we found
```
docker run -p 80:80 \
    -e PGADMIN_DEFAULT_EMAIL="admin@gmail.com" \
    -e PGADMIN_DEFAULT_PASSWORD="admin" \
	--network="docker_default" \
    -d dpage/pgadmin4
```

Note!
1- ```dpage/pgadmin4``` Is the name of my container
--Make sure to use your container name along with your mail address and password as well

--
goto pgadmin in browser

set port and ip-address to new server

![Screenshot_588](https://user-images.githubusercontent.com/23532295/114639301-c0189f80-9ccd-11eb-8ace-d1450439d1c6.png)

Good luck🙂
