### ISSUE TITLE
Search does not working 

### ISSUE THREAD

**Issue by spegroup** [ciur/papermerge#213]
**Description**
I installed v1.5.0 because of the fixed API upload bug. Now the API works well but searches are not matching in WebUI. The uploaded Docs will be OCRed and TXT files are visible after teseract is finished.

**Expected**
Matching search keywords in WebUI Search.

**Comment by ciur** [comment]
@spegroup 
Can you please be more specific ? What exactly doesn't match ?

**Comment by spegroup** [comment]
Search doesn't find any keyword over the webui which is recognized via OCR in PDFs (correct shown in the corresponding TXT files). It is working in 1.4 but not in 1.5.

**Comment by francescocarzaniga** [comment]
For what it's worth the search is not broken for me. Could you provide a bit more information @spegroup?

**Comment by spegroup** [comment]
Thx for your time. I reinstalled it from scratch and it works now.
