### ISSUE TITLE
Move To action - in addition to cut/paste

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#214]
In freshly included right click menu, add ``move to`` item. It will speed moving of documents around. Same for document view i.e. pages moving between documents.

Got this suggestion from here #82 

Here is full quote:

> Have you considered a Move to action?
> 
>     Select items
>     click Move To
>     pops up a folder browser allowing you to select the destination
> 
> Feels a bit more intuitive to me, especially if you are filing a large number of things from the inbox.
> Drag and drop is less useful when you have multiple levels of folders.

**Comment by okoetter** [comment]
What about drag and drop, if pinned folders (see #266) is implemented?

**Comment by ciur** [comment]
This feature is now implemented in 2.1.0b1. When in dual panel mode, folders/pages can be moved/extracted between panels.
Moving/Extracting can be triggered from context menu.
