### ISSUE TITLE
NoReverseMatch at /admin/core/user/add/

### ISSUE THREAD

**Issue by lagosr-github** [ciur/papermerge#22]
Crash while trying to add a user

brand new installation using docker compose files.

![NoReverseMatch at  admin core user add ](https://user-images.githubusercontent.com/3108304/84402049-d5f29b00-abb8-11ea-95f6-cd2e9d5c46cf.png)

docker compose used:

version: '3.7'
services:
  app:
    image: eugenci/papermerge:1.2.2
    command: python3 /opt/papermerge/manage.py runserver 0.0.0.0:8000
    ports:
      - "8888:8000"
    depends_on:
      - db
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/broker/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.stage
    deploy:
      placement:
        constraints:
          - node.labels.arch == amd64
          - node.role == worker
        
  db:
    image: postgres:11.7
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
    deploy:
      placement:
        constraints:
          - node.labels.arch == amd64
          - node.role == worker

  worker:
    image: eugenci/papermerge-worker:1.2.x
    command: bash -c "cd /opt/papermerge-worker && celery worker -A pmworker.celery -Q papermerge -l info"
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/broker/queue
    environment:
      - CELERY_CONFIG_MODULE=config
      - C_FORCE_ROOT=True
    deploy:
      placement:
        constraints:
          - node.labels.arch == amd64
          - node.role == worker

volumes:
  postgres_data:
  broker_queue:
  media_root:

**Comment by ciur** [comment]
Ooops! First real bug. 
Thank you for opening the issue, I will take care of it!

**Comment by ciur** [comment]
Will be fixed as part of 1.4.0 release

**Comment by ciur** [comment]
Fixed in release 1.4.0; release will be available on 1st of August 2020.
