### ISSUE TITLE
Importer - 'DefaultPipeline' object has no attribute 'temppath'

### ISSUE THREAD

**Issue by dgz** [ciur/papermerge#229]
**Description**
Upon discovering a new scanned pdf in the import directory, the worker throws the error below and does not import the file (does not appear in inbox). However, the file is deleted from the import folder as though it were successfully processed.

[2020-11-28 02:52:16,052: ERROR/ForkPoolWorker-2] LOCAL importer: 'DefaultPipeline' object has no attribute 'temppath'

**Expected**
The file is successfully imported or the file is at least left in the import directory to be tried again on the next loop (basically, don't eat my files if things break).

**Info:**
 - OS: Ubuntu 20.04 LTS
-  Database: SQLite
 - Papermerge Version: git master 69592d4 (I like to live on the edge)

**Comment by ciur** [comment]
@dgz, thank you for heads up! Pipelines feature is couple of days new addition to master branch ;)
