### ISSUE TITLE
Fundraising, Donations, Help

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#231]
Hi fellows,

I open sourced Papermerge project in February 2020. Since then, I work daily on it and I am very happy to see its userbase growing every single day! So many people use it, provide great feedback, help with code! I received countless number of emails with positive feedback, words of encouragement and features requests.

Thank you all for your fantastic support! :tada:

However, the less bright side of open source projects, especially in their initial phase is the financial part.
All projects struggle at the beginning to survive, Papermerge is no exception :cry:.

### Donations

In case you find Papermerge useful, I humbly ask you to support Papermerge via a small donation.
Even an amount as small as $9 will make a huge difference.

For donations, you can use thee channels paypal, patreon and github itself:

[Donate via Paypal](https://www.paypal.com/paypalme/eugenciur)
[Sponsor via Github](https://github.com/sponsors/ciur)
[Become a Patreon](https://www.patreon.com/papermerge)

### What you will get in return?

In return, you will benefit from free, open and well documented management system (DMS).
In return, Papermerge will transform your paper work into a pleasant experience - for free!
In return, you will have high quality, easy to use and truly open DMS.

:green_heart: :green_heart:  :green_heart: 

### Natural Growth

**It takes time, perseverance and genuine work to create great products.**
  
A common practice nowadays is to register a small startup company, develop a minimal viable product and immediately start looking for venture capital (VC) investors. While this approach in general makes perfect sense, in case of many software projects I find it very inappropriate, even harmful. In general, VC investors focus on grow fast and immediate return of investment (ROI). "Grow fast" approach coupled with lack of managerial experience of project leaders usually yields disastrous outcome, which many times translates into poor service quality.

I strongly oppose to any hyper acceleration be it in form of investment capital, human staff or childish haste. As Papermerge project manager, my values directly translate into Papermerge project values. This biological growth is not really what business people and investors are fond of exactly because of core nature of slow, gradual advancement. However, I firmly believe that natural growth approach, in long term leads in stable, solid and high quality product. 

If you value natural grow, high quality and transparency I gently ask you to support Papermerge even with a small donation.
Your donation, even small one, is like a drop of water - it is a valuable source of life for Papermerge. Your donation keeps away venture capital. Your donation secures the future of naturally grown product.

Thank you all for your kind support!

**Comment by dgalli1** [comment]
Can't donate via paypal, it seems like your account limit is reached

**Comment by ciur** [comment]
@dgalli1, indeed, there was a problem with my paypal account (My address was incomplete) which placed a limit on the account.
I fixed that.
Thank you a lot for your quick heads up!
