### ISSUE TITLE
apply_async never completes task

### ISSUE THREAD

**Issue by francescocarzaniga** [ciur/papermerge#234]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
On my computer ocr_page.apply_async doesn't work (normal apply without async works fine). This means that pdf uploaded from the web page are never OCR'ed, while the ones ingested by imap/local are fine. Everything works fine with with redis.

This problem is not caused by pipelines, since I reverted views/documents.py to a pre-pipeline version and this behaviour is still there.

Could you please try it as well @ciur? Maybe you know what is causing this.

**Expected**
PDF uploaded by web view are OCR'ed.

**Actual**
They aren't.

**Info:**
 - OS: Ubuntu 20.04
 - Browser: Chrome
-  Database: SQLite
 - Papermerge Version: master

**Comment by ciur** [comment]
> On my computer ocr_page.apply_async doesn't work

well, on my computer is works :)

**Comment by ciur** [comment]
Ticket was closed because information provided is too generic and maybe outdated. It is just impossible to recreate fully correct context of the problem (in case there is a problem at all).
