### ISSUE TITLE
Automating token generation for the rest api?

### ISSUE THREAD

**Issue by droidroy-ai** [ciur/papermerge#238]
Hello @ciur ,

I wanted to ask if there is any way of generating the token without the use of the front end UI of papermerge. I want to use papermerge REST API in my system and I really wanted to know if token generation is possible without the hassle of accessing the webpage of papermerge. 

Thank you.

**Comment by ciur** [comment]
no, there is nothing like that.
What would be the use case of automatic token generation?

**Comment by droidroy-ai** [comment]
Hello @ciur , 
Sorry for such a late reply. 
I only want to use papermerge for it's REST API capabilities and getting the token from something like oauth or anything would have been great. My system wants to integrate papermerge as its DMS but I don't want my users to go and create API tokens and all.

**Comment by ciur** [comment]
I see. At this moment there is no such feature. I will add oauth integration starting with 2.1 (aprox march 2021)
