### ISSUE TITLE
Adjusting size of sign-in button

### ISSUE THREAD

**Issue by l4rm4nd** [ciur/papermerge#239]
Just noticed that the sign in button of Papermerge is too small for the language German.
![grafik](https://user-images.githubusercontent.com/21357789/100945221-13e5d180-3501-11eb-82a4-114a274cbee5.png)

Can be easily fixed by increasing the column size in `papermerge/contrib/admin/templates/account/login.html` from `class="col-4"` to `class="col-4.5"`.

![grafik](https://user-images.githubusercontent.com/21357789/100945278-337cfa00-3501-11eb-91c5-3c17a374b6ae.png)

![grafik](https://user-images.githubusercontent.com/21357789/100945290-3b3c9e80-3501-11eb-9dd5-89a25e0496de.png)

**Comment by ciur** [comment]
@l4rm4nd, danke für den Issue!
