### ISSUE TITLE
Merge jpeg documents

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#240]
grabbed from a comment on reddit:

> I know, i am a bit late to the party, but i just installed papermerge and from all the alternatives i tried yet, it seems the most easy to use.
> 
> But i am missing ONE feature, that is missing in all the other tools as well (and which baffles me a but, because to me it seems so obvious).
> 
> Merge multiple picture files (scanned pages) to one document.
> 
> i have a flatbed scanner which does not have any clue about where one document starts and another ends or vice versa, so all it does is take the scan page by page and put it somewhere (currently a smb share, but i will change my script to upload it to papermerge if that works).
> 
> Now i have lets say 4 pages jpg that are one document.
> 
> I'd like to:
> 
>     treat those 4 pictures as 1 Document
> 
>     download them as 1 joined PDF
> 
> Is something like that planned ?

**Comment by ciur** [comment]
and my reply (on reddit) was:

> Author here.
> 
> Something like this is the core feature of Papermerge: jpeg images are treated as documents thus you should be able to merge them into one document (pdf).
> 
> However, because of a bug, this is not possible to do right now. I fill fix this bug as part of next major release (2.0) which will be in January 2020.
> 
> My scanner also optionally can save scans saved as jpeg - thus I had same issue.

**Comment by Raven24** [comment]
Would this mean something like selecting multiple "one-page" documents and getting an option at the top-level to merge them? Because from what I see, this is currently only possible by going into the documents one after another and cut&paste the pages by switching around from source to target document - which is quite inconvenient...

**Comment by ciur** [comment]
This feature is available in version 3.0 - you can merge jpeg documents.
