### ISSUE TITLE
Automates Screen max items

### ISSUE THREAD

**Issue by martincw2** [ciur/papermerge#243]
**Description**
If there are more than 25 automate actions defined, the screen displays the first 25 with no scrollbar or page breadcrumbs.

**Expected**
Provide a mechanism to access remaining automate actions

**Actual**
Can only view or access the first 25 items.

**Info:**
 - OS: Ubuntu
 - Browser Vivaldi, Edge
 - Papermerge Version  1.5.3

I was able to reproduce this issue with the LiveDemo as well.  I created 26 dummy Automate actions - https://demo.papermerge.com/admin/automates/

**Comment by ciur** [comment]
@martincw2, thank you for reporting the issue!
I forgot to add pagination for automation. I will be fixed in 1.5.4.

**Comment by ciur** [comment]
Fix is now available in master and stable/1.5.x branches
