### ISSUE TITLE
Have all configs in one place or read from admin-made drop-in config files

### ISSUE THREAD

**Issue by amo13** [ciur/papermerge#245]
**Is your feature request related to a problem? Please describe.**
I set up redis as a message broker and the configuration for this is in base.py. Upon updates, this files gets overwritten by the updated file, which is good from the update point on view, but inconvenient from the config point of view.

**Describe the solution you'd like**
Move the configuration part for redis (and maybe other potentially relevant configurations) from base.py to papermerge.conf.py, which does not get overwritten. Another idea would be to have a folder from which drop-in configuration files are read, maybe with lower precedence than the main config file papermerge.conf.py.

**Comment by ciur** [comment]
@amo13, this is now how it works.
In base.py only general purpose configuration goes. Think of base.py as a place which  gathers all config from other, more specific places.
Those "specific" places are two:
- django settings file, which is usually named either production.py, or dev.py or test.py depending on the context. That django configuration is the file you are looking for.
- papermerge.conf.py which is more user friendly config.

Configuration are assembled in this order base.py which takes them from production.py (or dev.py or whatever DJANGO_SETTINGS_MODULE points to) AND from papermerge.conf.py.

Here is [more info](https://www.papermerge.com/docs/Installation/settings.html#papermerge-prefix) on the topic.
