### ISSUE TITLE
Offer auto completion for tagging

### ISSUE THREAD

**Issue by wechsler42** [ciur/papermerge#249]
**Is your feature request related to a problem? Please describe.**
Tagging of documents and directories works actually without auto completion in the tag editor. So there are no suggestions derived from already existing tags.

**Describe the solution you'd like**
I suggest to offer an auto completion feature for tags in tag editor. The tag suggestions should be derived from the set of already existing tags. In order to speed up tagging, the auto completion suggestions should be case insensitive.

**Comment by ciur** [comment]
>  tags ... should be derived

``derived``, but how?

I assume you have in mind some sort of AI, which is out of scope at this stage of the project.

Besides, there is already an auto completion:
(for some reason screenshot does not render the "drop down options", but after I press "i" letter, the "drop down options" will offer me ``important`` and ``invoice`` tags for selection)
![Screenshot from 2020-12-08 19-52-15](https://user-images.githubusercontent.com/24827601/101527976-fc8a6680-398e-11eb-87b2-b0a1d244d363.png)

**Comment by wechsler42** [comment]
Thanks for the reply. I restarted my Browser and Voila, auto completion for tagging is there as you described it. Sorry, that must have been a malfunction somewhere in my Browser or the Browser plugins  - my bad!
