### ISSUE TITLE
Apache 2 wsgi application ignore papermerge.conf.py

### ISSUE THREAD

**Issue by celi28** [ciur/papermerge#254]
**Description**
On Ubuntu 20.04.1 LTS, apache2 wsgi mod application seem to ignore papermerge.conf.py

**Expected**
Expected to serve app. as ./manage.py runserver 0.0.0.0:80 does

**Actual**
Serve papermerge app. like it was no papermerge.conf.py file. Serving with default configuration

**Info:**
 - OS: Ubuntu 20.04.1 LTS
-  Database SQLite
 - Papermerge Version : v1.5.3

**Configs:**

/etc/apache2/sites-enabled/papermerge.conf
```
<VirtualHost *:80>
    <Directory /opt/papermerge/config>
        Require all granted
    </Directory>

    Alias /media/ /var/media/papermerge/
    Alias /static/ /opt/papermerge/static/

    <Directory /var/media/papermerge>
       Require all granted
    </Directory>

    <Directory /opt/papermerge/static>
      Require all granted
    </Directory>

    ServerName papermerge.home
    ServerRoot /opt/papermerge
</VirtualHost>

WSGIPythonHome /opt/papermerge/.venv/
WSGIPythonPath /opt/papermerge/
WSGIScriptAlias / /opt/papermerge/config/wsgi.py
```

/opt/papermerge/config/wsgi.py
```
import os
from django.core.wsgi import get_wsgi_application
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")
application = get_wsgi_application()
```

/opt/papermerge/papermerge.conf.py
```
OCR_LANGUAGES = {
    'fra': 'Français',
    'eng': 'English'
}

OCR_DEFAULT_LANGUAGE = "fra"
```

**Comment by wedganw** [comment]
Copying the papermerge.conf.py from the project directory to /etc/papermerge.conf.py worked for me.
Didn't testet it but I think it has something to do with how the "DEFAULT_CONFIG_PLACES" is implemented in /opt/papermerge/config/settings/base.py.

`DEFAULT_CONFIG_PLACES = [
    "/etc/papermerge.conf.py",
    "papermerge.conf.py"
]`

**Comment by ciur** [comment]
@celi28 I think @wedganw's comment should solve your issue. Can you please try it?

**Comment by ciur** [comment]
response time out :)
