### ISSUE TITLE
docker-compose sample doesn't set-up fully

### ISSUE THREAD

**Issue by AlexKnowsIt** [ciur/papermerge#261]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
I tried the last days to setup papermerge using docker, but I am having problems with the official image. If I am using the docker image from linuxserver.io I can get the app running without any problems. If I use the example-file version 1.4 from this repository it seems that the the app is not listening on port 8000. This is the output from the command line while setting up:
`Migrations for 'core':`

`
  papermerge/core/migrations/0035_auto_20201220_1021.py`

`    - Alter field first_name on user`

`Operations to perform:`
  `Apply all migrations: account, admin, auth, contenttypes, core, dynamic_preferences, dynamic_preferences_users, knox, sessions, sites, socialaccount`
`Running migrations:`
`  No migrations to apply.`
`Unknown command: 'drop_triggers'`
`Type 'manage.py help' for usage.`
`System check identified no issues (0 silenced).`
`[2020-12-20 10:22:00,969: INFO/MainProcess] Connected to filesystem://localhost//`
`[2020-12-20 10:22:01,001: INFO/MainProcess] celery@localhost ready.`
`[2020-12-20 10:22:04,009: INFO/Beat] beat: Starting...`
`[2020-12-20 10:23:08,094: INFO/Beat] Scheduler: Sending due task txt2db (papermerge.core.management.commands.worker.txt2db)`
`[2020-12-20 10:23:08,152: INFO/MainProcess] Received task: papermerge.core.management.commands.worker.txt2db[0fe25b8d-161a-4a70-b1c1-e78a076e2ac1]  `
`[2020-12-20 10:23:08,156: DEBUG/ForkPoolWorker-2] Celery beat: txt2db`
`[2020-12-20 10:23:08,157: INFO/MainProcess] Received task: papermerge.core.management.commands.worker.txt2db[b1aa02c5-8826-4ce2-9660-05cd2195494d]  `
`[2020-12-20 10:23:08,200: INFO/ForkPoolWorker-2] Task papermerge.core.management.commands.worker.txt2db[0fe25b8d-161a-4a70-b1c1-e78a076e2ac1] succeeded in 0.04409075299918186s: None`
`[2020-12-20 10:23:08,202: DEBUG/ForkPoolWorker-2] Celery beat: txt2db`
`[2020-12-20 10:23:08,213: INFO/ForkPoolWorker-2] Task papermerge.core.management.commands.worker.txt2db[b1aa02c5-8826-4ce2-9660-05cd2195494d] succeeded in 0.01100099399627652s: None`

**What happens**
If I am trying to open the web-interface I get a `server not found` message and there are no indications in the logs, that the request got blocked. It seems like the request is not getting to the server at all.

**Info:**
 - OS: Ubuntu 20.04 LTS

**Comment by jkuettner** [comment]
I think this is because (probably by mistake) the docker image [eugenci/papermerge:1.5.3](https://hub.docker.com/layers/eugenci/papermerge/1.5.3/images/sha256-d77a5dd245ce454edb6223a79d69547546b690353fa1c222f1b4e2e4e9e7f1f1?context=explore) was overwritten with the one from [eugenci/papermerge-worker:1.5.3](https://hub.docker.com/layers/eugenci/papermerge-worker/1.5.3/images/sha256-d77a5dd245ce454edb6223a79d69547546b690353fa1c222f1b4e2e4e9e7f1f1?context=explore).

The images have the same digest

**Comment by ciur** [comment]
@jkuettner, @AlexKnowsIt, right, my mistake :(. Thanks for heads up!
I will fix the issue next week (as part of release 1.5.4).

**Comment by ciur** [comment]
Release 1.5.4 is out.
