### ISSUE TITLE
Issues with the project when using docker

### ISSUE THREAD

**Issue by oussama-he** [ciur/papermerge#269]
I have recently cloned this repo and I'm trying to run the project and do some modifications, but I'm facing some issues.

Among these issues, I get two different interfaces after login. To clarify, when I'm using docker to run this project I get this interface after login:

![h-docker](https://user-images.githubusercontent.com/18425315/103021849-245efa00-454b-11eb-918b-d39fc17e20f9.png)

And this interface when running the project after install dependencies [manually](https://papermerge.readthedocs.io/en/latest/setup/manual_way.html#manual-way-bare-metal).

![h-run](https://user-images.githubusercontent.com/18425315/103021861-2a54db00-454b-11eb-9352-080017c1cb33.png)

Also, I can't see the modifications that I made when running the project using docker.

Can anyone tell me what is the problem and how can I fix it, please?

Thank you in advance.

**Comment by ciur** [comment]
Hi @oussama-he, when running docker images with ```cd docker/1.4; docker-compose up`` you run latest stable version 1.5.4.

While when running project manually you run the main branch i.e. development mode.
Development mode i.e. git master branch is the very latest version  (i.e. work in progress) and it is not suitable for production.

**Comment by oussama-he** [comment]
Thank you for your clarification, but I can't see my modifications when running the project using docker. 
Also, I have an issue when using `docker-compose run app django-admin compilemessages -l ar`, it doesn't compile the file.

**Comment by ciur** [comment]
Docker image is not provided for development purposes. Docker compose will run code from same commit (which is tagged as latest stable).
If you want to dockerize you own changes, you need to make changes outside docker, and when you are done with changes, you need to create you own image.
