### ISSUE TITLE
Can't add notes to a document

### ISSUE THREAD

**Issue by N1c093** [ciur/papermerge#27]
Currently it's not possible to add a note to a document.
When I hit the button "save" the error message appears.

![image](https://user-images.githubusercontent.com/59510296/85840113-39292380-b79c-11ea-87ba-be6ae7d48707.png)

**Comment by ciur** [comment]
This is a serious issue. 
I will try to provide a fix for this problem (+ [to this one](https://github.com/ciur/papermerge/issues/26)) over this weekend.
Thank you again for your time!

**Comment by ciur** [comment]
Fix is now available in v1.2.3. You basically need to: 
```
$ cd papermerge-proj/docker
$ docker-compose up -d
```
again. Docker compose will pull version v1.2.3 which includes above fix.
