### ISSUE TITLE
Multiarch Docker build

### ISSUE THREAD

**Issue by williwehrlos** [ciur/papermerge#274]
**Is your feature request related to a problem? Please describe.**
currently the original docker build is only compatible with amd64

**Describe the solution you'd like**
Please make the docker built multi arch so it can run on arm socs (pi, nas, etc)

**Describe alternatives you've considered**
Installing papermerge manually. It works but docker these days is more convenient

**Comment by ciur** [comment]
Providing docker images various arch is out of scope.
