### ISSUE TITLE
Docker papermerge-worker latest is not the newest version

### ISSUE THREAD

**Issue by w4tzmann** [ciur/papermerge#276]
I updated my docker-compose.yml to use always the newst vailable image for papermerge. So I used:
```services:
  app:
    image: eugenci/papermerge:latest
  worker:
    image: eugenci/papermerge-worker:latest
```
The app runs fine with the Version 1.5.5.
But the worker won't run:
> papermerge_worker   /bin/bash                       Exit 0

Using the worker image with tag 1.5.5 works without problems:
> papermerge_worker   /opt/app/startup.sh             Up

After looking at the images, I saw, that the image with the tag latest hasn't been updated since 7 months.

> eugenci/papermerge              latest              98d892b54ee8        19 hours ago        1.03GB
> eugenci/papermerge-worker       1.5.5               dbf175a92f3a        19 hours ago        1.05GB
> eugenci/papermerge              <none>              1dfd3ce4eecf        5 days ago          1.03GB
> eugenci/papermerge-worker       1.5.4               80c6fc99bece        5 days ago          1.05GB
> eugenci/papermerge              1.5.4               9a6a7097f355        5 days ago          1.04GB
> eugenci/papermerge-worker       latest              d985bc8c87f7        7 months ago        682MB

I'm not sure if these has an special reason, if so then sorry for opening the issue. If not can you please update the latest tag like you do with the papermerge image?

**Comment by ciur** [comment]
@w4tzmann 

> I'm not sure if these has an special reason

There is no special reason. That "latest" image was actually the very first image I pushed  while I was still learning/experimenting with docker.

> can you please update the latest tag like you do with the papermerge image?

Sure! It is actually a very good thing to have "latest" tag  point to the latest image. I will make the change tomorrow by EOD.

**Comment by ciur** [comment]
@w4tzmann, I updated docker hub.
Now eugenci/papermerge:1.5.5 point to the same as eugenci/papermerge:latest.
Similarly eugenci/papermerge-worker:1.5.5  point to the same image as  eugenci/papermerge-worker:latest.
And 1.5.5 is latest stable indeed :)

**Comment by w4tzmann** [comment]
thanks, it's working!
