### ISSUE TITLE
Docker Installation

### ISSUE THREAD

**Issue by dgalli1** [ciur/papermerge#277]
**Description**
I tried to setup a clean installation from the provide docker-compose file in the folder docker/1.4/
First off it started to build the image locally which doesn't match the description in readthedocs.
So i commented out the build directives in the file.

So the containers all started after changing this and they are now all in version 1.5.5
But their seems to be another issue.
1. OCR doesn't work -> Tesseract not installed warning in App container
2. DB Migrations seem to fail I don't think it should even try to migrate anything..

[Logs](https://pastebin.com/3jjpZkUL)

**Comment by ciur** [comment]
Hi @dgalli1, can you please be more specific about following line?

> build the image locally which doesn't match the description in readthedocs

Which part of documentation description it didn't match?

This one:

> Papermerge can't find tesseract. Without it, OCR of the documents is impossible.


is very misleading. I agree. But it is correct. You can safely ignore that warning if **it is from inside papermerge_app.**

Let me explain:
the OCR is performed by the worker (``papermerge_worker`` docker container) and thus is installed only on the worker. However, for simplicity sake both worker and app (``papermerge_app`` and ``papermerge_worker``) use same code. From application code point of view they are 95% identical and use exactly same methods for reading configurations.
However:
 * for worker  - tesseract is mandatory
 * for main app - tesseract is optional

as long as that "missing tesseract" comes from papermerge_app docker container - you can just ignore it.

Current setup (even though little confusing) is very practical. The practicality of it is that worker and app many times run on same machine - e.g. in development mode - in such cases, issuing that warning reminds me (or other developers) to install tesseract.

**Comment by ciur** [comment]
I updated documentation with this know issue.
Link to the [known issue](https://papermerge.readthedocs.io/en/latest/known_issues.html#warning-about-missing-tesseract-in-papermerge-app-docker-container) with explanation in readthedocs.

**Comment by dgalli1** [comment]
> Which part of documentation description it didn't match?
I was referring to this:
https://papermerge.readthedocs.io/en/latest/setup/docker.html#docker
This will pull and start the necessary containers. If you wish, you can use docker-compose -f docker-compose-dev.yml up --build -d command instead to build local images. 

Currently the images get builded locally when cding into the 1.4 Folder because the build instructions are in  the docker-compose.yml file
[See build: ..](https://github.com/ciur/papermerge/blob/master/docker/1.4/docker-compose.yml)

`cd papermerge-proj/docker`
Should probably be updated for the 1.4 Folder. Or if you ask me i would just name it latest and only give numbers to the archived docker files.

> is very misleading. I agree. But it is correct. You can safely ignore that warning if it is from inside papermerge_app.
I assumed this warning was irrelevant. I acctualy sent you the wrong log file.... Anyways i just figured it out what really failed while writing this message. I messed up the docker-compose file, by not pointing the worker and the app to the same media volume, it seems to work flawless now. :facepalm:
