### ISSUE TITLE
docker-compose ver 1.4 failure

### ISSUE THREAD

**Issue by Pabl0z** [ciur/papermerge#279]
cloned repo from git finishes with errors

git clone https://github.com/ciur/papermerge papermerge-proj
Cloning into 'papermerge-proj'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 15776 (delta 48), reused 65 (delta 26), pack-reused 15671
Receiving objects: 100% (15776/15776), 22.92 MiB | 1.81 MiB/s, done.
Resolving deltas: 100% (10683/10683), done.
Checking connectivity... done.

docker-compose up -d
Creating network "14_default" with the default driver
Creating volume "14_postgres_data" with default driver
Creating volume "14_media_root" with default driver
Creating volume "14_redisdata" with default driver
Building app
Step 1/29 : FROM ubuntu:20.04
20.04: Pulling from library/ubuntu
da7391352a9b: Pull complete
14428a6d4bcd: Pull complete
2c2d948710f2: Pull complete
Digest: sha256:c95a8e48bf88e9849f3e0f723d9f49fa12c5a00cfc6e60d2bc99d87555295e4c
Status: Downloaded newer image for ubuntu:20.04
 ---> f643c72bc252
Step 2/29 : LABEL maintainer="Eugen Ciur <eugen@papermerge.com>"
 ---> Running in 5731eca91c8f
Removing intermediate container 5731eca91c8f
 ---> a71a2a28d4b1
Step 3/29 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Running in 281d54c223ad
Removing intermediate container 281d54c223ad
 ---> be733849ea6c
Step 4/29 : RUN apt-get update  && apt-get install -y                     build-essential                     vim                     python3                     python3-pip                     python3-venv                     virtualenv                     poppler-utils                     git                     imagemagick                     pdftk-java                     apache2                     apache2-dev                     locales  && rm -rf /var/lib/apt/lists/*  && pip3 install --upgrade pip
 ---> Running in 9382b2ba48b5
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package build-essential
E: Unable to locate package vim
E: Unable to locate package python3
E: Unable to locate package python3-pip
E: Unable to locate package python3-venv
E: Unable to locate package virtualenv
E: Unable to locate package poppler-utils
E: Unable to locate package git
E: Unable to locate package imagemagick
E: Unable to locate package pdftk-java
E: Unable to locate package apache2
E: Unable to locate package apache2-dev
E: Package 'locales' has no installation candidate
ERROR: Service 'app' failed to build: The command '/bin/sh -c apt-get update  && apt-get install -y                     build-essential                     vim                     python3                     python3-pip                     python3-venv                     virtualenv                     poppler-utils                     git                     imagemagick                     pdftk-java                     apache2                     apache2-dev                     locales  && rm -rf /var/lib/apt/lists/*  && pip3 install --upgrade pip' returned a non-zero code: 100
root@DS:

**Info:**
 - OS: synology SRM 6
 - Papermerge Version 1.4

**Comment by ciur** [comment]
Hi @Pabl0z, support for synology based docker images is not provided here. Please contact vendor of respective synology based packager.
