### ISSUE TITLE
mail import doesn't work

### ISSUE THREAD

**Issue by tigertim08** [ciur/papermerge#282]
Hello, 

I'm using papermerge with the docker setup on a proxmox lxc. Everthing works sofar unless I'm not able to setup the email import. I added the neccesary information to the papermerge.conf.py from the worker. It looks like that now:

`www@2523c80e1056:~$ cat papermerge.conf.py

DBUSER = "dbuser"
DBPASS = "dbpass"
DBHOST = "db"
DBNAME = "dbname"

MEDIA_DIR = "/opt/media"
STATIC_DIR = "/opt/static"
MEDIA_URL = "/media/"
STATIC_URL = "/static/"

OCR_DEFAULT_LANGUAGE = "deu"

OCR_LANGUAGES = {
    "deu": "Deutsch",
    "spa": "Español",
    "eng": "English",
    "fra": "Français",
    "rus": "Русский",
    "ron": "Română"
}

#These values are required if you want papermerge to import email attachments
#from specific email account.
#If you don't define a HOST, mail checking will just be disabled.
IMPORT_MAIL_HOST = "imap.goneo.de"
IMPORT_MAIL_USER = "XXXX
IMPORT_MAIL_PASS = "XXXX"
#IMPORT_MAIL_BY_USER = False
IMPORT_MAIL_BY_SECRET = "Ablage"
IMPORT_MAIL_DELETE = True
#IMPORT_MAIL_INBOX = "Eingang"`

I double checked the host, user and pass -> there are correct. But unfortunately no files are imported. 

I'm I missing something?

Thanks in advance
**Info:**
 - OS: Ubuntu 20.04 LTS
-  Database SQLite, PostgreSQL 12.1
 - Papermerge Version 1.5.5

**Comment by ciur** [comment]
settings ``IMPORT_MAIL_BY_SECRET`` and ``IMPORT_MAIL_DELETE`` are part of Papermerge 2.0 (which is still in development) i.e. they are not valid option/don't exist prior to 2.0 version. 
Sorry for confusion, I will update documentation with that note. Otherwise your configurations looks ok.

**Comment by tigertim08** [comment]
Thanks, I disabled the two options but the result is still the same. Is there a way to see where the worker fails? The log of the worker shows: 

`papermerge_worker | [2021-01-10 13:15:31,045: INFO/ForkPoolWorker-2] Task papermerge.core.management.commands.worker.txt2db[099be9fb-8618-4a39-b636-c8f43062b2bc] succeeded in 0.5137349280121271s: None
papermerge_worker | [2021-01-10 13:15:48,641: INFO/Beat] Scheduler: Sending due task import_from_email (papermerge.core.management.commands.worker.import_from_email)
papermerge_worker | [2021-01-10 13:15:48,645: INFO/MainProcess] Received task: papermerge.core.management.commands.worker.import_from_email[dc070768-126b-494e-8704-f37d17bfe96e]  
papermerge_worker | [2021-01-10 13:15:48,646: DEBUG/ForkPoolWorker-2] Celery beat: import_from_email
papermerge_worker | [2021-01-10 13:15:48,802: DEBUG/ForkPoolWorker-2] IMAP Import: UNSEEN messages 0 count
papermerge_worker | [2021-01-10 13:15:48,804: INFO/ForkPoolWorker-2] Task papermerge.core.management.commands.worker.import_from_email[dc070768-126b-494e-8704-f37d17bfe96e] succeeded in 0.15758350398391485s: None
papermerge_worker | [2021-01-10 13:16:18,661: INFO/Beat] Scheduler: Sending due task import_from_email (papermerge.core.management.commands.worker.import_from_email)
papermerge_worker | [2021-01-10 13:16:18,665: INFO/MainProcess] Received task: papermerge.core.management.commands.worker.import_from_email[0ba631c3-a0f7-4149-a97c-2c48b3f9befa]  
papermerge_worker | [2021-01-10 13:16:18,666: DEBUG/ForkPoolWorker-2] Celery beat: import_from_email
papermerge_worker | [2021-01-10 13:16:18,814: DEBUG/ForkPoolWorker-2] IMAP Import: UNSEEN messages 0 count
papermerge_worker | [2021-01-10 13:16:18,816: INFO/ForkPoolWorker-2] Task papermerge.core.management.commands.worker.import_from_email[0ba631c3-a0f7-4149-a97c-2c48b3f9befa] succeeded in 0.14987174997804686s: None`

So it tells me that their are no unseen messageges but thats just not the case... Their are some in the inbox and also I sent a new one after the disabling of the two options.

**Comment by francescocarzaniga** [comment]
@tigertim08 You need to create at least one user, i.e. the superuser as mentioned in the [setup guide](https://papermerge.readthedocs.io/en/latest/setup/manual_way.html#step-4-superuser).

**Comment by tigertim08** [comment]
> @tigertim08 You need to create at least one user, i.e. the superuser as mentioned in the [setup guide](https://papermerge.readthedocs.io/en/latest/setup/manual_way.html#step-4-superuser).

Since I'm using the docker version, I have a superuser "admin"

**Comment by francescocarzaniga** [comment]
@tigertim08 Then the importer is not seeing the user. Try opening a management shell (`python3 manage.py shell`) inside the docker container.
Then run the following:
```
from papermerge.core.models import User
User.objects.filter()
User.objects.filter(is_superuser=True)
```
and paste the output.

**Comment by tigertim08** [comment]
thank you, the Output looks like: 

`>>> from papermerge.core.models import User
>>> User.objects.filter()
<QuerySet [<User: admin>]>
>>> User.objects.filter(is_superuser=True)
<QuerySet []>
>>> `

**Comment by ciur** [comment]
@tigertim08, from the output above I see that you don't have superuser (administrative user).

You need to run in command line ``createsuperuser`` command in order to create superuser:
```
./manage.py createsuperuser
```
The above command will ask you username, email and password.

**Comment by tigertim08** [comment]
Thank you @ciur and @francescocarzaniga! It works know :)
