### ISSUE TITLE
document as jpeg in papermerge are downloded as pdf

### ISSUE THREAD

**Issue by bolbit** [ciur/papermerge#288]
I, 
I run papermerge via a docker image (linuxserver), behind haproxy. Papermerge version is 1.5.5

**Description**

I just emailed a document with the name xxx.jpeg. It shows perfectly in papermerge.
I tried downloading it and by default the document was renamed to xxx.pdf when downloading.
I thought the tool turned jpegs to pdf.
The downloaded document xxx.pdf was not a pdf (error when opening)
Renaming the download xxx.pdf to xxx.jpeg, solved the problem.

**Expected**

The extension should be kept when downloaded.

**Actual**

What actually happens

**Info:**
 - OS: Ubuntu 18.04 LTS
 - Firefox
-  dataBase : the one in the linuxserver docker image ..
 - Papermerge Version [1.5.5]

**Comment by bolbit** [comment]
I forget, i downloaded the jpeg when viewing it in papermerge, not in the "file list" view.

**Comment by ciur** [comment]
@bolbit, thanks for reporting this bug.
