### ISSUE TITLE
Broken Image Icon when importing jpg or jpeg files.

### ISSUE THREAD

**Issue by tkammerlander** [ciur/papermerge#29]
Dear Support-Team,

when i upload a jpg or jpeg file i get the following screen:
![image](https://user-images.githubusercontent.com/1456877/86369984-6f284500-bc7f-11ea-9101-39b7a560d933.png)

Would be great if its possible to import jpg too.

With kind regards,

Thomas

**Comment by ciur** [comment]
This is definitely a bug. I will fix this bug over the weekend and update docker image.
Thank you for opening this issue.

**Comment by ciur** [comment]
Will be fixed as part of 1.4.0 release.

**Comment by tkammerlander** [comment]
do you already know a rough release date? regards thomas

**Comment by ciur** [comment]
Fixed. As mentioned above, fix is available in 1.4.0 (out in August 2020).
