### ISSUE TITLE
Installation help - Cant see folder

### ISSUE THREAD

**Issue by chanml** [ciur/papermerge#292]
Hi, after installation, can't see the folders, only continually wave circle as below. Is error due to worker.service? Any error log we can use to troubleshoot? 
Ubuntu 20.04
nginx/1.18.0
gunicorn (version 20.0.4)
papermerge v1.5.5

![image](https://user-images.githubusercontent.com/885762/106372982-4badb000-63b0-11eb-9461-768fcbe3d8e6.png)
![image](https://user-images.githubusercontent.com/885762/106373175-df33b080-63b1-11eb-9864-c95ba661f2b5.png)

**Comment by jjkonway** [comment]
what does your nginx config look like?

**Comment by ciur** [comment]
It looks like client side/javascript error. What web browser you use ? Can you confirm if there are javascript errors?

**Comment by chanml** [comment]
Looks like it is solved after another run of ./manage.py collectstatic to copy the static files and clear my Chrome browser cache.
Thanks Eugen for this awesome project.

> It looks like client side/javascript error. What web browser you use ? Can you confirm if there are javascript errors?
Yes there is 3 .map files missing, but the error still show after I have resolved it. Chrome. 

![image](https://user-images.githubusercontent.com/885762/106546857-125b7880-6547-11eb-81ce-1a4b18a95347.png)
