### ISSUE TITLE
REST API doc upload, python requests issue. 

### ISSUE THREAD

**Issue by jjkonway** [ciur/papermerge#294]
Uploading pdf to inbox via REST api and **python requests** does not trigger the worker. I get a response 200, and The document appears in the inbox, and the log shows STARTED OCR  for each page. but it never actually COMPLETED OCR. 

Drag and drop into inbox works fine. 

This is with gunicorn and nginx, ..if i run the server through manage.py runserver, python request triggers the worker normally. 
........

But, if I use CURL to upload the pdf, it works fine and triggers the worker as it should . 

Any thoughts? 
thanks. 

**Info:**
 - OS :Ubuntu 20.04 LTS
 - Browser  n/a
-  Database [PostgreSQL 12.1]
 - Papermerge Version1.5.3

Unrelated: 
is there any possibility to upload meta data with the document down the line? Or any suggestions to where to look in the code regarding accessing or editing the metadata in python?

**Comment by ciur** [comment]
@jjkonway 

> is there any possibility to upload meta data with the document down the line? 

This feature will be implemented in later versions, when more sophisticated REST API will be introduced. 

> Or any suggestions to where to look in the code regarding accessing or editing the metadata in python?

Sure, metadata is added/edited in [this view](https://github.com/papermerge/papermerge-core/blob/master/papermerge/core/views/metadata.py). As comments mention there, metadata is stored per Page (that is when end user saves metadata on the document, that metadata is actually saved on the first page of respective document).

**Comment by jjkonway** [comment]
Nevermind! it was my code. workng now thanks
