### ISSUE TITLE
demo password is wrong

### ISSUE THREAD

**Issue by pvinis** [ciur/papermerge#306]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**

**Expected**

**Actual**
What actually happens

**Info:**
 - OS: [e.g. Windows 10, Ubuntu 20.04 LTS]
-  Database [SQLite, PostgreSQL 12.1]
 - Papermerge Version [e.g. 1.4.3]

**Comment by ciur** [comment]
Credentials for [demo account](https://demo.papermerge.com) are:
username: guest
password: password77a

They are correctly listed on [github page](https://github.com/ciur/papermerge#live-demo) and on [official webpage](https://www.papermerge.com/demo).

**Comment by pvinis** [comment]
Oops, veeeery sorry. I typed `demo` for username. My bad, thanks.
