### ISSUE TITLE
List-View: Meta-Data-Columns appears multiple times

### ISSUE THREAD

**Issue by Popoboxxo** [ciur/papermerge#310]
**Description**
Meta-Data-Columns appears multiple times after adding this Meta-Data (Specification) on a parent Folder. 

![image](https://user-images.githubusercontent.com/11631395/108495458-1b6b7a00-72a9-11eb-82bd-2d66914ea111.png)

**Expected**
Unique Meta-Data appear in any Child-Folder-Hierarchy always a single time in the List-View.

**Actual**
Folder-Path: Hauptseite -> Versicherungen -> Krankenversicherung

Setting up the meta-Data (config) "Jahr" and "Versicherungs-Nr." on the Folder "Versicherungen" inherit the configuration to the Documents inside the Child-Folder “Krankenversicherung”

But then, both Columns appear duplicated in the List-View.

After opening and closing an Document, the Columns appear normally without any duplicates.

![image](https://user-images.githubusercontent.com/11631395/108495979-c11ee900-72a9-11eb-8539-cb55007882d3.png)
 

**Info:**
 - Server: Unraid Version: 6.8.3, https://hub.docker.com/r/linuxserver/papermerge/
 - Browser Edge Version 88.0.705.74 (Offizielles Build) (64-Bit) 
-  Database Maria DB 5.5.57
 - Papermerge Version 1.5.5
 
 **PS:**
 Ein sehr cooles Projekt! Ich hoffe, dass ich mich hier und da etwas einbringen kann!

**Comment by ciur** [comment]
Hallo @Popoboxxo, danke für die Meldung. Das Bug ist ein Duplicate von #191, dass in version 2.0 (noch in development) gefixt ist.

**Comment by Popoboxxo** [comment]
Perfekt! Vielen Dank!

**Comment by ciur** [comment]
@Popoboxxo, fix is available as part of 2.0.0rc38 release (you can double check on [demo page](demo.papermerge.com/), credentials are: guest/password77a)
