### ISSUE TITLE
Bug leads to multiple folder creation 

### ISSUE THREAD

**Issue by l4rm4nd** [ciur/papermerge#315]
Version: Papermerge 2.0rc35

Log into the Papermerge web application and visit /admin/browse. Create a new (invalid) folder named

``
<prohibited-chars>
``

You'll receive an application error as follows

![image](https://user-images.githubusercontent.com/21357789/109235862-d2e31d80-77ce-11eb-8bdc-0c5b933efb36.png)

Now proceed and create a new (valid) folder with an example name of

``
valid-foldername
``

The new folder is created multiple times due to the previous application error:

![image](https://user-images.githubusercontent.com/21357789/109236012-13db3200-77cf-11eb-9124-47e22034d4b3.png)

**Comment by ciur** [comment]
@l4rm4nd, danke für deine Hilfe!

**Comment by ciur** [comment]
@l4rm4nd, fix is not part of [2.0.0rc38 release](https://github.com/ciur/papermerge/releases/tag/v2.0.0rc38)

**Comment by l4rm4nd** [comment]
Fixed. Cannot reproduce the issue again!
