### ISSUE TITLE
Cross-Site Scripting (XSS) in Permission Management

### ISSUE THREAD

**Issue by l4rm4nd** [ciur/papermerge#316]
Version: Papermerge 2.0rc35

Group names are not properly escaped, which leads to XSS if the permissions of a document are edited.

****Steps to reproduce****

First, create a new group with the following XSS payload as group name:

````
<script>alert(0)</script>
````

![image](https://user-images.githubusercontent.com/21357789/109238191-63236180-77d3-11eb-9e88-f210009ce562.png)

Then proceed and upload an example document into the papermerge application. 

Select the document, right-click and chose `Permissions`.

![image](https://user-images.githubusercontent.com/21357789/109238351-aaa9ed80-77d3-11eb-9cca-140c720ee425.png)

After clicking the `edit`, `create` or `view` button, the group name's XSS payload is triggered and executed by the browser.

![image](https://user-images.githubusercontent.com/21357789/109239020-d9749380-77d4-11eb-89f9-8431b876b3a2.png)

****Steps to mitigate this issue****

As previously, it is recommended to escape all untrusted user input before reflecting or storing the data.

**Comment by ciur** [comment]
@l4rm4nd, thank you for your detailed report. I will take care of XSS fixes!

**Comment by ciur** [comment]
@l4rm4nd, fix is not part of [2.0.0rc38 release](https://github.com/ciur/papermerge/releases/tag/v2.0.0rc38)

**Comment by l4rm4nd** [comment]
Seems fixed. Cannot reproduce the XSS vulnerability.

![image](https://user-images.githubusercontent.com/21357789/110302190-3fdd8b00-7ff9-11eb-9df2-174235b37996.png)
