### ISSUE TITLE
LANGUAGE_CODE not working in 2.0.0 (rc38)

### ISSUE THREAD

**Issue by tobire** [ciur/papermerge#320]
**Description**
When changing the LANGUAGE_CODE to "de" in a config file that is run with the docker image eugenci/papermerge:2.0.0.rc38, the UI languages does not change.

I also mounted the config file from the docker folder (docker/2.0/config/papermerge.config.py) into the volume directly and verified that the LANGUAGE_CODE is set by running `docker exec -it papermerge_app /bin/bash` and then `cat papermerge.config.py` in the container.

In both cases (with and without the mounted config file) the UI language does not change.

When using the 1.5 docker-compose setup, changing the language in the file docker/1.5/config/papermerge.config.py, it changes the UI language as expected.

**Expected**
The UI language should change to german.

**Actual**
The UI language stays english.

**Info:**
 - Docker version 19.03.14, build 5eb3275d40
 - docker-compose version 1.25.3, build d4d1b42b
 - Browser: Firefox
 - Papermerge Version 2.0.0 rc38

**Comment by ciur** [comment]
sounds like a bug :)

**Comment by ciur** [comment]
hm, I double checked it, and it works i.e. ``LANGUAGE_CODE='de'`` in ``papermerge.conf.py`` file, user interface language changes to german. 
The problem is that many elements are not localized e.g. instead of Herunderladen is "Download". But Inbox is correctly set to "Posteingang", "sign out" is "Abmelden":

![Screenshot from 2021-02-28 13-13-02](https://user-images.githubusercontent.com/24827601/109418100-d93bea00-79c6-11eb-8368-94944d8112c6.png)

@tobire, can you please confirm that it is an issue of "text localization" i.e. many elements are not correctly translated?

**Comment by telsch** [comment]
For me it's working if i set it in settings.py but not in papermerge.conf.py. Using latest lsio docker image. For me `LANGUAGE_FROM_AGENT = True` doesn't work in both.

**Comment by tobire** [comment]
I'm new to the Project so i'm not Sure on all the different config Files yet. I added the LANGUAGE_CODE Line in docker/2.0/config/papermerge.config.py and that did Not Change the UI after starting with docker-compose.
The Same but in the docker/1.5/... Folder worked fine.

I did Not find the papermerge.conf.py File anywhere while Testing this, so I can't say anything about that.

However it could also be that I edited the wrong File.

**Comment by tobire** [comment]
I just tried out the linuxserver.io image (also with docker-compose) and changing the language in the mounted config file there works fine.
So it might be just that I didn't find the right file to edit using the described setup.

@ciur I'll leave this issue open for now. If you can't reproduce my original problem, feel free to close it though.
If it is indeed a problem with the docker files or setup, there might be the need to describe that process a bit more to allow people to edit the right files in their setup :)
