### ISSUE TITLE
API document upload broken

### ISSUE THREAD

**Issue by telsch** [ciur/papermerge#321]
**Description**
Document can't be uploaded via API. Fetching document information works.

**Expected**
Upload a document via API inserts document in users inbox.

**Actual**
Got following error message.
{"detail": "Unsupported media type \"\" in the request."}

 - OS: docker
 - Browser Firefox
-  Database SQLite
 - Papermerge Version 2.0rc38

**Comment by ciur** [comment]
@telsch, thank you for reporting this. What document type did you upload ? pdf, jpeg, png or tiff ?

**Comment by telsch** [comment]
I have only tried to upload a PDF. Also set the content type to application/pdf failed.

**Comment by ciur** [comment]
I just checked, indeed, for some reason, it always reports "unsupported media type".
Thank you for reporting this bug! Will be fixed.

**Comment by Ryther** [comment]
Hi,
tried with a .png with the same outcome.
I've updated my importer to manage errors a lot better (version 1.2.0 of the docker image)
