### ISSUE TITLE
Docker install Documentation does not tell to go to /docker/2.0 or 1.5

### ISSUE THREAD

**Issue by SB97** [ciur/papermerge#322]
Docker install Documentation does not tell to go to /docker/2.0 or 1.5
`Run docker compose command (which will pull images from DockerHub):

cd papermerge-proj/docker
docker-compose up -d

`

The readme states:
`Try it!

You can try it with just 3 simple commands (you need git and docker-compose):

git clone git@github.com:ciur/papermerge.git
cd docker/1.4/
docker-compose up
`
which is closer but 1.5 and 2.0 is current

**Comment by ciur** [comment]
@SB97, good point. I will update documentation.  By now you should use ``cd docker/2.0/; docker-compose up``

**Comment by ciur** [comment]
[readme updated](https://github.com/ciur/papermerge/commit/25336ffaf37f852882de666dc02ca9c2fda732ee)
