### ISSUE TITLE
Can't go to Page 2

### ISSUE THREAD

**Issue by w4tzmann** [ciur/papermerge#324]
**Description**
I have a folder with many files. It shows my a button for page 2, but I can't go there. If i click on '2', it redirects to the start page of documents.
URL for folder Documents: https://dms.mydomain
URL for folder with the documents: https://dms.mydomain/#100
Link for page 2: https://dms.mydomain/?page=2

So for me it looks like the Link to page 2 is broken, not sure where the problem is: Papermerge, or traeffik.
Also I can't see the documents (which I think there are on page 2), when i change the sort order.

**Expected**
Switch to page 2 in the folder.

**Actual**
Landing on the Documents page.

**Info:**
 - OS: Windows 10
 - Browser Edge
-  Database PostgreSQL
 - Papermerge Version 2.0.0.rc38

**Comment by ciur** [comment]
ah, that's a bad bug. I will fix it. @w4tzmann, thanks for reporting!

**Comment by w4tzmann** [comment]
wow, you are faster then light! Thank you for you work and you passion.

**Comment by ciur** [comment]
Fixed. Fix available in latest release, which is [2.0.0rc45](https://github.com/ciur/papermerge/releases/tag/v2.0.0rc45).
