### ISSUE TITLE
Per-User Import Folders

### ISSUE THREAD

**Issue by tobire** [ciur/papermerge#325]
**Is your feature request related to a problem? Please describe.**
I'm looking to host my family in one papermerge instance with different user accounts. There would be different scanners that are used by different people so they should be able to be logically assigned to an account.

**Describe the solution you'd like**
Either the possibility for a completely different import folder per user or subfolders per user in the import folder that assign documents to the respective user instead of the superuser.

**Describe alternatives you've considered**
Bad alternative: Set up a script that takes different input folders and sends the documents to the e-mail that is setup for importing with the secret of the specific user.
Using the REST-API would also be possible, but it would also require additional scripts to take documents from a folder and push them to the API.

**Additional context**
I Hope it's pretty self explainatory :)

**Comment by Ryther** [comment]
Hi, I've already asked this question on reddit. Since then I've created a script and a docker container that run it.
Try it and see if that helps with your case:
[Importer Script](https://github.com/Ryther/papermerge-importer)
[Docker Container](https://github.com/Ryther/docker-papermerge-importer)

**Comment by dazx2021** [comment]
ERROR: Service "papermerge-importer-user1" uses an undefined secret "papermergeimporter_auth_token1"
Any idea I got this error messages?

**Comment by Ryther** [comment]
> ERROR: Service "papermerge-importer-user1" uses an undefined secret "papermergeimporter_auth_token1"
> Any idea I got this error messages?

You need to define the secret in your docker-compose.yaml (as seen in the example) and ensure you have your API token in the file mentioned in the secret

**Comment by ciur** [comment]
This feature is now available via [papermerge-cli import /path/to/some/folder](https://docs.papermerge.io/Command%20Line%20Utilities/cli.html#import-folders-documents) command line utility.

`papermerge-cli` command line utility takes as input a token which is user specific. Imported document, by default, end up in user's inbox (in the user whose token was used for authentication).
