### ISSUE TITLE
Make move-to-folder automation predictable

### ISSUE THREAD

**Issue by amo13** [ciur/papermerge#326]
**Is your feature request related to a problem? Please describe.**
Assume we have an automation to move a document to the "medical" folder if it matches the word "medical" and another automation to move a document to the "invoice" folder if it matches the word "invoice". Not we drop a document containing both words into the inbox for processing. Where will it be moved?

**Describe the solution you'd like**
I am not sure about how to solve this as it might require the implementation of a rather complex logic, which might be out of scope.
One idea that comes to my mind is having a priority/precedence setting maybe ranging from "low" to "high" or from 1 to 10. But I guess this is still a naive solution. Designing a logic that makes the selection of the destination folder 100% predictable according to settings in conflicting automations is probably nearly impossible. I guess this is why one prefers to use tags instead of folders.

Anyway, is there a way to predict the destination folder for conflicting automations like in the example above? Maybe I am just missing something here...

**Comment by ciur** [comment]
Solution is to be as specific as possible. In your example, next to "medical" e.g. "Charité Universitätsmedizin"  or other more specific keywords. Using just word "invoice" is too general.

**Comment by MarcSN311** [comment]
@ciur I had the same problem and I think there is a solution for this:

give automations an order and give the user the ability to change it. No complex priority, just a fixed order in which they are run.
