### ISSUE TITLE
REST API: Create folder structure

### ISSUE THREAD

**Issue by telsch** [ciur/papermerge#329]
For existing documents that are already stored in directories, it would be good to be able to map this existing directory structure via the API during import. Until now, you can only upload documents with certain names without being able to create directories in which the document is stored.

**Comment by ciur** [comment]
Feature was implemented. [In this document section](https://docs.papermerge.io/REST%20API/overview.html#nodes-folders-and-documents) is described how to use REST API to create a specific folder structure and how to upload documents into those folders.
