### ISSUE TITLE
Applying tags broken

### ISSUE THREAD

**Issue by telsch** [ciur/papermerge#330]
**Description**
Adding tags to documents or directories no longer works.

**Expected**
When a tag is added to a document or directory, it is also applied.

**Actual**
The tag is not displayed after it is applied.

**Info:**
 - OS: Docker
 - Browser Firefox
-  Database SQLite,
 - Papermerge Version 2.0.0.rc43

**Comment by ciur** [comment]
man, it works. I checked both on demo and on my local dev environment. 

![papermerge-tagging](https://user-images.githubusercontent.com/24827601/110125677-e04a6a00-7dc3-11eb-9799-c4c838d3249c.gif)

**Comment by telsch** [comment]
You're right, i missed semicolon, then it's applied but without semicolon not.

**Comment by ciur** [comment]
@telsch, [comma are important](https://papermerge.com/docs/User%27s%20Manual/tags_and_folders.html#remember-the-comma).
