### ISSUE TITLE
Cut and paste multiple folders broken

### ISSUE THREAD

**Issue by telsch** [ciur/papermerge#331]
**Description**
When multiple folders are cut to paste into another folder, it does not work. With only one selected folder it works.

**Expected**
If several folders are cut to paste them, they should be moved.

**Actual**
Nothing at all.

**Info:**
 - OS: Docker
 - Browser Firefox
-  Database SQLite
 - Papermerge Version 2.0.0.rc43

**Comment by telsch** [comment]
Ahh sorry, not cut and paste folders are broken! Select multiple folders and move them per drag&drop didn't work.

**Comment by ciur** [comment]
hey man, drag & drop is not yet implemented. I agree it would be great to have it, but it will takes time :)

**Comment by telsch** [comment]
OK thanks for clarification!
