### ISSUE TITLE
Crash when trying to acess Logs 

### ISSUE THREAD

**Issue by jvps5656** [ciur/papermerge#332]
![Captura de Tela (3)](https://user-images.githubusercontent.com/55995021/110125464-17a81f00-7da2-11eb-9018-82f98ce61bd3.png)

Brand new version 2.0 installation from today

 - OS: [Windows 10, Debian10]
 - Browser [ chrome, firefox]
-  Database [PostgreSQL 11.10]
 - Papermerge Version [2.0rc43]

**Comment by ciur** [comment]
Did you run it from docker container ? What docker container you used ?

**Comment by jvps5656** [comment]
I used normal installation

**Comment by ciur** [comment]
I cannot reproduce.
