### ISSUE TITLE
How I would like to use papermerge as a paperless user

### ISSUE THREAD

**Issue by Tooa** [ciur/papermerge#34]
Hi, 
this is a reply to your paperless issue ticket showcasing your project papermerge. I would like to give you some feedback on the project from the perspective of a paperless user. Further, I would like to describe my current paperless setup and how I would love to use papermerge in the future (tested version v1.2.3)

Feel free to ask questions if something is unclear.

# Usage

## How I use Paperless (docker installation)

1. I scan a new document with my iPhone scan app, name it `20200711Z - correspondent - title` and choose WebDav target in the app to upload it to my NAS
2. The WebDav target is configured as the import folder for paperless via a docker host mount
3. Paperless then consumes the document and stores it in its media folder with a name pattern I configured e.g. /media/{date}-{correspondent}-{title}.pdf
4. Via the `Post-consumption` [script](https://paperless.readthedocs.io/en/latest/consumption.html) of paperless, I send a notification via Telegram to my phone
5. Because the media folder is a host mount and configured as NFS share on my NAS, I can browse the documents from any PC with the file explorer. Sometimes, this is quicker than using the web interface.

### Things that trouble me with this workflow

- Often in step (1), I make a mistake with the fixed naming schema paperless expects. In these cases paperless imports titles as tags or as correspondents. I don't log in to paperless for weeks and just keep uploading documents. It is quite some effort then to delete all wrong tags manually, rename the documents accordingly, and assign the correct tags and correspondents finally. I would love to have an Inbox, where I can correct such mistakes and only when I click e.g. `import to documents` the document's metadata is merged with my existing structure. Then, I wouldn't have to delete the wrong tags and correspondents.

## How I would like to use Papermerge (docker installation)

1. I scan a new document with my iPhone scan app, name it  `20200711Z - correspondent - title` and choose WebDav target in the app to upload it to my NAS
2. The WebDav target is configured as the import folder for papermerge via a host mount
3. Papermerge then consumes the document and stores it in its media folder with a name pattern I configured e.g. /media/{date}-{correspondent}-{title}.pdf
4. When I log in, I see the new document in the Inbox view. I can correct the tags, the correspondent, and the document time. Once I'm finished I can bulk "import" the Inbox.
5. Because the media folder is a host mount and configured as NFS share on my NAS, I can browse my documents from any PC with the file explorer

# Feature Requests

## Blocker

Following a few things that do not work out for me and therefore block me from migrating to papermerge as a paperless user:

* I miss tags (feature request #21), correspondents and document dates as paperless support them
* I was not able to use a host mount for the import folder. When using the following volume `./import:/opt/papermerge/import/` with the worker, I have no permissions to copy files in the created host mount `import`
* Backup and restore is crucial for me when using a system with important data. [Looks](https://papermerge.readthedocs.io/en/latest/migrations.html) like this is not supported yet but planned with #23.

## Would need in the future

* I miss filters for tags, correspondents and date ranges
* Customizable file names as I also browse my media folder via an NFS share

## Improvements

* Usability: The paperless search shows me the documents as little preview images. This makes it easy for me to identify the right document as I often can identify them by their appearance. I miss a similar preview in the papermerge search list. Maybe use document previews in grid view and text preview in list view?
* Usability: After clicking on a search item I cannot go back to the search. Thus, I have to redo the search. When a search term has a lot of hits it might be frustrating to always do the same search when one clicked on the wrong document in the process of finding the right one.
* Bug: Using the "New folder" Button twice with the same folder name will create the folder twice with the same name
* Bug: Simply clicking Pages->Paste->Pages causes `KeyError at /paste-pages/`

## Nice to have

* Raspberry Pi / ARM support
* WebDav worker (see use case) would allow me to upload documents directly to papermerge
* Papermerge suggests tags and correspondents for documents in the Inbox. This would allow uploading documents with a title only. It should be optional to apply these suggestions automatically
* Mobile friendly UI (haven't tested yet)
* **Updated:** Hooking into the Consumption Process allows executing arbitrary commands for certain states (see [here](https://paperless.readthedocs.io/en/latest/consumption.html)). For example, I have linked scripts that notify me in Telegram when the document is successfully imported. So, I know when to better not shred a physical document ;)
* Will edit for more

**Comment by ciur** [comment]
wow, I am very impressed ! Thank you very much for detailed feedback! Let me go over it very carefully and I will come back with a detailed reply.

**Comment by ciur** [comment]
first question: what is **correspondent**? I saw it in paperless source code/documentation but was unable to figure it; out what does it stands for ? (obviously I know [dictionary description of the word](https://www.dictionary.com/browse/correspondent?s=t), but what does it mean in paperless/papermerge context ? )

**Comment by Tooa** [comment]
> Thank you very much for detailed feedback!

No problem, you are welcome.

> What is correspondent?

Correspondent refers to the sender of the document. Let's say you receive a bill from your insurance called "TK - Technikerkrankenkasse" then `correspondent` refers to that name. Tagging the documents with the correspondent allows me to quickly filter all correspondence between me and that specific insurance.

**Comment by totti4ever** [comment]
I can second the workflow and feature request plus blocker to like 95%, also being a paperless user. Would love to give papermerge a try (and I love the idea to have an folder view additionally!), but right now, it is nothing which would help me.

Will check back regularly as you seem to be ambitious on this project :-) !

**Comment by ciur** [comment]
@totti4ever  thank you for your feedback! 

Backup/Restore feature was implemented. See #23.
Tags management is planned for [version 1.5.0](https://github.com/ciur/papermerge/milestone/1)

**Comment by Pyromane** [comment]
> Tags management is planned for [version 1.5.0](https://github.com/ciur/papermerge/milestone/1)

Date and time "Tags" are automatically recognized and assigned at paperless, which is a great relief.

Using keywords, self-defined tags can be automatically assigned to the documents when they are recognized.

**Comment by ciur** [comment]
tag feature is top priority for 1.5 release. I absolutely agree that tags  is a must for any decent document management.

This part:

> Date and time "Tags" are automatically recognized

In Papermerge is called [Automates](https://papermerge.readthedocs.io/en/latest/automation.html).
It is already there. It can 'recognize' documents and move them to destination folder.
As bonus automates can extract metadata from recognized document. But that is a more advanced feature.
Anyway, when tags feature will be ready, user will be able to configure automates so that recognized document will be assigned 'automatically' preconfigured tags.

Sounds, cool, eh ? :100:  :+1:

**Comment by Pyromane** [comment]
Sounds great! Thanks for the detailed answer!
(I assumed the status of your last video)
