### ISSUE TITLE
Fixed XSS during file upload time

### ISSUE THREAD

**Issue by B3EF** [ciur/papermerge#340]
the rendering of file name during the file upload time has caused an xss.
i have fixed it in your papermerge-js repo please refer this 
https://github.com/418sec/papermerge-js

**Comment by ciur** [comment]
@BEFF, thanks for pull request, I will take care !

**Comment by B3EF** [comment]
Hi @ciur any updates?

**Comment by ciur** [comment]
See my comment [here](https://github.com/ciur/papermerge-js/pull/13#issuecomment-803257845).
