### ISSUE TITLE
pagination for pinned tags does not work

### ISSUE THREAD

**Issue by MarcSN311** [ciur/papermerge#349]
**Description**
Click on page 2 (or any other page) on a pinned tag page

**Expected**
get to the second page related to this tag `https://papermerge.mydomain.tld/admin/browse#tagged/myTag?page=2`

**Actual**
get to the documents overview page 2 `https://papermerge.mydomain.tld/admin/browse?page=2`

**Info:**
 - OS: Windows 10
 - Browser Firefox, Opera, Chrome
-  Database PostgreSQL
 - Papermerge Version 2.0rc43

**Comment by ciur** [comment]
thanks for opening this. Indeed pinned tags do not take into consideration pagination :(
