### ISSUE TITLE
[Edge Chromium] Login screen after every action

### ISSUE THREAD

**Issue by FutureCow** [ciur/papermerge#35]
I;m running the docker version (1.2.2 or 1.2.3).  After i login on my Edge browser, i see the start screen. When clicking on Inbox, upload a document or do anything else, it will first return to the login screen. 
I also tried chrome and to "older" edge, there was no problem,

Chome: Versie 83.0.4103.116
Edge: Versie 85.0.552.1

Simpel log from docker (can i debug more?)

Edge:
[11/Jul/2020 17:40:25] "GET /admin/core/basetreenode/1/list/ HTTP/1.1" 302 0
[11/Jul/2020 17:40:25] "GET /admin/login/?next=/admin/core/basetreenode/1/list/ HTTP/1.1" 200 3265

Chrome:
[11/Jul/2020 17:40:42] "GET /admin/core/basetreenode/1/list/ HTTP/1.1" 200 25983
[11/Jul/2020 17:40:42] "GET /document/2/preview/4/page/1 HTTP/1.1" 200 5080
[11/Jul/2020 17:40:43] "GET /clipboard/ HTTP/1.1" 200 1

Also tried the master version (1.4.0) there was the same problem.

**Comment by ciur** [comment]
I am little bit confused. Mentioned versions of Chrome (83.0...) and Edge (85.0...) are the ones which **do have** the problem, right?

> I also tried chrome and to "older" edge, there was no problem,

Can you please be more specific? What version you mean by "older" ? I may be helpful to track the problem.

I assume that above info refers to Windows OS.
Can you please tell me what on Windows version you tested ?

In general to me, the problem sounds like some browser specific cookie based issue. Maybe that version of Edge does not accept to save insecure cookies (docker version is over HTTP, not HTTPS). Just first guess.

**Comment by FutureCow** [comment]
Sorry for not being clear.

Chrome 83.x is working correctly
Edge 85.x (based on chromium) does not work correctly
Edge 44.x (based on EdgeHTML) is working correctly

But you the problem might the a wrong cookie, after a cleaning also Edge 85.x looks like it's working correctly. So this issue can be closed i think. Will try it a little bit more in the next days!

Thanks for this great software, looking forward for the 1.4.0 release!

**Comment by ciur** [comment]
OK, then I close this issue. 
thanks for feedback!
