### ISSUE TITLE
"Try it!" default username/password not working

### ISSUE THREAD

**Issue by carldavis** [ciur/papermerge#351]
I've tried the [Try it!](https://github.com/ciur/papermerge#try-it) instructions and the username/password of admin/admin do not seem to work. \<pre-apology\>I've really tried to make sure this is not a dumb mistake on my part but I'm still suspicious I simply need more coffee.\</pre-apology\>

![image](https://user-images.githubusercontent.com/3662661/111613113-2df3a900-87ac-11eb-9831-e45fe0c911d4.png)

**Comment by ciur** [comment]
man, admin's username + password are pretty much [hardcoded into docker image](https://github.com/ciur/papermerge/blob/master/docker/scripts/create_user.py), and they are ``admin`` / ``admin`` :)

Maybe there some errors in console when you start docker compose  ?

**Comment by sudo-talon** [comment]
I pulled my repo from https://github.com/ciur/papermerge papermerge-proj and I am experiencing same issue, username and password admin/ admin not working

**Comment by Christoph-wq** [comment]
got mine from https://github.com/ciur/papermerge as well. admin/admin is not working
