### ISSUE TITLE
How to delete all items in folder INBOX ???

### ISSUE THREAD

**Issue by Marook332** [ciur/papermerge#353]
**Description**
My inbox contains about 27849 documents and i want to delete them all

**Expected**
A method to mass delete items in my inbox

**Actual**
For some reason, two scanned pdf's bombed my inbox :)

**Info:**
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome latest
-  Database: SQLite
 - Papermerge Version : 2.0rc48
![image](https://user-images.githubusercontent.com/13482386/111638128-586c5300-87fa-11eb-9069-ad903136008b.png)

**Comment by ciur** [comment]
Here is a short screencast on how to do it, hopefully github doesn't mind 8MB animated gif :).

![delete-documents-from-inbox](https://user-images.githubusercontent.com/24827601/111685865-b57efd80-8828-11eb-9cdb-5638d7f7f82d.gif)

**Comment by Marook332** [comment]
Thank you, it seems to work but take a while...i will close this 'bug' when it's finished!
