### ISSUE TITLE
[Docker] Edited Tag of an existing Automate is not stored after Submit

### ISSUE THREAD

**Issue by schdagi** [ciur/papermerge#357]
**Version**
linuxserver/papermerge:v2.0.0rc48-ls31

**How to reproduce**
Create a new automate and leave the tag option empty. Submit.
Use the Automate/Edit option to add a tag. Submit.

**Expected behaviour**
Selected Tag is permanently stored after Submit.

**Actual behaviour**
Tag stays "empty" after Submit

![image](https://user-images.githubusercontent.com/62592051/112196739-9fe44c00-8c0b-11eb-93b8-7d912e850f38.png)

**Comment by schdagi** [comment]
Resolution: User error
" , " must be placed after the tag is selected

**Comment by ciur** [comment]
oh, man, I fall many times into that 'trap' too. This is a subtle reminder that UX (user experience) can be improved.
Thanks for opening the ticket anyway, it served me as reminder :)
