### ISSUE TITLE
Login doesn't work (docker)

### ISSUE THREAD

**Issue by tigertim08** [ciur/papermerge#359]
Hello together, 

yesterday I tried do setup papermerge via docker. Sofar everything worked put if I'm trying to log in with as admin with the standart password "admin" it tells me "The username and/or password you specified are not correct." 

Any Idea how to fix that?

**Comment by ciur** [comment]
@tigertim08, sure!
Here is a step by step screencast on how to reset admin's password using django's shell :)

![reset-admin-password](https://user-images.githubusercontent.com/24827601/113264907-cd985780-92d3-11eb-80ac-212111c85a3d.gif)

**Comment by tigertim08** [comment]
Thanks! worked perfect :)

**Comment by multimill** [comment]
Just did a fresh install (first use) and the login/password did not work. 

But the solution given by @ciur worked!

**Comment by typkrft** [comment]
Fresh install of docker using the Compose verbatim admin admin did not work.

**Comment by Johnnyyr** [comment]
the same problem in 2023 restart fixed

**Comment by rodieter** [comment]
> @tigertim08, Sicher! Ich kann mir keinen Grund vorstellen, warum Ihr Admin-Passwort nicht mehr funktioniert. Vielleicht einfach Kappen aufsetzen? :) Auf jeden Fall finden Sie hier einen Schritt-für-Schritt-Screencast zum Zurücksetzen des Administratorkennworts über die Befehlszeile:
> 
> ![Admin-Passwort zurücksetzen](https://user-images.githubusercontent.com/24827601/113264907-cd985780-92d3-11eb-80ac-212111c85a3d.gif) [ ![reset-admin-password](https://user-images.githubusercontent.com/24827601/113264907-cd985780-92d3-11eb-80ac-212111c85a3d.gif) ](https://user-images.githubusercontent.com/24827601/113264907-cd985780-92d3-11eb-80ac-212111c85a3d.gif) [ ](https://user-images.githubusercontent.com/24827601/113264907-cd985780-92d3-11eb-80ac-212111c85a3d.gif)

Schade das sie das nicht als Text bereit gestellt haben, für mich als Leihen ist es nicht mach bar mich anzumelden.
Fünf mal neu aufgesetzt und ich kann die Anmeldung nicht nach vollziehen. Da bleibt ihr Progamm nur den Profis vorbehalten.
