### ISSUE TITLE
[Help wanted] "Stapler not found"

### ISSUE THREAD

**Issue by crtvrmn** [ciur/papermerge#361]
Hello everyone, 

im quite a total noob when it comes to unix system. Im running portainer/docker on a raspi 4 with 8gb and i created a new stack with 

'---
version: "2.1"
services:
  papermerge:
    image: ghcr.io/linuxserver/papermerge
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./volumes/papermerge/Config:/config
      - ./volumes/papermerge/Data:/data
    ports:
      - 8005:8000
    restart: unless-stopped'

It seemed like my RasPi was lacking a "new" python version, so i came up with

'wget http://ftp.de.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb && sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb'
(look how beautiful i linked the commands with &&, like someone that knows what he is doing).
The python error went away, i was able to log into the webinterface. But OCR is not working, so i looked at the log files again.

The log keeps telling me "PermissionError: [Errno 13] Permission denied: '/root/.local/bin/stapler'". After having a look at the log (extended version on pastebin [https://pastebin.pl/view/6690bdae](url) )
`WARNINGS:

?: Papermerge can't find stapler. Without it, Papermerge won't be able to cut/paste PDF pages.

HINT: Either it's not in your PATH or it's not installed.`

Now im kinda irritated, i thought the stack would "pull" everything it needed? Right now im not really sure what to do, so any pointings into the right direction would be highly appreciated! 

thank you in advance!

**Comment by URBANsUNITED** [comment]
As you'll use the Linuxserver Docker container, the stabler should be here:

BINARY_STAPLER = "/usr/local/bin/stapler"

I doubt:

which stabler in your docker console:

root@e0b33fb76cc4:/# which stapler
/usr/local/bin/stapler
root@e0b33fb76cc4:/# 

Cheers

URBANsUNITED

**Comment by christo-ph** [comment]
Hi,

although stapler is there, in path as you described, papermerge still reports that it is unable to find stapler.

Later it reports 

```
PermissionError: [Errno 13] Permission denied: '/root/.local/bin/stapler'
```

and the server fails to start.

What is expected by papermerge to find stapler properly?

**Comment by guim31** [comment]
I'm facing the exact same issue

**Comment by amo13** [comment]
are the permissions correct? `ls -lah /root/.local/bin/stapler`

**Comment by christo-ph** [comment]
Thats not really the case. There is no folder `/root/.local/bin/`

Papermerge is somehow looking in the wrong place. It should be `/usr/local/bin`

**Comment by amo13** [comment]
I think you can set the PATH to stapler manually in the configuration file. Did you try?

**Comment by christo-ph** [comment]
Thanks to your and @URBANsUNITED post, I found it in the config and the initial error disappears. 

The following errors are due to permission problems with the mounted share. I will check this further

**Comment by crtvrmn** [comment]
So i learned a little bit of linux the last few days. i found stapler with
root@c396486f1713:/# find / stapler | grep -e "stapler" 2>dev/null
/usr/local/bin/stapler
/usr/local/bin/pdf-stapler
/usr/local/lib/python3.8/dist-packages/staplelib/stapler.py
/usr/local/lib/python3.8/dist-packages/staplelib/__pycache__/stapler.cpython-38.pyc
/usr/local/lib/python3.8/dist-packages/stapler-1.0.0.dist-info
/usr/local/lib/python3.8/dist-packages/stapler-1.0.0.dist-info/METADATA
/usr/local/lib/python3.8/dist-packages/stapler-1.0.0.dist-info/INSTALLER
/usr/local/lib/python3.8/dist-packages/stapler-1.0.0.dist-info/WHEEL
/usr/local/lib/python3.8/dist-packages/stapler-1.0.0.dist-info/RECORD
/usr/local/lib/python3.8/dist-packages/stapler-1.0.0.dist-info/LICENSE
/usr/local/lib/python3.8/dist-packages/stapler-1.0.0.dist-info/entry_points.txt
/usr/local/lib/python3.8/dist-packages/mglib/stapler.py
/usr/local/lib/python3.8/dist-packages/mglib/__pycache__/stapler.cpython-38.pyc
find: ‘/proc/313/map_files’: Permission denied
find: ‘/proc/315/map_files’: Permission denied
find: ‘/proc/337/map_files’: Permission denied
find: ‘/proc/3271/map_files’: Permission denied
find: ‘/proc/3272/map_files’: Permission denied
find: ‘stapler’: No such file or directory

and according to https://www.papermerge.com/docs/Installation/settings.html the default path for stapler in the papermerge.conf.py is expected to be BINARY_STAPLER = "/usr/bin/stapler"

Its kinda clear to me, that i either need to edit the papermerge.conf.py but neither vi, vim or nano do work. what am i missing? im using the docker terminal, i guess there is no vi, vim or nano installed?

**Comment by amo13** [comment]
a simple `whereis stapler` would have found the binary too ;)

I never used any docker or container stuff, but if you can't edit the config file, you should take notice of the error message given to you. Why can't you edit it? No editor like nano installed? Or is nano showing you the file but without permission to edit?

**Comment by crtvrmn** [comment]
> No editor like nano installed

this :c

**Comment by crtvrmn** [comment]
Problem with stapler fixed  due to adding the correct path (it got an extra local in there) in the papermerge.conf.py

now i need to fix "DEBUG/ForkPoolWorker-2] Missing page txt /data/media/results/user_1/document_2/pages/page_1.txt." wich seems to be a problem with the DB location, but my initial problem is solved so im closing this one :)
