### ISSUE TITLE
folder creation duplicated

### ISSUE THREAD

**Issue by jjkonway** [ciur/papermerge#373]
highlighting the text to the left closes the box. but will create addition folder as show in the video. 

https://user-images.githubusercontent.com/75956274/116632298-b452ed00-a90b-11eb-90b1-935edda3b8f7.mp4

**Comment by ciur** [comment]
@jjkonway, thanks for reporting this bug!

By the way, if you want to quickly record an animated GIF with "bug step by step" you can use an awesome tool like [peek](https://github.com/phw/peek). 

After you recorded a GIF, you can drag & drop in "text editor" here in github.

Here is an example of animated GIF recorded with above mentioned tool:

![bug-reporting-with-peek](https://user-images.githubusercontent.com/24827601/116808385-b4840000-ab38-11eb-85c4-5b33652705d4.gif)

**Comment by ciur** [comment]
for 2.1.4 this issue is not relevant anymore.
