### ISSUE TITLE
Make selection boxes larger

### ISSUE THREAD

**Issue by koehntopp** [ciur/papermerge#375]
**Is your feature request related to a problem? Please describe.**

When selecting multiple files it is extremely easy to miss the box and thereby un-select everything that was selected before

**Describe the solution you'd like**

Make it less likely to miss the selection box, maybe by multi-selecting by clicking the thumbnail instead of a tick box...?

**Describe alternatives you've considered**

**Additional context**

**Comment by ciur** [comment]
@koehntopp, can you please be more specific on how you select multiple file? 

There are two ways select documents/folders:

1. drag a selection rectangle around the items (similar to desktop file managers)
2. click on selection checkbox on the top left corner

In your description I think you mean to "make top left corner checkbox larger" . But again, I am not sure, this is why I am asking you to be more specific.

Maybe you can use a tool like [Peek](https://github.com/phw/peek) to record an animated GIF to show your point.
Here is an example:

![select-folders](https://user-images.githubusercontent.com/24827601/116808926-c7e49a80-ab3b-11eb-8108-0a7d495ac719.gif)

By the way, thank you for sponsoring Papermerge!

**Comment by koehntopp** [comment]
Hi Eugen,

yes, I did mean the selection checkbox on the upper left corner. And thanks for the pointer to the selection rectabgle, hadn't noticed that.
