### ISSUE TITLE
Question about read only user

### ISSUE THREAD

**Issue by necotec** [ciur/papermerge#381]
Hi Eugen,

at first, you have a very cool project there. I like it ;)
I use Papermerge with your docker-compose.yaml inside the project. I have a question about the users. Is it possible to create a read only user? I have created one, but this user can not see documents from other users. Or can i set the roles anywhere inside a folder? Or can i create a "Public folder"?

If this is not the right place for the question, please delete this issue ;)

Thank you for your great work!

**Info:**
 - OS Linux Mint 20
 - Browser Chromium
-  Database PostgreSQL
 - Papermerge Version 2.0.0

**Comment by necotec** [comment]
![image](https://user-images.githubusercontent.com/64785948/119044480-887ed080-b9ba-11eb-9772-2c9042cc50ad.png)
Found it!
Select folder with the arrow on the left side. Then take a right klick and select access.
This issue can be closed.

**Comment by ciur** [comment]
glad that you figured it out! Sorry for late reply!
