### ISSUE TITLE
Migrate from Docker to Ubuntu (20.04) VM

### ISSUE THREAD

**Issue by necotec** [ciur/papermerge#386]
Hi Eugen,

at the moment, I run Papermerge with your included Docker-Compose file (from your folder in the project). I think, your project is very interesting and I want to use it in future for store all my documents. For that, I have one question and one idea.

For first the question:
- Is it possible to migrate the documents from docker container to a VM with installed Papermerge? The background is, I have stored some documents in my docker instance :)

If that is possible, then here my idea:
- Please add a button for migrate/export/import the data from/to current Papermerge-instance. I think, that makes some things easier ;) 

Thank you

Have a nice Day!

**Comment by ciur** [comment]
Regarding your first question:

> Is it possible to migrate the documents from docker container to a VM with installed Papermerge? The background is, I have stored some documents in my docker instance :)

Yes, it is definitely possible. In general you need to migrate 1. your data directory (called media directory, the place where you files actually live) and 2. your database (sql dump).
For a more general overview of this topic you may have a look at [backup section](https://papermerge.com/docs/Installation/backup.html) in documentation.

**Comment by lucasff** [comment]
@necotec I don't agree so much with the idea of having a full blown VM. It's too much resources for a single application. The docker workflow is essentially a VM for Papermerge only. You can use docker volumes and mount them accordingly so you'll always have it ready to start a container without losing your data, config and state.

**Comment by necotec** [comment]
> @necotec I don't agree so much with the idea of having a full blown VM. It's too much resources for a single application. The docker workflow is essentially a VM for Papermerge only. You can use docker volumes and mount them accordingly so you'll always have it ready to start a container without losing your data, config and state.

Jeah, i develop my new infrastructure at the moment. Docker container in portainer.io are really cool. My idea was only for good support and maintenance for the VMs.
I stay on docker containers ;)
