### ISSUE TITLE
"Tags" are not working

### ISSUE THREAD

**Issue by necotec** [ciur/papermerge#389]
Hi Eugen,

by me, Papermerge is up and running. But I have a little Problem with the Tags. I can create Tags, I can pin Tags, I cas set Tags to a document... but i can not see the Tags on the document. By clicking on a pinned tag there are no documents. Is that issue known? Can't find any solution for this.

I have tested this on Firefox and Chromium.

**Info:**
 - OS: Ubuntu 20.04 LTS on a Proxmox VM (4 Cores 8GB RAM)
 - Browser Firefox and Chromium
 - Papermerge Version 2.0.1

**Comment by ciur** [comment]
Can you please provide a screenshot to clarify your problem? Like for example where you would expect to see a tag and you actually don't see it ?

**Comment by necotec** [comment]
Hi Eugen,
just now, I wanted to make some screenshots... and yes... it's working now. I think, I don't pressed the comma or Enter after selecting a Tag in. I think, that was the problem. 


Sorry for this  issue.
