### ISSUE TITLE
[Docker] Papermerge 1.3.0 Docker image

### ISSUE THREAD

**Issue by anderaith** [ciur/papermerge#39]
Hello, 

I tried your software and it's the one I want to handle my documents (Less complex than Mayan and more user-friendly than Paperless) but I'm unable to make it do what I want in 1.2.3.
I want to add the OCR in French and modify some part of the configuration (Mainly the DB).
I saw that all of that was available in 1.3.0 but my whole infrastructure runs on Docker.
So back to the original question: Would it be possible to get a Papermerge 1.3.0 Docker image ?

Best regards,
P-Y

**Comment by FutureCow** [comment]
He is in the progress of making 1.4.0, with quite some changes. Hopefully a alpha version of 1.4.0 will be released soon on docker.

**Comment by ciur** [comment]
> He is in the progress of making 1.4.0, with quite some changes. Hopefully a alpha version of 1.4.0 will be released soon on docker.

Right! There will be a release candidate (1.4.0.rc1) on first week of August 2020 (+ docker image). Release candidate means - all features are there, documentation updated - but still with naughty bugs :). After additional testing + feedback I will tag/release 1.4.0.
