### ISSUE TITLE
Email importing is not working, how to debug?

### ISSUE THREAD

**Issue by mipmip** [ciur/papermerge#391]
**Description**
Email importing is not working. Can I debug this at code level? I'd like to know if it's a connection problem of a authentication problem.

```
papermerge_worker_1  | ?: Failed to login to IMAP server 'xxxxxx.xxxxx.xxx'
papermerge_worker_1  |  HINT:
papermerge_worker_1  |         Please double check that IMPORT_MAIL_HOST,
papermerge_worker_1  |         IMPORT_MAIL_USER, IMPORT_MAIL_PASS settings
papermerge_worker_1  |         are correct.
```
I double checked configuration by copy and pasting all values in a regular mail client and this works.

**Info:**
 - OS: Docker-compose from project
 - Papermerge Version 2.0 (master)
 - Docker-Mailserver v10(https://github.com/docker-mailserver/docker-mailserver) running dovecot

**Comment by ciur** [comment]
Debugging session in three easy steps:

1. Learn python
2. Run application in development mode[by following this step by step guide](https://papermerge.com/docs/Installation/installation.html).
3. Insert a breakpoint (starting with python 3.7 there is a built-in [breakpoint](https://docs.python.org/3.8/library/functions.html#breakpoint) keyword !)

Happy debugging! :laughing: :rofl: :partying_face: 

You can [use this resource](https://realpython.com/python-debugging-pdb/) to learn how to debug. I don't provide assistance for that.
