### ISSUE TITLE
support Windows, outside of Docker

### ISSUE THREAD

**Issue by mohammed-Emad** [ciur/papermerge#392]
I can support Windows, outside of Docker

**Is your feature request related to a problem? Please describe.**
I had to run the project outside of Docker because it didn't allow me to install a virtual Linux system and then install Docker on it.
I saw some advice here already talking about the possibility of running it inside Docker on Windows, but when I was asked to add a new feature, it was difficult to just add a new page, or just support another engine for OCR, it was difficult. Maybe because I'm not very good at working with Docker,
Instead, the code is somewhat rambunctious, which compelled me to think of working on a simple version that could simply be run from within any editor, just for development purposes.

**Describe the solution you'd like**
working on a simple version that could simply be run from within any editor, just for development purposes, and from any OS

**Describe alternatives you've considered**
Some modifications to libraries such as [MgLib](https://github.com/mohammed-Emad/mglib), for example modifying the way the OCR engine is called within Windows. or "check it out".
Also added conditional loops that inquire about the type of system in order to use the appropriate tools such as those related to pdf such as pdfinfo, and others.
Then we check if Pipeline is working fine after modifications.

**Additional context**
Thanks for your great effort🙂
![Screenshot_849](https://user-images.githubusercontent.com/23532295/123020844-3ecb4080-d3d3-11eb-9770-888823584289.png)

**Comment by ciur** [comment]
Papermerge is server side application. As such it runs on linux/unix flavors (nowadays ubuntu is the most commonly used).
In order to run papermerge on your favorite OS - docker is the way to go.
