### ISSUE TITLE
Default login admin:admin for docker doesnt work

### ISSUE THREAD

**Issue by timowevel1** [ciur/papermerge#401]
Hello,

I deployed papermerge through docker on a completly new server. admin:admin doesnt work for login, it tells me it is wrong. I deployed it on another server, same issue.

You got an idea how I can login anyway?

Thanks

**Comment by julien-vu** [comment]
Just updated the container and can't update at all, maybe it's linked

**Comment by iwconfig** [comment]
Don't know for sure if this is related, but I did some changes to the papermerge config file and this occurred to me as well, after recreating the containers.

I solved it by removing everything with

    docker-compose rm -sv
    docker volume prune

then rebuilt the images before starting the containers by running

    docker-compose up -d --build

and then admin:admin worked as it should again.

**Comment by jasonjenssen** [comment]
Thank you, worked!

**Comment by iwconfig** [comment]
Glad I could help!

Isn't this still considered a bug though? Maybe it's already reported in another open issue but if not I suggest reopening this again.

**Comment by hillbicks** [comment]
Since this issue is still open, let me chime in.

I was also unable to login, but in my case the admin didn't even exist, so the solution was simple. Just run python3 manage.py createsuperuser inside the container.
