### ISSUE TITLE
OCR errors when using chi-sim or chi-sim-vert

### ISSUE THREAD

**Issue by redpixy** [ciur/papermerge#413]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
Using OCR with chi-sim-vert and chi-sim results in errors.

**Expected**
OCR of document containing selected text for the selected language.

**Actual**
Nothing happens. Logs show the following error when executing the command.

> [2021-09-05 10:56:41,109: DEBUG/ForkPoolWorker-2] Run:/usr/bin/tesseract|-l|chi-sim-vert|/data/media/results/user_4/document_27/v5/pages/page_1/50/page-1.jpg|/data/media/results/user_4/document_27/v5/pages/page_1/50/page-1|hocr
 
>[2021-09-05 10:56:41,141: ERROR/ForkPoolWorker-2] returncode=1 stdout= stderr=Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/chi-sim-vert.traineddata
 
>Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
 
>Failed loading language 'chi-sim-vert'
 
>Tesseract couldn't load any languages!
 
>Could not initialize tesseract.

>Check the permissions
/usr/share/tesseract-ocr/4.00/tessdata/
total 22740
-rw-r--r-- 1 root root  4113088 Sep 16  2017 eng.traineddata
-rw-r--r-- 1 root root  1824756 Sep 16  2017 chi_tra_vert.traineddata
-rw-r--r-- 1 root root  1927902 Sep 16  2017 chi_sim_vert.traineddata
-rw-r--r-- 1 root root 10562727 Sep 16  2017 osd.traineddata
-rw-r--r-- 1 root root  2366642 Feb 22  2018 chi_tra.traineddata
-rw-r--r-- 1 root root  2469156 Feb 22  2018 chi_sim.traineddata
-rw-r--r-- 1 root root      572 Mar  4  2020 pdf.ttf
drwxr-xr-x 2 root root     4096 Sep  3 12:12 tessconfigs
drwxr-xr-x 2 root root     4096 Sep  3 12:12 configs

**Info:**
 - OS: [Raspbian GNU/Linux 10 (buster)]
 - Browser [chrome]
-  Database [SQLite]
 - Papermerge Version 2.01 (latest ver.)

**Comment by ciur** [comment]
There is long time of inactivity on this issue. Plus the description is vague.
Closing it.
