### ISSUE TITLE
Easy way to move documents from inbox manually

### ISSUE THREAD

**Issue by Dominik-Koenig** [ciur/papermerge#425]
To collect my documents from various sources I use the mail and the import feature. So most of my documents appear in the Inbox.
As far as I found out, I can either use an automation to move them automatically to the destination folder 
or I can go the hard way:
- mark one
- right click
- cut
- navigate to the destination folder
- paste
- go back to start over with the next document

It would be much more convenient to have a "move-to" box on the right side. Some kind of dropdown list like in "Automate" where you can select the destination direktory and move the file with just one or two clicks.

**Comment by ciur** [comment]
yes, I know that mark, cut, navigate, paste is very tedious. Next release will have dual panel mode and you'll be able to drag'n drop documents/folders/pages from one panel to another. [Here is an early preview](https://youtu.be/sWv6bblWZQQ?t=52) of dual mode feature.

**Comment by ciur** [comment]
In latest release you can use dual panel mode which has exactly what you are asking.
Here is a quick demo of how to move files from Inbox to Home > My Documents folder using dual panel mode:

![easy-move-of-documents](https://user-images.githubusercontent.com/24827601/183253423-9471a9fe-7c21-4910-9327-1df37e499c61.gif)
