### ISSUE TITLE
Documentation of file storage structure

### ISSUE THREAD

**Issue by MinchinWeb** [ciur/papermerge#43]
I can't find any documentation on how the files are stored on disk. Are they in the folders to match the structure should on the webUI?

**Comment by ciur** [comment]
Right! An action item on me.
But, man, the whole thing is pretty simple. If you will see media folder structure, you will understand yourself.

Here is what you can do until I update docs.
[Install dev version from master branch.](https://papermerge.readthedocs.io/en/latest/setup/manual_way.html)
With default setup you don't even need to specify [media](https://papermerge.readthedocs.io/en/latest/settings.html#media-dir) folder, it will be created for you (called `media`, and in same place where file manage.py is).
Start main app and the worker:

```
./manage.py runserver  # main app
./manage.py worker   # worker
```
Upload a couple of documents and check <media>/docs and <media>/results folders.

1.   <media>/docs - original files are uploaded
2.   <media>/results - OCRed files data is stored

In both cases documents data is stored in following format:
```
   <media><docs|results>/user_<user_id>/document_<doc_id>/...
```

**Comment by MinchinWeb** [comment]
I can't get papermerge to upload anything (it errors out) on Windows, because `mglib` is expecting a binary at a linux-style path (which doesn't work in Windows).

The lines in question seem be used to determine the number of pages in the PDF file, which is doable with a Python library. Do you have a preferred library for this? I'd be happy to provide a pull request to solve it.

Also, `pywin32` is required to run the project on Windows. <See https://github.com/ciur/papermerge/pull/45>

**Comment by ciur** [comment]
Yes, because [Papermerge does not support windows platform.](https://papermerge.readthedocs.io/en/latest/requirements.html#requirements)
In case you run Windows OS - you need to use some sort of linux/unix instance - for example use virtualbox with an Ubuntu instance on it.
Another option is to try it via docker.

**Comment by tido-** [comment]
@MinchinWeb ,  I run it on an ARM device with Debian 10 Buster.  If you have such a device I can tell you/I'll update the documentation with required software on a fresh install of Debian/Ubuntu needed. For example: apt show python3 python3-pip python3-venv poppler-utils imagemagick build-essential tesseract-ocr libxml2-dev libxslt1-dev python3-dev zlib1g-dev

**Comment by MinchinWeb** [comment]
@tido- The update to documentation would probably be good in any case.

I tired out papermerge on Docker (on x64), but the OCR wasn't working, and I think I want to customize the storage structure. I was hoping to get it working on Windows so I could actually hack on it myself, and fix these random bugs (which is much easier to do locally, rather than remotely and on Docker...; Docker is great for deploying but sometimes painful for iterating on code). At this point, I'm waiting to see what the v1.4 release brings; the file structure I'm hoping for would require a bit for metadata be stored about each document, which I think was on the roadmap for v1.4.

**Comment by ciur** [comment]
Hi @MinchinWeb,

I still have your request in mind. I was busy these days with other parts of the project. Now that I have more time, I will document how papermerge stores documents on the disk. 
Allow me one more day.

**Comment by ciur** [comment]
Hi @MinchinWeb,

here is [Storage Structure documentation](https://papermerge.readthedocs.io/en/latest/developers_guide/storage_structure.html)

**Comment by MinchinWeb** [comment]
@ciur Thanks for doing this; I appreciate it!
