### ISSUE TITLE
Version 2.1 Development Updates

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#435]
Hello ladies and gentlemen,

Papermerge 2.1 development is at full speed. I am very pleased to announce that new changes look good enough for a public demo.

Here is a [screencast on youtube](https://www.youtube.com/watch?v=rh6p48W4wXk) which demos the progress so far.

Following features presented in above screencast are:
1. Dual panel mode + drag and drop of the documents
2. Skip OCR for specific documents
3. Download document with OCRed text overlay
4. Modern reactive desktop-like user experience

It will take me another three maybe four months until first beta.

**Comment by Marvo2011** [comment]
Hello,

can we get a beta version?

**Comment by ciur** [comment]
@Marvo2011 There is no beta version yet.
There is an early alpha
I updated online documentation with instruction on how to [start latest alpha release with portainer](https://docs.papermerge.io/Installation/portainer.html#).
If you are more docker-compose guy, here is similar instructions on how to [start latest alpha release with docker-compose](https://docs.papermerge.io/Installation/docker.html).

Papermerge is has now fully REST API - which basically means backend server works with REST API and has no UI. The fancy user interface is just another REST API client (but really, really shiny one).

Here is online documentation reference for REST API with [swagger ui](https://docs.papermerge.io/swagger-ui/) and as [rdoc ui](https://docs.papermerge.io/redoc/).

Next days a series of demo screencasts with latest features (and their bugs :) ) will follow.
