### ISSUE TITLE
.. button to navigate to parent directory

### ISSUE THREAD

**Issue by ajarzyn** [ciur/papermerge#437]
**Description**
No easy way to navigate to parent directory.
I understand that it's possible to select directory on the directory path, but you have to aim for one you are interested in.

**Describe the solution you'd like**
Add `..` button to allow linux like navigation

**Describe alternatives you've considered**
Add arrow up [semething like this](https://www.google.com/search?q=parent+directory+icon&client=ubuntu&hs=4XL&channel=fs&sxsrf=AOaemvLdYpaINdqkIdEgpzQ4gS3r5jt49Q:1639605925501&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjo8IqG6Ob0AhXkpYsKHXmXAskQ_AUoAXoECAEQAw&biw=1920&bih=995&dpr=1) to have like Windows navigation

**Comment by ciur** [comment]
Feature is available in [2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35) i.e. in latest alpha release (which is relatively stable).

Here is a demo in (single panel mode):
![deeply-nested-folders](https://user-images.githubusercontent.com/24827601/182027071-954a7c3c-901e-4b78-9be0-eafcbcca0815.gif)


and in case of dual panel mode:
![deeply-nested-folder-dual-panel-mode](https://user-images.githubusercontent.com/24827601/182027199-4084e8a1-8560-47a3-b8e6-e8e243e3755d.gif)
