### ISSUE TITLE
Store Data On MariaDB

### ISSUE THREAD

**Issue by necotec** [ciur/papermerge#438]
Hey ho,

a little question. Is it possible to store the Papermerges data in a MariaDB in the network? It can/should help me with my documents in my infrastructure :)

Thank you

**Comment by RefineryX** [comment]
Yes it can, I just did it today. As per the documentation, you need to edit ``settings.py`` file. Uncomment the following and enter your info

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db name',
        'USER': 'your user',
        'PASSWORD': 'your pass',
        'HOST': 'mariadb',
        'PORT': 3306,
```

**Comment by necotec** [comment]
Wow, thank you 👍

I test it 😊
