### ISSUE TITLE
Feat Req: Auto select first item

### ISSUE THREAD

**Issue by YouveGotMeowxy** [ciur/papermerge#443]
When viewing an image, if you just click "view ocr'd text" you'll get the message saying something along the lines of "select a thumbnail first"; it would save some clicks and frustration if PM auto-selected the first item in the thumbnail list (which often is just 1 in my case anyway) when viewing the item.

This way if it's only 1 item, user won't' have to fist click it; if more than one item, user would have to click a thumb anyway, so if they don't want the 1st one, they can just click whichever else; but if they still wanted the first thumb, it's already selected for them.

**Comment by ciur** [comment]
No need to select "first page". By default it will retrieve OCRed text of the whole document.

![get-ocred-text](https://user-images.githubusercontent.com/24827601/187017517-4e28eba8-d4ed-4ab5-b2c6-cf2b51649072.gif)

feature was added by following commits:

[backend](https://github.com/papermerge/papermerge-core/commit/2e870abf659bd1f155f7f6b088d0ffae1bdb9b51)
[frontend](https://github.com/papermerge/papermerge.js/commit/b83825b2cdba76e9d77d17da40c6fe2b2b58f41b)
