### ISSUE TITLE
Feat Req: Add Button to get OCR's Text

### ISSUE THREAD

**Issue by YouveGotMeowxy** [ciur/papermerge#444]
Would love if a button was just added to the screen when viewing an item, to get the ocr'd text. Then it would save a couple of clicks (instead of always having to first right-click the item, then click the view ocr menu item). I'm all about ease of use and save clicks. :)

Mock up (ignore the drop down arrow on the button, I just forgot to remove it in the mock up):

![image](https://user-images.githubusercontent.com/39491297/148081407-ce1775ff-d64e-4d01-86fb-d4a8396a8aeb.png)

**Comment by ciur** [comment]
You can now get OCRed text from contextual menu of the commander or view:

![get-ocred-text](https://user-images.githubusercontent.com/24827601/187017430-97a4edce-301d-4187-8941-f47aa9bcd264.gif)

feature was added by following commits:

[backend](https://github.com/papermerge/papermerge-core/commit/2e870abf659bd1f155f7f6b088d0ffae1bdb9b51)
[frontend](https://github.com/papermerge/papermerge.js/commit/b83825b2cdba76e9d77d17da40c6fe2b2b58f41b)
