### ISSUE TITLE
Feat. Req: Allow Pasting image from clipboard & drag and drop to upload

### ISSUE THREAD

**Issue by YouveGotMeowxy** [ciur/papermerge#445]
Like many image hosts these days (along with many other types of services and apps), not only are you able to manually browse for an image to upload, but you can simply paste an image from your clipboard and it'll upload it. You can usually just drag and drop onto the upload box to upload as well.

Only offering manual navigating and selecting is somewhat archaic in 2022. :D

Example from imgur:

![image](https://user-images.githubusercontent.com/39491297/148082202-2f035cfc-d5e9-4e11-a1c6-c21312a8c200.png)

**Comment by ciur** [comment]
Actually drag'n drop works. Here is a quick demo based on [lastest 2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35) docker image.

[drag-n-drop-demo.webm](https://user-images.githubusercontent.com/24827601/182029192-b56a128d-b4de-452c-872d-16febf6b17cc.webm)

When dragging over an area where documents can be dropped - a green border highlights the "dropping area".
