### ISSUE TITLE
Rotation of the images and possible slicing?

### ISSUE THREAD

**Issue by FinlandApollo** [ciur/papermerge#446]
Hello! 

I'd like to thank you for this nice piece of software that you have created. I'd think that one thing that is missing that I'd greatly appreciate, would be rotation of images and PDF files. Some of Canon scanners have forced auto-rotation which you probably already have guessed: Doesn't really work 100% well in the end. In order to make it plug and play and automated system, it would be great that there would be a tool that could rotate these wrongly orientated pages and then run OCR if desired. Currently, OCR gives from these incorrectly orientated pages total gibberish, which is pretty much useless.

Thank you and be safe!
FinlandApollo

**Comment by ciur** [comment]
@FinlandApollo, thank you for opening this issue.
I don't promise anything about slicing, but page rotations is definitely coming in next version.

**Comment by ciur** [comment]
Page rotation was implemented. Here is a quick demo:
![rotation](https://user-images.githubusercontent.com/24827601/183254840-e54f845c-b15b-4fa5-ae70-e1365146eb4e.gif)
