### ISSUE TITLE
Modify Creation Date / Document Date

### ISSUE THREAD

**Issue by michaelkrieger** [ciur/papermerge#448]
**Is your feature request related to a problem? Please describe.**
Currently there are two non-modifiable dates: Document Creation and Document Modification.
Both are not likely meaningful in most circumstances, but the **Document Date** would be.

**Describe the solution you'd like**
Yes, this could be solved with additional Metadata, it seems like updating the creation date makes more sense as then the 'sort by date' would work with the document date (ie: the credit card bill date, the pay stub date, etc) instead of an arbitrary creation time that just tells me when I scanned it into PaperMerge.

**Describe alternatives you've considered**

**Additional context**

**Comment by ciur** [comment]
Feature avaiable with 3.3 via custom fields. Just create a custom field of type date and name it : "Document Date"
