### ISSUE TITLE
Cut/Paste Not Working as Expected

### ISSUE THREAD

**Issue by typkrft** [ciur/papermerge#451]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
Cut Paste not working as expected
I opened this on Linuxserver initially, but the same behavior persists using the supplied compose from here. I am probably doing something wrong, but some guidance would be appreciated. I have made no changes to the papermerge.conf.py.

**Expected**
1. Upload Document A (10 Pages)
2. Select pages 1-3
3. Right Click on selected pages > Cut
4. Navigate to File Browser
5. Right Click Empty Space > Paste Pages
6. Reload Page (Per Papermerge Docs) so file shows up 
7. File Shows Up As Expected
8. Open Document A again
9. Select Pages 4-6
10.  Right Click on selected pages > Cut
11. Navigate to File Browser
12. Right Click Empty Space > Paste Pages
13. Reload Page (Per Papermerge Docs) so file shows up 
14. **Pasted Document of Pages 4-6 appears**

**Actual**
1. Upload Document A (10 Pages)
2. Select pages 1-3
3. Right Click on selected pages > Cut
4. Navigate to File Browser
5. Right Click Empty Space > Paste Pages
6. Reload Page (Per Papermerge Docs) so file shows up 
7. File Shows Up As Expected
8. Open Document A again
9. Select Pages 4-6
10.  Right Click on selected pages > Cut
11. Navigate to File Browser
12. Right Click Empty Space > Paste Pages
13. Reload Page (Per Papermerge Docs) so file shows up 
14. **Original Selection 1-3 Shows Not 4-6**

**Info:**
 - OS: Ubuntu 20.04
 - Browser Firefox 97.0b2
-  Database Postgres 12.3
- Papermerge Version 2.0.0

**Comment by ciur** [comment]
Thank you for your time and detailed report of the issue.

**Comment by typkrft** [comment]
Of course. Thank you for the wonderful software!

**Comment by ciur** [comment]
Latest version of Papermerge - 2.1.0a37 features [dual panel mode](https://docs.papermerge.io/User%27s%20Manual/user_interface.html#dual-panel-mode) which significantly improve user experience when moving pages around.

Here is a quick demo of how to extract pages 1-3 and then 4-6 into separate document:

![extracting-pages](https://user-images.githubusercontent.com/24827601/183240007-853162cf-2fec-4936-9998-6caff4dbbc1c.gif)
