### ISSUE TITLE
Add more roles to admin user

### ISSUE THREAD

**Issue by bklutse20** [ciur/papermerge#452]
After running the papermerge docker image, I noticed the admin user doesn't have enough privileges. Eg: I am unable to add folder, add users, etc. Can someone help me fix this?

**Comment by Northguy** [comment]
Just wondering what your issue is. Which docker image are you referring to? I just installed the [Linuxserver image ](https://github.com/linuxserver/docker-papermerge) and I am perfectly able to add users as admin user.

**Comment by bklutse20** [comment]
Hi @Northguy,

Thanks for the response. Let me try with the above link and get back. I really appreciate your response.

**Comment by ciur** [comment]
Cannot reproduce ticket.
Tested against latest [2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35) docker image.
