### ISSUE TITLE
make data revision-safe

### ISSUE THREAD

**Issue by cfoellmann** [ciur/papermerge#465]
For us the archival of our scanned and pdf-received incoming mail needs to be protected from change without the possibility for manipulate "anything".
Is there any function or interface in papermerge?

I am looking at putting all the files in git and commit everything once a day.
Or sign all documents with a documente signage cert but that might create a lot of data. not sure yet what the signature puts on the filesize.

Anyone running a business documents archive? Revision-safe? In Germany/For a German company?

**Comment by ciur** [comment]
I am not sure I understand the feature request.

Can you please be specific on what you mean by "without the possibility for manipulate -anything-" ?

**Comment by cfoellmann** [comment]
i just saw that you are from Germany, too.
As you might know there is GoBD in Germany which is regulatory groundwork describing how businesses have to archieve and save business critical documents of various degrees.
This is not law so it is vague and a real pain.
It gives you the freedom to save and archive documents in a proper way without giving you standards on how to achieve the degree that is needed. And  without saying what that degree is.
Until you need that document in a law suite or for the IRS.

I want to achieve peace of mind by scanning anything and everything and archiving in a way that can not be altered.
I am thinking about
- document signage with a cert from the Bundesdruckerei
- putting all (signed) documents into Git
- signing all docs with GPG

**Comment by ciur** [comment]
First of all you cannot change "content of the page" because pages are "scans".
Secondly, everytime you perform a change (means add new page, or merge newer version of the scan), the version of the document is incremented i.e. your previous version stays intact.
The most important of all - is that original version i.e. you upload - is always available.

This has a slight overlap with papermerge/papermerge-core#16

**Comment by cfoellmann** [comment]
Thanks for the reference!
