### ISSUE TITLE
Get 404 page not found

### ISSUE THREAD

**Issue by cleverbobo** [ciur/papermerge#467]
I installed the docker / docker-compose version. I used these instructions:
https://docs.papermerge.io/Installation/docker.html

When connecting to the main page I only get: 404 page not found

I am able to access the Traefik site though: http://ip:8080/

The service is deployed on my cloud service, and I use IP address to access it.

Did I miss something?

**Comment by ciur** [comment]
> Did I miss something?

Yes, you missed a lot of things. First of all, I don't see any traefik mentioned in the https://docs.papermerge.io/Installation/docker.html

Secondly, if you used specific docker compose file, and you want us to help you, please paste here docker compose you used. 

Also, note that traefik configuration for request routing, specific cloud service provider configurations on how to route external http request to the application is outside the scope.
[Docker compose|https://github.com/papermerge/papermerge-core/blob/master/docker/docker-compose.yml|] shipped in papermerge repository is not meant to be used in cloud service providers (production environments).

Lastly, please paste here all logs files (docker logs or docker-compose logs, whichever is relevant for your case)

**Comment by ciur** [comment]
time out
