### ISSUE TITLE
Papermerge behind Nginx Proxy Manager not working

### ISSUE THREAD

**Issue by SamTV12345** [ciur/papermerge#472]
**Description**
Deploy papermerge to be available outside of the internal network via reverse proxy

**Expected**
Access via ssl and DNS record papermerge.

**Actual**
Cannot login to the system.

Try 1: Use the complete stack: https://docs.papermerge.io/Installation/docker-compose.html#complete-stack I tried to use the complete stack, all services were also available but as soon as I got to the login screen and typed in username and password the page reloaded and nothing happened. I didn't got an error message compared to entering wrong username or password. When I checked the logs I got a 403 for the api path.

Try 2: Use this https://github.com/ciur/papermerge/blob/master/docker/docker-compose.yml . I can login via internal IP, via DNS it says POST https://<my-domain>/api/auth/login/ 404 with this message:

![image](https://user-images.githubusercontent.com/40429738/185803319-6bbf006e-4a3a-4ae4-bd79-cfe7af839dba.png)

**Info:**
 - OS:  Proxmox LXC running 22.0.4
 - Browser Microsoft edge
-  Database PostgresSQL: 12.3
 - Papermerge Version: latest/2.0.0

**Comment by ciur** [comment]
@SamTV12345 

> Deploy papermerge to be available outside of the internal network via reverse proxy

The above mentioned docker compose is not meant to be deployed "outside internal network via reverse proxy"

> Access via ssl and DNS record papermerge.

Again, SSL (TLS) and DNS settings are outside the scope of above mentioned docker-compose

**Comment by SamTV12345** [comment]
So even the full stack is not ready for being deployed with a reverse proxy?

**Comment by ciur** [comment]
Maybe it is.
I've just never done it with docker compose. Provided docker compose is for local setup - never was meant to be accessed over the network.

Maybe you want to wait couple of weeks as I will be releasing a series of videos "Papermerge for DevOps" in which I will describe and detail different deployment scenarios.

**Comment by SamTV12345** [comment]
Ah I see. I was wondering why you should edit the /etc/hosts file. Now I understand your aim. Looking forward to your video series.
