### ISSUE TITLE
Import Dir configuration in 2.1.1

### ISSUE THREAD

**Issue by olli0815** [ciur/papermerge#495]
**Is your feature request related to a problem? Please describe.**
I would like to configure an importer dir like in 2.0 also in 2.1.

**Describe the solution you'd like**
option to set an importing folder in env. or config

**Describe alternatives you've considered**

**Additional context**

**Comment by ciur** [comment]
I am currently working on "importing part" of 2.1 the whole thing will be ready (i.e. with documentation) in couple of weeks.

It works (again, work in progress) as follows as described below.
Say you have Papermerge DMS 2.1 running on http://papermege.local.

1. Install[ papermerge-cli ](https://github.com/papermerge/papermerge-cli) client with:
   
    $ pip install papermerge-cli

2. set `PAPERMERGE_CLI__HOST` environment variable:
  
   $ export PAPERMERGE_CLI__HOST=http://papermege.local

4. Get REST API Token with:
  
    $ papermerge-cli auth  # you will be asked username/password

Also you can get REST API token from the UI client in User Menu -> REST API Token

5. set `PAPERMERGE_CLI__TOKEN` environment variable:
 
    $ export PAPERMERGE_CLI__TOKEN=mytoken

OK, now you are ready to import. Use import comment:

    $ papermerge-cli import /path/to/folder 

Import command will upload recursively all documents (and folders... folder structure will be preserved) to your Papermerge DMS 2.1 instance.

Note that [papermerge-cli](https://github.com/papermerge/papermerge-cli) works only with 2.1

Again, all described above is not yet documented and client has still many bugs - as I mentioned at the beginning it is work in progress.

**Comment by olli0815** [comment]
No matching distribution found for papermerge-cli:
```
root@PaperMerge:~# pip -V
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
```
```
root@PaperMerge:~# pip install papermerge-cli
ERROR: Could not find a version that satisfies the requirement papermerge-cli
ERROR: No matching distribution found for papermerge-cli
```

**Comment by ciur** [comment]
> No matching distribution found for

What python version you have (python --version) ?

Sounds like you have python, but the version is wrong. You need [python version 3.10.x(https://github.com/papermerge/papermerge-cli/blob/0351d798845ec399481daaaeebed37df1fcd4e05/pyproject.toml#L10).

I guess python version is too strict - I will relax that.

**Comment by olli0815** [comment]
ja, using debian 11 is always trouble with python versions...
need to set up proper environment first, using pycharm with proper python and environment...

**Comment by olli0815** [comment]
coool ! 
works at least from my Win-laptop in virtual environment.
But it lands in home folder not in the Import-Directory
 - OCR will be triggered 
 - works fine (w/o any duplication)

so need to adjust my old scanner-grabber script to to use the cli. Far better as using mounts..
