### ISSUE TITLE
Files with "&" w/ filename will be ignored by GUI-Import 

### ISSUE THREAD

**Issue by olli0815** [ciur/papermerge#496]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
If a filename contains any "&" the file won't be imported 

**Expected**
import or error message in GUI

**Info:**
 - Papermerge Version FE 2.1.0b12

**Comment by ciur** [comment]
What happens here is that backend returns an error with message:

`{"errors":[{"detail":"Enter only safe characters.","status":"400","source":{"pointer":"/data/attributes/title"},"code":"invalid"}]}`

Which is correct - as the backend is not allowed to upload files which contains "&".
However,  the frontend (i.e. GUI) does not show the error to user :(.

I see two problems here actually:
1. It should be documented what are allowed files names (valid file names)
2. The GUI should report the problem i.e. show why files was not uploaded

**Comment by ciur** [comment]
Following pull requests handles also the invalid characters set error messages i.e. when user uploads a document
with title containing one of the invalid set characters - it will display an error message:

https://github.com/papermerge/papermerge.js/pull/35/files

**Comment by ciur** [comment]
![invalid character set error message](https://user-images.githubusercontent.com/24827601/209424002-99b2323c-d328-45a4-ae00-01df3942b2ef.png)
