### ISSUE TITLE
Add User Error!

### ISSUE THREAD

**Issue by Timothy13Munyao** [ciur/papermerge#50]
Request Method: | GET
-- | --
http://0.0.0.0:8000/admin/core/user/add/
3.0.2
NoReverseMatch
Reverse for 'auth_user_changelist' not found. 'auth_user_changelist' is not a valid view function or pattern name.
/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py in _reverse_with_prefix, line 677
/usr/bin/python3
3.7.5
['/opt/papermerge',  '/opt/papermerge',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/usr/lib/python3/dist-packages']
Fri, 24 Jul 2020 07:36:55 +0000

[NoReverseMatch at _admin_core_user_add_.pdf](https://github.com/ciur/papermerge/files/4970660/NoReverseMatch.at._admin_core_user_add_.pdf)

**Comment by ciur** [comment]
This error is fixed in version 1.4.0 which will be available in aprox. 2 weeks (together with new docker image).
I won't fix this bug in 1.2.3  (version provided by latest docker image).

When 1.4.0 is out, I will provide detailed instructions how to migrate from 1.2 to 1.4.
