### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by brettowe** [ciur/papermerge#511]
**Description**
I was looking at the issue https://github.com/linuxserver/docker-papermerge/issues/42 and trying to figure out how to fix the problem and I see that the dockerfile is needing the requirements file to cover modules needed.
looking at the requirements files in this repo I don't see PikePDF or OCRmyPDF listed.
is there any reason for them to be left out?

**Comment by ciur** [comment]
I think there is a misunderstanding here.
My guess is that linuxserver docker image is only for Papermerge DMS 2.0.
While the above mentioned ticket: https://github.com/linuxserver/docker-papermerge/issues/42
(I guess) tries to use a feature which is in Papermerge DMS 2.1, at very least [this link](https://docs.papermerge.io/User%27s%20Manual/page_management.html#move-document-to-document) which is referenced in the linuxserver issue from above, describes a feature which did no exist in 2.0.

My very first question would be - does linuxserver provides image for 2.1 as well ?

**Comment by brettowe** [comment]
that would explain the problem then. I guess it's time to find a new docker image to use then.
thanks
