### ISSUE TITLE
Full Restore Backup

### ISSUE THREAD

**Issue by PicklesIIDX** [ciur/papermerge#524]
How can I perform a full backup of papermerge (accounts, documents, tags, metadata) and restore it?

I tried figuring this out but hit a dead end. I saw in the docs that the backup utility (https://docs.papermerge.io/Installation/backup.html#backup-utility) does not backup metadata and tags. So I attempted to backup the directories wholesale. I'm using docker so I backed up each volume. Then I simulated a catastrophic failure by setting up a whole new installation of papermerge. I restored the volumes by copying the contents to the new volumes. While the copy completed successfully, the documents were not visible in the new instance. I dug into the media directory and saw that documents are stored by user GUID. I tried to just rename those directories to match the GUID of the user created for the new instance, but it still did not work.

I do see some issues (https://github.com/ciur/papermerge/issues/508, https://github.com/ciur/papermerge/issues/519) that describe backup and restore work, but it's unclear if this will support my use case (e.g. tags). 

- What's currently supported for backup functionality?
- What's currently planned?
- Was I close with my attempt? Is there something I can do manually to restore my instance?

**Comment by ciur** [comment]
Which version you have in mind? 2.0 or 2.1?

**Comment by PicklesIIDX** [comment]
I'm good either way. I'm still evaluating papermerge and haven't committed.

**Comment by ciur** [comment]
Backup/Restore is documented here: https://docs.papermerge.io/3.0/backup-restore/
