### ISSUE TITLE
Installation on Unraid

### ISSUE THREAD

**Issue by celerohop** [ciur/papermerge#532]
Linuxserver template (as mentioned in #93) has been deprecated.
Would it be possible to create an official Community applications template for Unraid?

**Comment by z1R** [comment]
Second that!

**Comment by ciur** [comment]
I guess, it is possible. Why would it be impossible?
Feel free and create one! :heart:

**Comment by z1R** [comment]
My post was more as being excited rather than demanding, sorry if it came out that way. 

I wish I had the knowledge to do it myself :)
