### ISSUE TITLE
Ability To Change Items Per Page

### ISSUE THREAD

**Issue by drtechnofreak** [ciur/papermerge#540]
Hi Ciur,

It would be a massive feature for the end user or config side to amend amount of items per page.

Either UI or CLI Side would be fine for me & i'm sure others out there would support this idea

Cheers

**Comment by ciur** [comment]
Feature is available in 3.0: https://papermerge.github.io/documentation/3.0-dev/setup/docker-compose/

![items-per-page-in-pagination](https://github.com/ciur/papermerge/assets/24827601/00e9980a-b8cd-45a7-887a-3a7ba44e27fc)
