### ISSUE TITLE
jpeg documents cannot be downloaded

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#55]
found this issue while testing jpeg.
I will provide a fix as soon as possible.

**Comment by Aruscha** [comment]
I have a syntax error in the latest version when starting the docker container

![Screenshot_20200805-083456859.jpg](https://user-images.githubusercontent.com/49562390/89379704-8df27f00-d6f6-11ea-8b15-f3ac9c1c6327.jpg)

**Comment by ciur** [comment]
Maybe you have /etc/papermerge.conf.py from previous installation?
Application looks for papermerge.conf.py in:

* current folder
* /etc/papermerge.conf.py

Another thing. Can you please make sure it uses (1 hour fresh) 1.4.0.rc2 tagged image ?

**Comment by Aruscha** [comment]
It's definitely r2 in use and the config is definitely new, like I said I downloaded and started your project
And there are definitely no more old packages

**Comment by ciur** [comment]
oh, man, then your scenario is really tricky (I would even use word - mysterious :ghost:  ). 
Can you please describe in detail the whole thing ?

1. what docker version you use
2. docker-compose version
3. operating system
4. what locale you use
5. steps you followed a. clone repo b. cd docker/1.4/ c. docker-compose up

**Comment by Aruscha** [comment]
Ich schreib dir mal auf deutsch da mein englisch da zu ende ist :D

Also genutzt wird docker 19.03.12 auf Centos8 bisher ging auch alles habe mir nun dein Projekt wieder geclont, dann cd docker/1.4
docker-compose up.

Jou dann kam eben der Syntax Fehler :D

Ich installiere mir das gleich nochmal auf dem Laptop wenn ich das hinbekomme zum testen.

**Comment by ciur** [comment]
Also, wir machen folgendes:

1. ich schließe diesen bug,  weil hier (in diesem Bug, meine ich) um "jpeg documents cannot be downloaded" geht
2. wenn dein Syntax Fehler noch da ist, dann, bitte, öffne einen neun bug und ich kümmere mich darum.
  
Danke vielmals für den Feedback!

**Comment by ciur** [comment]
Download issue was not jpeg related - it was because of access permission problem.
[Now it is solved.](https://github.com/ciur/papermerge/commit/1a73dc7c212b2b42943ed343bc7edb26db35b9c2) Will be part of 1.4.0.rc3.
