### ISSUE TITLE
Automates is not available

### ISSUE THREAD

**Issue by NerdRelaxo** [ciur/papermerge#551]
**Description**
I installed Papermerge on my Synology DS1522+ with Portainer and from your repo with your docker_compose.yaml. The "Automates" Menu item is missing.

**Expected**
That Automates is available in the menu

**Actual**
It's not there.

**Info:**
 - OS: DSM 7.2-64570 Update 1 (Client macOS Ventura)
 - Browser Safari
-  Database [PostgreSQL 14.4]
 - Papermerge Version [2.1.9]

**Comment by w4tzmann** [comment]
Papermerge 2.1.X has no Automates for the moment, as you can see in the comparison table:  https://github.com/ciur/papermerge (scroll down to the bottom of the page).

**Comment by ciur** [comment]
Automates feature is not available 3.0 either.
