### ISSUE TITLE
Drag and drop between two panels doesn't work

### ISSUE THREAD

**Issue by kovaacs** [ciur/papermerge#553]
**In case you experience issues with docker image provided by [linuxserver.io/papermerge, please open bug report in their repository.](https://github.com/linuxserver/docker-papermerge/issues)**

**Description**
Drag and drop between panels doesn't work.

**Expected**
I'm trying to reproduce [this behaviour](https://github.com/ciur/papermerge/issues/109#issuecomment-1200434767), but I'm unable.

**Actual**
Nothing.

https://github.com/ciur/papermerge/assets/20384210/c3b2732e-2c12-400f-828f-6c2dccda2efd

**Info:**
 - OS: macOS 13.5.1
 - Browser Chrome 116.0.5845.140, Firefox 117.0 
-  Database postgres:14.4
 - Papermerge Version 2.1.9

**Comment by ciur** [comment]
Thank you for well structured bug report!

**Comment by ciur** [comment]
Maybe you give a try to version 3?

- via docker: https://papermerge.github.io/documentation/3.0-dev/setup/docker/
- via docker compose: https://papermerge.github.io/documentation/3.0-dev/setup/docker-compose/
- or ansible: https://papermerge.github.io/documentation/3.0-dev/setup/ansible/

I will officially release version 3.0 it in a month or so.

**Comment by ciur** [comment]
I am closing this ticket as version 3.0 was released, which renders this ticket obsolete.
