### ISSUE TITLE
Docker, Error loading MySQLdb module: Did you install mysqlclient?

### ISSUE THREAD

**Issue by philiplb** [ciur/papermerge#555]
**Description**
When starting a container with the image `papermerge/papermerge:2.1.9` with `PAPERMERGE__DATABASE__TYPE=mysql`, I get the following error (due to a missing dependency in the image?):
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?

**Expected**
Papermerge launches.

**Actual**
Papermerge crashes with the above mentioned exception

**Info:**
 - OS: Docker
 - Browser -
-  Database MySQL
 - Papermerge Version 2.1.9

**Comment by ciur** [comment]
Please try version 3.0, as it supports mysql: https://docs.papermerge.io/3.0/setup/docker-compose/
You'll need to use [database url](https://docs.papermerge.io/3.0/settings/database/#database__url) with mysql scheme.

**Comment by philiplb** [comment]
Thank you very much! Unfortunately I settled.with a different system. But will try this eventually.
