### ISSUE TITLE
Share your personal setup?

### ISSUE THREAD

**Issue by smichaelsen** [ciur/papermerge#561]
@ciur Would you mind sharing your **personal** setup? I consider throwing away everything I have regarding document management (apart from the files of course, I'll need to migrate them) and start from scratch. I might as well take inspiration from others then. So, if you feel comfortable sharing some or all of this information, I'd appreciate it very much.

* Where do you run papermerge (locally in your home, some cloud server, ..)?
* What hardware runs your papermerge (CPU, RAM)?
* What scanner(s) do you use?
* How are your scans transferred into your inbox?
* Do you sometimes "scan" documents with your phone?
* If yes, how are they transferred into your inbox?
* What else is essential to your personal setup that I forgot to ask?

**Comment by ciur** [comment]
My Papermerge instance runs in my "home lab",  on old Dell computer with i5 CPU and 8 GB of RAM. 
On that machines runs Ubuntu 22.04.
For installing/backup/restore of data I use these ansible playbooks: https://github.com/papermerge/ansible
Regarding scanner, I have Brother ADS 2800W.
I usually scan my docs/receipts once a week. I just feed the whole batch in the scanner; the scanner saves all scanned docs on USB stick as one single PDF file, which I manually move to my laptop, where, again manually, upload scanned docs (as one PDF file) to my paper instance. Then I spend some time moving around individual pages/docs into separate folders.

Off topic: I checked now on amazon, and the price of above mentioned scanner is twice as it was back in 2019 when I bought it!
