### ISSUE TITLE
Enhancements for backup and restore

### ISSUE THREAD

**Issue by Tooa** [ciur/papermerge#58]
Hi :wave:, 

thanks for implementing the backup and restore feature @frenos :+1:. 

I would like to propose additional user-centered stories here on how I would like to further shape this feature. Let me know what you think.

**Given** an offsite backup strategy via `rclone` to `backblaze`
**And** incurred costs for each uploaded byte to the service
**As a User**, I want to perform incremental offsite backups from my `papermerge` instance
**so that** I do not have to upload the complete and huge backup `*.tar` file to the service for every new `papermerge` backup which would increase my costs for the offsite backup service

**Given** the media root folder as a **host mount** in my docker installation rather than a volume ([reference](https://github.com/ciur/papermerge/blob/master/docker/1.4/docker-compose.yml#L14))
**And** the host mount is already included in my own `rsync` backup strategy
**As a User**, I want to export/backup only the `backup.json` file from `papermerge`
**so that** I only need to add the `backup.json` to my existing `rsync` backup strategy

**Comment by ciur** [comment]
Enhacements to backup/restore feature will be added as part of v1.5.0 release.

**Comment by Tooa** [comment]
Closing this issue as it is not relevant to me anymore.
