### ISSUE TITLE
OCR saying "unsupported format" for PDF and JPG file

### ISSUE THREAD

**Issue by Chavell3** [ciur/papermerge#587]
Hi Team,

after a bunch on tries I could now successfully set up Papermerge.
So by the looks of it, all connections are working between each of the instances... but when I upload a file and try to run OCR manually it fails.
Within the logs of the Worker node I see a message of "unsupported format" and it can be a PDF or JPG file which both are supported.

But by the documentation, PDF and also JPG file should work.

[docker compose.txt](https://github.com/ciur/papermerge/files/14110455/docker.compose.txt)
[PM_worker_log.txt](https://github.com/ciur/papermerge/files/14110456/PM_worker_log.txt)

Any idea what I could change to make it work?

**Info:**
 - Papermerge Version 3.0.2
 - Deployment with SOLR Search-Server
 - Docker compose used to deploy
 - All other services like redis, solr, webserver and DB do not report any error.
 

Thanks!

**Comment by Chavell3** [comment]
also interesting if I try to manually run the OCR detection there is no logging about a new task on the worker node... I would have expected to get a new task...

**Comment by ciur** [comment]
Does it happen for all PDF, JPG images you've tried? Or only for some of them? Would you mind attaching one problematic file one pdf and one jpg)?

**Comment by thndrbck** [comment]
Check to see if the file uploaded completely. Also check to see that the file is actually pdf or jpg. I had one file rejected because it had the wrong extension (three letters after the dot in the file name), and a few that didn't completely upload when I tried uploading 30 at a time.

**Comment by Chavell3** [comment]
I don't think it's a matter of a specific file, I now uploaded like 6 additional files(PDF's and JPEG's) non of them is scanned...
Any idea what I could do to additionally troubleshoot that?

small side note although I entered the volumes for media and database... those folder still stay empty...
I added some pictures.
If you still like to have some files, just give me shout... but I don't think it's file related...

![msedge_01312024_212907](https://github.com/ciur/papermerge/assets/56268217/aaf26078-477a-4a37-acf0-ff298d7e9d26)

![putty_01312024_212823](https://github.com/ciur/papermerge/assets/56268217/5c4ecd5e-3e60-4624-a106-863fed4f6acf)

Thanks for the help.

**Comment by ciur** [comment]
On what operating system are you running papermerge ?
Do you have there `/usr/bin/file` utility ?
Can you run following command (on that machine where papermerge is deployed) ?:
```
/usr/bin/file --mime-type -b <path-to-file>
```

**Comment by Chavell3** [comment]
okay... already the folder "media" does not exist under /core_app

**Comment by Chavell3** [comment]
Okay, I now added the docker volumes manually to mount those to my wanted folders.

![putty_02012024_112327](https://github.com/ciur/papermerge/assets/56268217/092a2066-4118-4c2a-85c3-17fe2df4da81)

But it still seems not to mount those volumes correctly.
I do found the issue... which is, that the worker and web node are not mounting the media volume correctly somehow, although it is listed when running "df"

Worker-Node:
![putty_02012024_112459](https://github.com/ciur/papermerge/assets/56268217/0886823e-d452-4501-b69a-a87caa0b6d13)

Web-Node:
![putty_02012024_112540](https://github.com/ciur/papermerge/assets/56268217/b1dc59d6-68c0-4c8a-b45d-8677f7076d06)

Somehow the web node has access to such volume but the worker node does not...
Interesting is, that /dev/md0 is my raid device where I want the files to be safed but I want to choose some subfolder, DMS/papermerge/..

The docker compose configuration looks like that:
![msedge_02012024_113342](https://github.com/ciur/papermerge/assets/56268217/f8a82f44-c6e4-4271-8914-2354f8e94c2b)

But also there, nowhere just /dev/md0 is defined... it's always some subfolder(either "docker" or "DMS")...

**Comment by Chavell3** [comment]
okay seems like "/dev/md0" is somehow just the naming, but it is correctly mounted to my subfolder within the directory. 
Because when I browser the container's FS and compare that with the local FS where it should be located those files are correct. 

![putty_02012024_115043](https://github.com/ciur/papermerge/assets/56268217/9d60a752-a181-4a2b-9d1f-8fb28d1a5ac8)

That maybe means, somehow the worker node seems not to be able to mount the volume "MEDIA" because of some permission stuff... and same for the WEB node because it does not create any file within that folder...

**Comment by Chavell3** [comment]
I think the issue is, that the folder "media" under /core_apps does not exist. So it cannot mount that volume under that directory.
When I start the WEB node and login into the container, the folder "media" also does not exist.

![putty_02012024_201628](https://github.com/ciur/papermerge/assets/56268217/13f3d98c-1b81-4ea8-8e8c-ce92c599d820)

BUT the difference is, it seems the WEB node does create that folder when the first file is uploaded. While the WORKER node tried to read from a directory that just does not exist, because it was never created or correctly mounted...

**Comment by Chavell3** [comment]
but even if I create that folder, build a new repository from that running container(with the "media" folder) it does not seem to work because still on the host all created files in that volumes are visible or does not exist on the host....

**Comment by Chavell3** [comment]
OKAY shame on me... all my fault...
first tried to directly mount the host folders and messed the config there.
After I fixed that, I did wrote "/core_apps" instead of "/core_app"...
So everything works now.
