### ISSUE TITLE
How to stop integrated worker

### ISSUE THREAD

**Issue by mtonnie** [ciur/papermerge#59]
When I start the worker from manage.py worker and detach the process I'm not able to stop the worker.

There is no stop command and no possibility to write a pid file for the worker process.
I'm facing this issue when I try to create the start/stop mechanism for Synolog package #31 .

I have made a quick an dirty patch to pass the pidfile attributte, but I guess there are other more smarter solution.

Baybe to implement a worker start / workerr stop feature or to implement the pidfile as an optional command line argument.

[001-worker_pidfile.txt](https://github.com/ciur/papermerge/files/5045417/001-worker_pidfile.txt)

What's the prefered solution?

**Comment by ciur** [comment]
start/stop commands should be part of external process management service like SystemD.
I would go with last option - pass optional pid file path as argument - if that works for you,  for me it would be fine as well.
I would gladly accept your PR with that change. With only remark - argument must be optional.

Thank you ! Danke Danke!
