### ISSUE TITLE
does not attach tags

### ISSUE THREAD

**Issue by smart-clouds-09** [ciur/papermerge#590]
Latest release does not attach tags to file and folders.
while creating tags, it is not possible to save the "pinned" flag

 - Papermerge Version 3.0.3

**Comment by ciur** [comment]
Did you press "tab" key when adding tags?

**Comment by smart-clouds-09** [comment]
ups, that was it.. btw, there is a problem with the tab key on mobile devices (apple), so you can't use it..

**Comment by ciur** [comment]
For mobile devices part please open a separate ticket with device type, OS running on it and the detailed step of the issue. Some screenshots or screen recording will help as well.
