### ISSUE TITLE
papermerge-cli import option --delete without any function

### ISSUE THREAD

**Issue by smart-clouds-09** [ciur/papermerge#592]
The option --delete of papermerge-cli has no function. The imported docs are not being deleted

**Info:**
 - Papermerge Version 3.0.3

**Comment by ciur** [comment]
I fixed the problem.
`--delete` option works in `papermerge-cli` 0.7.1, which is already [published](https://pypi.org/project/papermerge-cli/) and ready for use.

For record, here is [Pull Request](https://github.com/papermerge/papermerge-cli/pull/34)
