### ISSUE TITLE
Registered user other than admin cannot log in

### ISSUE THREAD

**Issue by thndrbck** [ciur/papermerge#595]
I created a user but cannot log in under that user. Notice says "unauthorized" in red letters

Created this user in 3.0.2, but couldn't log in then either. Using admin user. Upgraded to 3.0.3, but still cannot use that user.
![Screenshot from 2024-02-08 16-49-11](https://github.com/ciur/papermerge/assets/16791618/82c0bd26-9044-497e-b46c-b981a71879d1)
![Screenshot from 2024-02-08 16-49-43](https://github.com/ciur/papermerge/assets/16791618/d937adc0-c2bf-4de8-b66d-58f091cdfc6d)

 - Papermerge Version 3.0.3

**Comment by ciur** [comment]
I cannot reproduce issue. Could you pls attach the logs ? Do you use docker compose, which setup ?

**Comment by thndrbck** [comment]
I logged in as admin and changed the password for that user. That solved the problem.

**Comment by thndrbck** [comment]
Changing password for that user solved the problem.
