### ISSUE TITLE
Docker desktop on Windows

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#6]
Issue reported by @lucaz82

> Hey I cloned your repo last friday and today.
> 
> Building the containers works fine I suppose but upon starting the papermerge_service container exits with Exit 1 and says standard_init_linux.go:211: exec user process caused "no such file or directory"
> 
> I'm using docker desktop on windows

**Comment by ciur** [comment]
Because I don't have a real Windows box I never tested it in that environment. I will install a windows on my old PC and investigate the issue.

**Comment by tkammerlander** [comment]
Just edit all the .sh files in the docker cotainer folder and follow this guide:
http://sql313.com/index.php/43-main-blogs/maincat-dba/62-using-notepad-to-change-end-of-line-characters
the files should be:
app.startup.sh and
worker.startup.sh

then do a clean build and you are good to go :-)

regards, tom

**Comment by ciur** [comment]
I overlooked one important factor.  Papermerge does not support Windows environment. [I wrote it  in requirements](https://papermerge.readthedocs.io/en/latest/requirements.html#requirements). I am not sure why I kept this ticket open and why I even promised that I will have a look at windows based installation.
Bad, bad Eugen :smile:  !

Sure, you can **use** Papermerge from Windows (via web browser). But deploy it on windows ? Out of scope.

**Comment by tkammerlander** [comment]
I think its more about hosting it on windows and that works. I dont know how Microsoft exactly does it but i think they use WSL to run linux docker images on windows os. so just for your info it is possible to run linux containers on Windows OS. i use the same setup for my tests. regards, thomas

**Comment by voarsh2** [comment]
> Just edit all the .sh files in the docker cotainer folder and follow this guide:
> http://sql313.com/index.php/43-main-blogs/maincat-dba/62-using-notepad-to-change-end-of-line-characters
> 
> the files should be:
> app.startup.sh and
> worker.startup.sh
> 
> then do a clean build and you are good to go :-)
> a clean build is done by entering:
> docker-compose build --no-cache
> 
> after that is finished start everything up with:
> docker-compose up -d
> regards, tom

I followed this and couldn't get it working on Windows.

```Attaching to postgres_db, papermerge_worker, papermerge_app
papermerge_app | standard_init_linux.go:211: exec user process caused "not a directory"
papermerge_worker | standard_init_linux.go:211: exec user process caused "not a directory"
postgres_db |
postgres_db | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_db |
postgres_db | 2020-11-05 15:36:14.203 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_db | 2020-11-05 15:36:14.204 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_db | 2020-11-05 15:36:14.204 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_db | 2020-11-05 15:36:14.206 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_db | 2020-11-05 15:36:14.216 UTC [25] LOG:  database system was shut down at 2020-11-05 15:16:14 UTC
postgres_db | 2020-11-05 15:36:14.219 UTC [1] LOG:  database system is ready to accept connections
papermerge_worker exited with code 1
papermerge_app exited with code 1```
