### ISSUE TITLE
New Video + Online Demo

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#60]
I recorded new demo video - [here is youtube link](https://www.youtube.com/watch?v=OpwTaEN5t2Y).
In video is presented a workflow which I use very often for my own documents (batch scan -> email -> papermerge -> organize pages).It might be useful for you as well.
There is a online demo as well: [https://demo.papermerge.com](https://demo.papermerge.com/)
Credentials are open for everyone: 
- username: guest 
- password: password77a

**Comment by Pyromane** [comment]
The demo access is great. Thank you!

**Comment by ciur** [comment]
> The demo access is great. Thank you!

you are welcome!
