### ISSUE TITLE
Group-menu not visible

### ISSUE THREAD

**Issue by anionDev** [ciur/papermerge#600]
Hello,

the [documentation](https://docs.papermerge.io/3.0/user/user-interface/) tells something about groups and some screenshots also show a group-menu on the left side of the web-application. But when I install and run a new papermerge-server (v3) then all things seems to work (upload documents, create new users, etc.) except the group-menu. The menu is simply not visible and this does not seem to be correct:

![image](https://github.com/ciur/papermerge/assets/19505692/12a29ae3-bdb1-4bd5-a7a1-834d3bb9033d)

Are groups still a feature and if yes how can i activate it?

I can reproduce this behavior with both MariaDB and PostgreSQL.
I can also reproduce this behavior in Chrome and Firefox without any browser-console-error.

**Comment by ciur** [comment]
Thank you for taking you time and opening this ticket!

Version 3 does not support groups. Documentation is misleading. 
I will update documentation.

Groups will be introduced in 3.3 along with access management (role, groups, permissions, per user, per node etc).

**Comment by anionDev** [comment]
ok, thank you very much for the answer. sounds good! ✅

**Comment by ciur** [comment]
I will keep this ticket opened as a reminder for me about that specific part of the docs that needs to be updated.

**Comment by ciur** [comment]
I updated the docs for 3.1 i.e. the screenshots and texting does won't mention groups as they are not there yet.
Again I updated only 3.1 docs: https://docs.papermerge.io/3.1/user/user-interface/
