### ISSUE TITLE
when creating a new folder input does not receive focus

### ISSUE THREAD

**Issue by viktor-c** [ciur/papermerge#625]
**Description**
After clicking on Create new folder a nice dialog appears to name the folder. I expect the input box to receive `focus`, so that I can __immediately start typing__ in the name.

Also after typing the name hitting Enter does not submit the form (which in html code does miss `form` tag and is only surrounded by divs of the modal)

**Info:**
 - Papermerge Version 3.2

**Comment by ciur** [comment]
Thank you for opening this ticket report

**Comment by ciur** [comment]
Fix is available in 3.3. The screenrecorder did not capture the mouse pointer, but that is not the important here. Important
part is that when modal opens - the title input component gets automatically the focus. 

![Peek 2024-12-27 18-30](https://github.com/user-attachments/assets/1401e856-4c1a-4a88-9531-043bca60199c)
