### ISSUE TITLE
Problem with the Users and Groups windows

### ISSUE THREAD

**Issue by dandan-ux** [ciur/papermerge#637]
**Description**
![image](https://github.com/user-attachments/assets/de9b7771-3fbf-4a54-b458-88c5ac0386ef)
Whenever I try to create a user or a group this thing happens. The window is not centered and going beyon borders of the browser. 
Changing the browser size doesn't help, it stays there. 

**Info:**
 - Papermerge Version [e.g. 3.3]

**Comment by dandan-ux** [comment]
![image](https://github.com/user-attachments/assets/eddb2bad-460b-4faf-aec9-f96ffe82f524)
I changed the browser, it fixed the issue.

**Comment by nicekiwi** [comment]
@dandan-ux what do you mean by you changed the browser? I have this issue with all popups in 3.3 in Google Chrome.
