### ISSUE TITLE
Fixed database configuration in docker containers

### ISSUE THREAD

**Issue by sbonfert** [ciur/papermerge#66]
In the file docker/1.4/config/app.production.py the configuration variables for the database are set statically. That means, that credentials, port and the hostname cannot be chosen, but are predefined.
Can you change that to allow for custom configurations, most preferably set by environment variables?

**Comment by ciur** [comment]
Hi @sbonfert,

sounds like a very good point! I will change compose.yml + docker/1.4/config/app.production.py to use/read from environment variables.

Thank you for heads up!
