### ISSUE TITLE
Ability to download multiple documents at once

### ISSUE THREAD

**Issue by ivandc33** [ciur/papermerge#70]
Hi, wondering if you plan to add the ability to download multiple documents at once.  Also add the option to download from the action menu in the folder view.

**Comment by ciur** [comment]
Hi @ivandc33,

thank you for your time and opening an issue.

Download multiple documents at once sounds very reasonable and to be honest I was thinking about this feature for some time.
It will definitely be implemented.
However at this point in time I cannot tell you in which release.
For sure it won't be next release (1.5) as it is already "booked" with high priority features like tags management.

**Comment by goldcoders** [comment]
its possible by collating all files to one tar.gz or zip file....
shell script has easy way to do it,with os module in python maybe i can make a pull request on this one....

**Comment by ciur** [comment]
will be shipped with 1.5 release.

**Comment by ciur** [comment]
Feature is implemented (right now it is in master branch).
