### ISSUE TITLE
Add document date (vs added date)

### ISSUE THREAD

**Issue by totti4ever** [ciur/papermerge#71]
I can only find "creation date", I think date added and document date are better - the latter one should be read automagically from the document...otherwise no chance for me to use this

**Comment by ciur** [comment]
Hi @totti4ever,

can you please describe in more detail what you mean with

   > the latter one should be read automagically from the document

? 
What exactly you mean by _"document date_" ? or "_date added_" ?

I would love understand better your requirement.
Thank you for your feedback!

**Comment by totti4ever** [comment]
document date: date the letter (which are eventually most of my docs) has been written
good for finding documents and/or showing them in the right order
_can be found by taking the first date in the ocred text_

date added: date the pdf file was added to paper merge
good for finding documents added lately

from my understanding only the latter one is available right now

**Comment by ciur** [comment]
Hi @totti4ever,

Now I understand your point.
"document date" can be added using metadata feature.
Below are screenshots with a quick 3 step example:

**Step 1 - in folder titled e.g. 2020**

![step-01](https://user-images.githubusercontent.com/24827601/90415764-dbd19480-e0b1-11ea-8205-4084749a2360.png)

**Step 2 - open any document in folder 2020**

![step-02](https://user-images.githubusercontent.com/24827601/90415800-e5f39300-e0b1-11ea-9dd1-496994565a42.png)

**Step 3 - inside folder 2020, change to list view**

![step-03](https://user-images.githubusercontent.com/24827601/90415825-eee46480-e0b1-11ea-9673-5073d9fe4497.png)

Further more, you can process of extracting metadata can be [automated](https://papermerge.readthedocs.io/en/latest/automation.html).
However, I add soon documentation about "Automates" and how to write + configure plugins (feature is part of 1.4.0, it works, but not yet documented).

**Comment by totti4ever** [comment]
Hi, I see your point. But this makes the whole system for me not usable fluenty...I might check back in half a year or so to see whether it's more convenient to use then.

keep up the effort, it's great!
