### ISSUE TITLE
Manual Installation Issue on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#75]
Got [feedback on reddit:](https://www.reddit.com/r/selfhosted/comments/ibwuj2/papermerge_14_out/g22o04e?utm_source=share&utm_medium=web2x)

> 
> I would prefer the manual installation route due to filesystem ease of access, but attempting the install on a clean image of Ubuntu 20.04 results in error after error (python/python3/pip/pip3 related issues, pdftk errors, django errors, /etc/papermerge.conf.py access errors, 'pip wheel' needs installed to fix a bdist_wheel error, & more).
> 
> And even after working through all of those the process of starting the worker throws an error saying that debug settings are being used and to never use those in prod as it leads to a memory leak and I've got no idea how to fix that.
> 
> Lastly, I then don't know what the best route to make those processes auto-start at server boot would be.

**Comment by ciur** [comment]
I will even record a screencast on this topic!

**Comment by dohlin** [comment]
Sorry for the late reply, and thanks for taking the feedback...hopefully it didn't sound rude I certainly didn't mean it that way :)

Also to be honest, when I posted the feedback I had already deleted the VM I had spun up (in no small part because I had run so many different trial & error commands during my install & troubleshooting that things just had started to feel really "messy" and disorganized)

That being said, I'd be happy to to test any updated directions and contribute any refinements.  Thank you!

**Comment by Pyromane** [comment]
I am available for tests!
I use Ubuntu 20.04 in LXC containers.

**Comment by ciur** [comment]
Great! I am very happy that there people ready to help!
Documentation updates, follows...

**Comment by ciur** [comment]
> Also - I'm still getting these 2 memory leak warnings when running the worker: https://imgur.com/a/il66qdH
> Is this expected or anything to be concerned about? Thanks!

Those warning are issued because you run Papermerge in DEBUG mode. As long as you run it from you own computer (or only for home networks - that is from 100% safe environment) and only "in manual way" - means you start application with ``./manage.py runserver`` + ``./manage.py worker`` command there is nothing to be concerned about.

DEBUG mode means that during an exception all stacktrace with all environment variables, paths etc will be printed on the screen - this is a big problem if you run application "in the wild" (in wild wild Internet :))) )

> 
> How does one make it so that the server binds to 0.0.0.0 rather than 127.0.0.1 (so the web UI is accessible from other PC's in the LAN)
> 
Use runserver command:

>   $ ./manage.py runserver 0.0.0.0:8090

It will bind application  on IP 0.0.0.0 on port 8090. Obviously you can use any other port greater than 1024. Port 8090 is just a random example.

> 2. How does one make it so that the main app and the worker both start automatically after system reboot?

This is part of [next documentation ticket I am going to work on](https://github.com/ciur/papermerge/issues/96).

Otherwise I think this ticket is good to be closed. 
@dohlin, what do you think?

Ah, @dohlin, completely unrelated, but still I think useful tip: 
Instead of uploading images to imgur.com and copy/paste url here, you can drag and drop directly images directly in this edit box. It is confusing because editor does not have "upload image" button... but still it supports drag and drop. I found out that myself couple of days ago.

**Comment by dohlin** [comment]
> Ah, @dohlin, completely unrelated, but still I think useful tip:
> Instead of uploading images to imgur.com and copy/paste url here, you can drag and drop directly images directly in this edit box. It is confusing because editor does not have "upload image" button... but still it supports drag and drop. I found out that myself couple of days ago.

Good to know, thanks for that heads up!

> > $ ./manage.py runserver 0.0.0.0:8090
> 
> It will bind application on IP 0.0.0.0 on port 8090. Obviously you can use any other port greater than 1024. Port 8090 is just a random example.

Probably wouldn't hurt to add this to the manual docs, but this answers my question!

> Those warning are issued because you run Papermerge in DEBUG mode. As long as you run it from you own computer (or only for home networks - that is from 100% safe environment) and only "in manual way" - means you start application with `./manage.py runserver` + `./manage.py worker` command there is nothing to be concerned about.
> 
> DEBUG mode means that during an exception all stacktrace with all environment variables, paths etc will be printed on the screen - this is a big problem if you run application "in the wild" (in wild wild Internet :))) )

> Otherwise I think this ticket is good to be closed.
> @dohlin, what do you think?

Not like I'm going to be exposing this to the internet lol, but just for my knowledge is there a way to run it in PROD mode?  Or is DEBUG mode just how the project is run in its current state?

Otherwise yes - ok to close and I'll keep watching that 'auto start' documentation ticket.  Thanks again!

**Comment by ciur** [comment]
> I think I resolved my non-debug question myself by changing "DEBUG = True" to "DEBUG = False" in [PapermergeDMS root]\config\settings\dev.py

@dohlin , correct !
Thank you very much for great feedback + ticket!

**Comment by Pyromane** [comment]
Wow, that's a great guide!
I followed detailed version and this one worked perfectly.
