### ISSUE TITLE
Does it support Mariadb/MySQL

### ISSUE THREAD

**Issue by BobWs** [ciur/papermerge#76]
Hi,
I would love to try your program, but at the moment I’m only using Docker Mariadb for all my DB related containers. So I was wondering if your app supports Mariadb, I couldn’t find anything about that.

**Comment by ciur** [comment]
Good point !

I never tried it, but in theory it should. Application code uses a layer of abstraction over DB - django's ORM system. So in theory you can configure it with madiadb/MySql as well.

I will keep this ticket for reference to update documentation and try it myself with mariadb.
Thank you for opening this issue!

**Comment by BobWs** [comment]
Good to know thanks for the opportunity. If you need someone for testing let me know, I’m glad to help. All the Docker container I’m running at the moment are running on Synology NAS.

**Comment by ciur** [comment]
great! 
Now there are around 10 new tickets. So it will take maybe a week until I will handle this one.

**Comment by francescocarzaniga** [comment]
I opened #158 to address this. Please take a look if this approach is decent enough.

**Comment by ciur** [comment]
@francescocarzaniga, thank you for your PR! I merged  it into master !
