### ISSUE TITLE
[Request] Release on dockerhub

### ISSUE THREAD

**Issue by bktz** [ciur/papermerge#8]
Hello,

I think creating a new docker-compose.yml for deployments that contains pre-built docker images published to DockerHub would make standing up a new deployment of papermerge much simpler. With the images in DockerHub they can now be referenced in a new docker-compose.yml file (similar to how docker-compose is currently referencing postgres) which would remove the build step.

This could also be used to version releases of papermerge as well.

What are your thoughts?

**Comment by ciur** [comment]
Sounds good to me! I will take care of it. 
@bktz thanks for opening an issue.

**Comment by ciur** [comment]
- [Papermerge app image](https://hub.docker.com/r/eugenci/papermerge)
- [Papermerge worker image](https://hub.docker.com/r/eugenci/papermerge-worker)

Also default docker/docker-compose.yml will pull from docker-hub images. There is docker/docker-compose-dev version which will do older way i.e. will build local images.

And the [diff](https://github.com/ciur/papermerge/commit/bdc4e6419a1883e06878e7c0d8537826bd11792d)

**Comment by hrvylein** [comment]
I have to admit, i'm new to docker and hate it.

I want to install an edms on my synology NAS. Any instructions on how to use these specific containers? Which folders must be persistent? How to backup? Additional containers needed? Where to config these containers?
