### ISSUE TITLE
Docker Image Set GID an UID with environment variables

### ISSUE THREAD

**Issue by Philap95** [ciur/papermerge#80]
Hi,
im using a Synology Nas (DS218+) and want to run the docker container, but every time i get issues with the file permissions between the container and host filesystem, yeah setting rights to public on the Nas should make it work, but for private documents thats not an option, so it would great to be able to set the Gid and Uid in the environment variables of the container.

Maybe this could help [https://vsupalov.com/docker-shared-permissions/](https://vsupalov.com/docker-shared-permissions/)

**Comment by okoetter** [comment]
I am using ´Linuxserver`s docker image and it's way easier to setup on my Synology NAS than the original docker files. But does anybody know how to use the worker to monitor a directory with scans with it?

**Comment by ciur** [comment]
Hi @okoetter!

The setting you are looking for is [IMPORTER_DIR](https://papermerge.readthedocs.io/en/latest/settings.html#document-importer). You need to change it only on worker side/container.

The thing is, I don't run Papermerge via Docker on the daily basis, so it is very difficult for me to advice you how to correctly play nicely with docker images.
I assume you need somehow to map your local/network folder to same point  [IMPORTER_DIR](https://papermerge.readthedocs.io/en/latest/settings.html#document-importer) is pointing to within docker image.

I updated documentation with how to [apply changes in Docker Container](https://papermerge.readthedocs.io/en/latest/setup/docker.html#configuration-changes-in-docker-container).

Maybe there are docker experts in this thread who can help you (and me!) in regards of docker image. Given such useful info, I will gladly update documentation.

**Comment by okoetter** [comment]
Hi @ciur, 
thanks for your answer. 
No, I do not need help how to map my local folder to the docker image. And the use of `IMPORTER_DIR` is also clear. What I don't understand is how I get the second container (worker container. I don't use the third db container as I want to use sqlite).  I only have the main app container.
I cannot use your docker files as `docker-compose up` does not build correctly on my Synology NAS. When I am asked for the region and I enter 8 for Europe nothing happens. 
So I chose `Linuxserver`'s docker image as I made some good experiences with his images. But that is only the main app container and I also need a worker container to import from my scans folder, correct? Or can I do **both in one container**?

**Comment by sizzicus** [comment]
@okoetter 

I figured this out for myself last night:  

If you're using the linuxserver.io image you can set the IMPORTER_DIR setting in papermerge.conf.py in the image's /config directory.  Then it seems to work fine.  Not an ideal solution, but the linuxserver image only allows a few env variables passed in.

Maybe it would also work to maintain your own papermerge.conf.py and pass it into the linuxserver image with bind mount.

**Comment by okoetter** [comment]
@sizzicus 
Thanks for the info. I will create a "/scan" directory inside the container, point IMPORTER_DIR to that and map that folder within Docker to the real external dir.
But does the one linuxserver.io image also provide periodically calling the worker app to check the import folder for new scans?
I thought there was a second container needed for that.

**Comment by sizzicus** [comment]
The auto importing definitely works correctly once you tell it where to look, so they must have correctly integrated all three parts of this app.  (linuxserver.io is all about making single integrated images that all work on the same base image and setup rules)

**Comment by okoetter** [comment]
OK, I can't get it to work.

This is what I've done:

- shell inside the container with `docker exec -it linuxserver-papermerge1 /bin/bash` and create `/import` folder
- mount my nas folder `/volume1/scan` to docker container's `/import`
- check that my pdf are visible inside container's  `/import` by `ls -l /import`
- check that IMPORTER_DIR is set correctly by `cat /config/papermerge.conf.py`:
IMPORTER_DIR = "/import/"
- restart container

but my pdfs never show up in Papermerge. What do I do wrong?

**Comment by sizzicus** [comment]
Hi,

I didn't need to enter the running container to make this work.

1) I have the container's /config directory mapped out to a volume called docs_config.  This should work for a direct path mount also.

2) After starting up the container for the first time, it generates papermerge.conf.py in that volume.

3) I stopped/removed the container (docker-compose down) and then edited that file from the host system to add an importer_dir entry below the rest of the path settings:

<other stuff>
MEDIA_DIR = "/data/media"
STATIC_DIR = "/app/papermerge/static"
MEDIA_URL = "/media/"
STATIC_URL = "/static/"
IMPORTER_DIR = "/import/"
<other stuff>

4) I edited my docker compose file to add a bind mount mapping for /import:

- ./import:/import

(you do not have to create the /import directory inside the running container)

5) I created/started the container again and found it working - it detects a new file in <30s probably?  You should see the worker printing out log entries in docker-compose logs -f even if the importer is not set up.  If it is working, you will see something like this when it finds your file:

papermerge | [2020-09-21 00:41:16,744: INFO/ForkPoolWorker-2] Importing file /import/dummy.pdf...
papermerge | [2020-09-21 00:41:16,749: INFO/ForkPoolWorker-2] Same as temp_file_name=/tmp/tmp3u7a2292/dummy.pdf...
papermerge | [2020-09-21 00:41:16,754: DEBUG/ForkPoolWorker-2] Importing file /tmp/tmp3u7a2292/dummy.pdf.
papermerge | [2020-09-21 00:41:16,964: DEBUG/ForkPoolWorker-2] Post save doc => normalize_pages
papermerge | [2020-09-21 00:41:16,968: DEBUG/ForkPoolWorker-2] Normalizing document 12
etc...

I hope this helps!

**Comment by okoetter** [comment]
I got it working now, thanks for your help. It was a permissions problem with my scan share on my NAS.

To get German OCR working in `Linuxserver`'s image I had to bash into the container and
- `apt update`
- `apt install tesseract-ocr-deu` to install the German tesseract package

Hope that helps others.
