### ISSUE TITLE
Easy select multiple documents. Selecting documents one by one is a pain

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#81]
[Feedback from reddit](https://www.reddit.com/r/selfhosted/comments/ibwuj2/papermerge_14_out/g25mu21?utm_source=share&utm_medium=web2x&context=3)

Selecting documents is painful, having to select one by one. No way to multi-select with shift is a pain when dealing with multiple 
documents.

**Comment by goldcoders** [comment]
maybe change the ui to checkbox , what front end framework you using, react? vue ? svelte? or vanilla js?

**Comment by ciur** [comment]
@goldcoders, [papermerge-js ](https://github.com/ciur/papermerge-js) is the front-end project. It is a mix of vanilla, bootstrap and backbone.js all packed with webpack.

**Comment by ciur** [comment]
Better selection. New select All/Folders/Documents/Invert Selection/Deselect menu was added.
Adding "draggable" selection (sort of UI rectangle to select UI elements under it) is too much trouble - for a moment I won't include it. Maybe will be included in next releases.
