### ISSUE TITLE
having to go through the "actions-> ..." stuff is also quite tedious, especially the paste

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#82]
having to go through the "actions-> ..." stuff is also quite tedious, especially the paste, which is a 2-level action. Having a popup when selecting a document or multiple documents at the mouse-cursor or being able to right-click would be nicer, or maybe just even buttons at the top, since this is functionality you'll use a lot.

**Comment by tf198** [comment]
Have you considered a **Move to** action?
* Select items
* click **Move To**
* pops up a folder browser allowing you to select the destination

Feels a bit more intuitive to me, especially if you are filing a large number of things from the inbox.
Drag and drop is less useful when you have multiple levels of folders.

PS. Love the project - is well on its way to becoming the best DMS out there...

**Comment by ciur** [comment]
> PS. Love the project - is well on its way to becoming the best DMS out there...

Thank  you! It feels great to hear kind words!

> Have you considered a Move to action?
> 
>     Select items
>     click Move To
>     pops up a folder browser allowing you to select the destination

It never crossed my mind actually - maybe because it was shadowed by idea of cut/paste. I will open a new ticket to keep an eye on it (it is actually very easy to implement)

**Comment by ciur** [comment]
Right click menu was added. Will be available since next 2.0 release.
Here is a preview.
![right-click](https://user-images.githubusercontent.com/24827601/99504590-04eb1500-2980-11eb-8d44-3df862432b18.png)
