### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by luismanson** [ciur/papermerge#9]
Hello, im an Spanish user. I want to test the app since I understand a bit of python, but noticed there is no Spanish support. I gave a quick look the source and saw some language related stuff in the database. 

Do you plan to add language support? 
Can you outline the areas where language is hard coded? 

thanks

**Comment by ciur** [comment]
@luismanson I will add detailed documentation describing areas one needs to change to include a particular language support. Thank you for opening a ticket.

**Comment by ciur** [comment]
Documentation updated. Description of [adding a language support is here](https://papermerge.readthedocs.io/en/latest/developers_guide/language_support.html).

**Comment by luismanson** [comment]
Thanks for the docs. I'll try to help. Looking at papermerge/core/pgsql/03_update_lang_cols.sql and noticed that the UPDATE core_basetreenode is run twise for English. 
Is that right? 
Also, i've just branched repo and started editing the mentioned files, Is there something else to do? like generate database migrations?

**Comment by luismanson** [comment]
@ciur It did not work. Can you take a look?
