### ISSUE TITLE
Docker installation with Unraid

### ISSUE THREAD

**Issue by guim31** [ciur/papermerge#93]
[Paste from Reddit post]

Hi everyone,

please someone could give me hint on how to make it work on my Unraid server ?I pulled the eugenci/papermerge image but I don't know how to configure it...:

/config allocation, /db ?, internal/external port, other ?

I'm used to those types of way to go (example woth SabNZBd) :

```
docker create \ 
--name=sabnzbd \ 
-e PUID=1000 \ 
-e PGID=1000 \ 
-e TZ=Europe/London \ 
-p 8080:8080 \ 
-p 9090:9090 \ 
-v /path/to/data:/config \ 
-v /path/to/downloads:/downloads \ 
-v /path/to/incomplete/downloads:/incomplete-downloads
--restart unless-stopped \   
linuxserver/sabnzbd
```

But I'm not able to use the docker compose method.
Any hints for me ?

**Comment by guim31** [comment]
As I'm not in a hurry I'll choose to wait a little bit more to try an Unraid template if someone creates one.

Too much console for me 😇

**Comment by fumunda** [comment]
I understand. :)  Its pretty simple with User scripts from the CA though.

**Comment by AlexanderEDavis** [comment]
Linuxserver have released their CA template on Unraid

**Comment by Quotic** [comment]
Yes it is working fine :)

**Comment by Quotic** [comment]
@ciur I think you can close this (?)
