### ISSUE TITLE
How do you auto start or run as a service?

### ISSUE THREAD

**Issue by lukyjay** [ciur/papermerge#96]
Hi

I can't find any documentation on how to auto-start or run this software as a service in my Ubuntu 20.04 LXC container (under proxmox).

Is there any information on this? 

Regards
Jayden

**Comment by dohlin** [comment]
Just FYI - assuming this was noticed but the "papermerge-worker.service:" and "papermerge-server.service:" in the systemd config example post above seem to be reversed :)

**Comment by ciur** [comment]
> Just FYI - assuming this was noticed but the "papermerge-worker.service:" and "papermerge-server.service:" in the systemd config example post above seem to be reversed :)

right!

@dohlin, this ticket is continuation of your issue #75. Once you installed manually and ./manage.py runserver + manage.py worker commands worked  - next level is to configuring Papermerge to run as service. Service - usually assumes that application in production mode (DEBUG=False). I will paste here URL when documentation will be updated.

**Comment by lukyjay** [comment]
> Just FYI - assuming this was noticed but the "papermerge-worker.service:" and "papermerge-server.service:" in the systemd config example post above seem to be reversed :)

Only in my GitHub comment 😉



> > Just FYI - assuming this was noticed but the "papermerge-worker.service:" and "papermerge-server.service:" in the systemd config example post above seem to be reversed :)
> 
> right!
> 
> @dohlin, this ticket is continuation of your issue #75. Once you installed manually and ./manage.py runserver + manage.py worker commands worked - next level is to configuring Papermerge to run as service. Service - usually assumes that application in production mode (DEBUG=False). I will paste here URL when documentation will be updated.

My instance is giving me an error regarding debug mode being enabled. Can this be disabled via a setting in the conf file?

**Comment by dohlin** [comment]
> > Just FYI - assuming this was noticed but the "papermerge-worker.service:" and "papermerge-server.service:" in the systemd config example post above seem to be reversed :)
> 
> Only in my GitHub comment 😉
> 
> > > Just FYI - assuming this was noticed but the "papermerge-worker.service:" and "papermerge-server.service:" in the systemd config example post above seem to be reversed :)
> > 
> > 
> > right!
> > @dohlin, this ticket is continuation of your issue #75. Once you installed manually and ./manage.py runserver + manage.py worker commands worked - next level is to configuring Papermerge to run as service. Service - usually assumes that application in production mode (DEBUG=False). I will paste here URL when documentation will be updated.
> 
> My instance is giving me an error regarding debug mode being enabled. Can this be disabled via a setting in the conf file?

You can set debug = false in settings.py on the config folder, but this seems to break the login page, at least on Chrome.

**Comment by ciur** [comment]
Hi guys!

this [is documentation page you were looking for](https://papermerge.readthedocs.io/en/latest/setup/server_configurations.html).
It is work in progress.
There I document systemd service examples for worker and main app. Server configurations for apache and nginx.
