### ISSUE TITLE
OCR english using docker-compose

### ISSUE THREAD

**Issue by fumunda** [ciur/papermerge#97]
Ok, so i may be an idiot but I cannot figure out how to default to english using docker-compose.  I have read the closed post on how to do it.  I even made changes in both worker and main containers but when i docker-compose down and then docker-compose up -d, both containers come back up with my changes gone. 

what the heck am i doing wrong?

using 1.4 brand new git clone and running docker-compose from /docker/1.4

explain it to me like i am a child please ;)

**Comment by ciur** [comment]
@fumunda , did you managed to solve your issue ?

**Comment by hactar** [comment]
@fumunda @ciur  If you want your config to be permanent you need to link it to an outside volume on the host. Add an entry to the worker section of the docker-compose file. For example if you cloned the repo like in the install instructions, you have a papermerge.config.py file already - edit this one, and then expose it to your container as below.

```
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/app/queue
      - ./config/papermerge.config.py:/opt/app/papermerge.conf.py
      - /home/brother_scanner/importer_dir:/mnt/importer_dir
```

**Comment by Perry3D** [comment]
Would be nice to have this in the documentation. This line is a little bit misleading:
https://github.com/ciur/papermerge/blob/b0d36a58af302257093b7f4f7abbeb724c7a6d04/docs/source/setup/docker.rst#L136
Or even better, change the docker-compose.yml file.
